import type { Citation, DocumentTableFact, SearchResult } from "@/lib/types";

// GEN-C2 / GEN-H2 — shared numeric faithfulness verification.
//
// The fast/strong LLM routes synthesize prose, so dose figures, ANC/FBC
// thresholds, and timing intervals are regenerated by the model and can be
// transcribed or rounded incorrectly. Numeric fidelity is the highest-risk
// property of a clinical answer, so after generation we extract every
// numeric/dose/threshold token from the ANSWER and confirm each one appears
// verbatim in the text of a CITED chunk. Tokens that are not entailed by any
// cited source are surfaced as "unverified" so the answer can be flagged
// ("verify against source") rather than silently trusted.
//
// This is intentionally conservative: it never rewrites numbers, only reports
// which asserted figures are unsupported by the cited evidence.

// Matches clinical numeric tokens: doses, thresholds, ranges, percentages,
// and unit-bearing figures. Examples it should catch:
//   12.5 mg, 25-50 mg, 2.0 ×10⁹/L, 1500 mg/day, 0.4 mmol/L, 100 mcg, 12 hours,
//   ANC 2.0, 80%, 3/7. Bare integers like "1" or "3" are excluded by default
//   (too noisy / rarely a clinical figure) unless attached to a unit or range.
const NUMERIC_TOKEN_PATTERN =
  /\b\d+(?:[.,]\d+)?(?:\s*[-–—]\s*\d+(?:[.,]\d+)?)?\s*(?:%|mg\/(?:day|kg|m2|dose)?|mg|mcg|microgram(?:s)?|micrograms?|μg|g\b|kg|ml|mL|l\b|mmol\/l|mmol\/L|mmol|mol\/l|umol\/l|µmol\/l|ng\/ml|units?\/?\w*|iu\b|×10\^?\d*\/?l?|x10\^?\d*\/?l?|×10⁹\/l|hours?|hrs?|hours|h\b|days?|weeks?|wk\b|months?|minutes?|mins?|years?|°c|mmhg|bpm)\b/giu;

// Decimal numbers and ranges that, while not unit-bearing, are very likely
// clinical thresholds in context (e.g. "ANC 2.0", "INR 2-3"). We only treat a
// bare number as significant when it is a decimal or part of a range, to avoid
// flagging incidental integers.
const SIGNIFICANT_BARE_NUMBER_PATTERN = /\b\d+(?:[.,]\d+)?\s*[-–—]\s*\d+(?:[.,]\d+)?\b|\b\d+\.\d+\b/gu;

function normalizeNumericToken(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-")
    .replace(/,/g, ".")
    .replace(/µ/g, "μ")
    .trim();
}

// Build a normalized haystack from a single text blob so token lookups are
// whitespace/case/dash insensitive (matches how normalizeNumericToken folds).
function normalizeHaystack(text: string): string {
  return text
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/,/g, ".")
    .replace(/µ/g, "μ")
    .replace(/\s+/g, " ");
}

// A token "appears" in the source if either the spaced or the de-spaced form is
// present, so "2.0 mg" in the answer matches "2.0mg" or "2.0 mg" in the source.
function haystackContainsToken(haystack: string, despacedHaystack: string, token: string): boolean {
  const normalized = token; // already normalized/de-spaced by caller
  if (despacedHaystack.includes(normalized)) return true;
  // Also try a spaced variant: re-insert a space between number and unit.
  const spaced = normalized.replace(/^(\d+(?:\.\d+)?(?:-\d+(?:\.\d+)?)?)/, "$1 ");
  return haystack.includes(spaced);
}

export function extractNumericTokens(text: string): string[] {
  if (!text) return [];
  const tokens = new Set<string>();
  for (const match of text.matchAll(NUMERIC_TOKEN_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  for (const match of text.matchAll(SIGNIFICANT_BARE_NUMBER_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  return [...tokens];
}

function tableFactText(fact: DocumentTableFact): string {
  return [fact.table_title, fact.row_label, fact.clinical_parameter, fact.threshold_value, fact.action]
    .filter(Boolean)
    .join(" ");
}

function sourceTextForResult(result: SearchResult): string {
  const parts: string[] = [result.content ?? ""];
  if (result.adjacent_context) parts.push(result.adjacent_context);
  if (result.section_heading) parts.push(result.section_heading);
  if (result.table_facts?.length) parts.push(result.table_facts.map(tableFactText).join(" "));
  if (result.memory_cards?.length) parts.push(result.memory_cards.map((card) => card.content).join(" "));
  if (result.index_unit) parts.push([result.index_unit.title, result.index_unit.content].filter(Boolean).join(" "));
  return parts.join(" ");
}

export type NumericVerification = {
  /** Every numeric/dose/threshold token extracted from the answer. */
  answerTokens: string[];
  /** Tokens from the answer NOT found in any cited chunk's text. */
  unverifiedTokens: string[];
  /** True when at least one numeric token is unsupported by cited sources. */
  hasUnverifiedNumbers: boolean;
};

// Verify every numeric token in `answerText` against the combined text of the
// chunks the answer actually cites. Only cited chunks count — an answer that
// cites nothing has no support, so all of its numbers are unverified.
export function verifyAnswerNumbers(
  answerText: string,
  citations: Array<Pick<Citation, "chunk_id">>,
  results: SearchResult[],
): NumericVerification {
  const answerTokens = extractNumericTokens(answerText);
  if (answerTokens.length === 0) {
    return { answerTokens, unverifiedTokens: [], hasUnverifiedNumbers: false };
  }

  const citedIds = new Set(citations.map((citation) => citation.chunk_id));
  const citedResults = results.filter((result) => citedIds.has(result.id));
  // If no citation maps to a known chunk, fall back to all results so we don't
  // over-flag during transitional states; cited-only is preferred when present.
  const sourceResults = citedResults.length > 0 ? citedResults : results;

  const combined = sourceResults.map(sourceTextForResult).join(" \n ");
  const haystack = normalizeHaystack(combined);
  const despacedHaystack = haystack.replace(/\s+/g, "");

  const unverifiedTokens = answerTokens.filter(
    (token) => !haystackContainsToken(haystack, despacedHaystack, token),
  );

  return {
    answerTokens,
    unverifiedTokens,
    hasUnverifiedNumbers: unverifiedTokens.length > 0,
  };
}

export const VERIFY_AGAINST_SOURCE_NOTE =
  "Some figures in this answer could not be matched verbatim to the cited sources — verify against the source documents before acting.";
