import type { Citation, DocumentTableFact, SearchResult } from "@/lib/types";

// GEN-C2 / GEN-H2 — shared numeric faithfulness verification.
//
// The fast/strong LLM routes synthesize prose, so dose figures, ANC/FBC
// thresholds, and timing intervals are regenerated by the model and can be
// transcribed or incorrectly rounded. Numeric fidelity is the highest-risk
// property of a clinical answer, so after generation we extract every
// numeric/dose/threshold token from the ANSWER and confirm each one appears
// verbatim in the text of a CITED chunk. Tokens that are not entailed by any
// cited source are surfaced as "unverified" so the answer can be flagged
// ("verify against source") rather than silently trusted.
//
// This is intentionally conservative: it never rewrites numbers, only reports
// which asserted figures are unsupported by the cited evidence.

// Matches clinical numeric tokens: doses, thresholds, ranges, percentages,
// and unit-bearing figures.
// Hardened to include complex clinical units (mg/kg/day, mmol/L, etc.) and
// ensure boundary safety to prevent hallucinated decimal bypass.
// The ×10^n / ×10⁹ scientific-notation branch is listed BEFORE the bare unit
// branches so "2.0 ×10⁹/L" is captured whole rather than truncated to "2.0".
// The percentage branch must NOT be followed by \b: "%" is a non-word char, so
// a trailing \b after it can never match (it would require a word char to its
// right), which previously dropped every percentage token.
const NUMERIC_TOKEN_PATTERN =
  /\b\d+(?:[.,]\d+)?(?:\s*[-–—]\s*\d+(?:[.,]\d+)?)?\s*(?:×10\^?\d*\/?l?|x10\^?\d*\/?l?|mg\/(?:day|kg|m2|dose)|mg|mcg|micrograms?|μg|g\b|kg|ml|mL|l\b|mmol\/[lL]|mmol|mol\/[lL]|umol\/[lL]|µmol\/[lL]|ng\/ml|units?\/?\w*|iu\b|hours?|hrs?|h\b|days?|weeks?|wk\b|months?|minutes?|mins?|years?|°c|mmhg|bpm)\b|\b\d+(?:[.,]\d+)?\s*%/giu;

// Decimal numbers and ranges that, while not unit-bearing, are very likely
// clinical thresholds in context (e.g. "ANC 2.0", "INR 2-3"). We only treat a
// bare number as significant when it is a decimal or part of a range, to avoid
// flagging incidental integers.
const SIGNIFICANT_BARE_NUMBER_PATTERN = /\b\d+(?:[.,]\d+)?\s*[-–—]\s*\d+(?:[.,]\d+)?\b|\b\d+\.\d+\b/gu;

// Unicode superscript digits ⁰¹²³⁴⁵⁶⁷⁸⁹ → ASCII. Sources and answers mix
// "×10⁹/L" with "x10^9/L"; folding superscripts to ASCII before extraction and
// matching keeps ANC/WBC thresholds (central to the clozapine use-case) from
// being mangled or silently dropped.
const SUPERSCRIPT_DIGITS: Record<string, string> = {
  "⁰": "0",
  "¹": "1",
  "²": "2",
  "³": "3",
  "⁴": "4",
  "⁵": "5",
  "⁶": "6",
  "⁷": "7",
  "⁸": "8",
  "⁹": "9",
};

function foldSuperscripts(text: string): string {
  return text.replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]/g, (ch) => SUPERSCRIPT_DIGITS[ch] ?? ch);
}

function normalizeNumericToken(raw: string): string {
  return foldSuperscripts(raw)
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-")
    .replace(/,/g, ".")
    .replace(/µ/g, "μ")
    .replace(/×10\^?(\d+)/g, "x10^$1")
    .replace(/x10(\d)/g, "x10^$1")
    .trim();
}

export function extractNumericTokens(text: string): string[] {
  if (!text) return [];
  const folded = foldSuperscripts(text);
  const tokens = new Set<string>();
  for (const match of folded.matchAll(NUMERIC_TOKEN_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  for (const match of folded.matchAll(SIGNIFICANT_BARE_NUMBER_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  return [...tokens];
}

function tableFactText(fact: DocumentTableFact): string {
  return [fact.table_title, fact.row_label, fact.clinical_parameter, fact.threshold_value, fact.action]
    .filter(Boolean)
    .join(" ");
}

function sourceTextForResult(result: SearchResult): string {
  const parts: string[] = [result.content ?? ""];
  if (result.adjacent_context) parts.push(result.adjacent_context);
  if (result.section_heading) parts.push(result.section_heading);
  if (result.table_facts?.length) parts.push(result.table_facts.map(tableFactText).join(" "));
  if (result.memory_cards?.length) parts.push(result.memory_cards.map((card) => card.content).join(" "));
  if (result.index_unit) parts.push([result.index_unit.title, result.index_unit.content].filter(Boolean).join(" "));
  return parts.join(" ");
}

export type NumericVerification = {
  /** Every numeric/dose/threshold token extracted from the answer. */
  answerTokens: string[];
  /** Tokens from the answer NOT found in any cited chunk's text. */
  unverifiedTokens: string[];
  /** True when at least one numeric token is unsupported by cited sources. */
  hasUnverifiedNumbers: boolean;
};

// Verify every numeric token in `answerText` against the numeric tokens of the
// chunks the answer actually cites. Only cited chunks count — an answer that
// cites nothing has no support, so all of its numbers are unverified.
//
// B1: matching is by SET MEMBERSHIP of normalized numeric tokens, never by
// substring. Substring matching let "2.5 mg" match inside "12.5 mg" (a 5x dose
// error) and "500 mg" inside "1500 mg". We extract the source's tokens with the
// SAME extractor used on the answer, so a number is verified only when an exact
// normalized token (e.g. "2.5mg") is present in the source's token set.
export function verifyAnswerNumbers(
  answerText: string,
  citations: Array<Pick<Citation, "chunk_id">>,
  results: SearchResult[],
): NumericVerification {
  const answerTokens = extractNumericTokens(answerText);
  if (answerTokens.length === 0) {
    return { answerTokens, unverifiedTokens: [], hasUnverifiedNumbers: false };
  }

  const citedIds = new Set(citations.map((citation) => citation.chunk_id));
  const citedResults = results.filter((result) => citedIds.has(result.id));
  // N1: fail closed. If nothing the answer cites maps to a known chunk, we have
  // no scoped evidence — treat every numeric token as unverified rather than
  // matching against the full unfiltered result set (which could "verify" a
  // number that lives in a chunk the answer never cited).
  if (citedResults.length === 0) {
    return { answerTokens, unverifiedTokens: answerTokens, hasUnverifiedNumbers: answerTokens.length > 0 };
  }

  const sourceTokens = sourceNumericTokenSet(citedResults);
  const unverifiedTokens = answerTokens.filter((token) => !sourceTokens.has(token));

  return {
    answerTokens,
    unverifiedTokens,
    hasUnverifiedNumbers: unverifiedTokens.length > 0,
  };
}

// Build the union of normalized numeric tokens across a set of source chunks
// using the same extractor applied to the answer, so verification is an exact
// token-membership test rather than a substring scan.
function sourceNumericTokenSet(results: SearchResult[]): Set<string> {
  const tokens = new Set<string>();
  for (const result of results) {
    for (const token of extractNumericTokens(sourceTextForResult(result))) {
      tokens.add(token);
    }
  }
  return tokens;
}

export const VERIFY_AGAINST_SOURCE_NOTE =
  "CRITICAL: Some figures in this answer could not be matched verbatim to the cited sources — verify against the source documents before acting.";
