import { appendRoutingReason } from "@/lib/rag-routing";
import type {
  AnswerSectionKind,
  Citation,
  ConflictOrGap,
  DocumentTableFact,
  RagAnswer,
  SearchResult,
} from "@/lib/types";

// GEN-C2 / GEN-H2 — shared numeric faithfulness verification.
//
// The fast/strong LLM routes synthesize prose, so dose figures, ANC/FBC
// thresholds, and timing intervals are regenerated by the model and can be
// transcribed or incorrectly rounded. Numeric fidelity is the highest-risk
// property of a clinical answer, so after generation we extract every
// numeric/dose/threshold token from the ANSWER and confirm each one appears
// verbatim in the text of a CITED chunk. Tokens that are not entailed by any
// cited source are surfaced as "unverified" so the answer can be flagged
// ("verify against source") rather than silently trusted.
//
// This is intentionally conservative: it never rewrites numbers, only reports
// which asserted figures are unsupported by the cited evidence.

// Matches clinical numeric tokens: doses, thresholds, ranges, percentages,
// and unit-bearing figures. Examples it should catch:
//   12.5 mg, 25-50 mg, 2.0 ×10⁹/L, 1500 mg/day, 0.4 mmol/L, 100 mcg, 12 hours,
//   ANC 2.0, 80%. Bare integers like "1" or "3" are excluded by default
//   (too noisy / rarely a clinical figure) unless attached to a unit or range.
// The ×10^n / ×10⁹ scientific-notation branch is listed BEFORE the bare unit
// branches so "2.0 ×10⁹/L" is captured whole rather than truncated to "2.0".
// The percentage branch must NOT be followed by \b: "%" is a non-word char, so
// a trailing \b after it can never match (it would require a word char to its
// right), which previously dropped every percentage token.
const NUMERIC_TOKEN_PATTERN =
  /\b\d+\s*:\s*\d+\b|\b\d+(?:[.,]\d+)?(?:\s*[-–—]\s*\d+(?:[.,]\d+)?)?\s*(?:×10\^?\d*\/?l?|x10\^?\d*\/?l?|mg\/(?:day|hour|hr|h|kg|m2|dose)|mg|mcg|ug|microgram(?:s)?|micrograms?|μg|g\b|kg|ml\/(?:day|hour|hr|h)|ml|mL|l\b|mmol\/l|mmol\/L|mmol|mol\/l|umol\/l|µmol\/l|ng\/ml|units?\/?\w*|iu\b|hours?|hrs?|h\b|days?|weeks?|wk\b|months?|minutes?|mins?|years?|°c|mmhg|bpm)\b|\b\d+(?:[.,]\d+)?\s*%/giu;

// Decimal numbers and ranges that, while not unit-bearing, are very likely
// clinical thresholds in context (e.g. "ANC 2.0", "INR 2-3"). We only treat a
// bare number as significant when it is a decimal or part of a range, to avoid
// flagging incidental integers.
const SIGNIFICANT_BARE_NUMBER_PATTERN = /\b\d+(?:[.,]\d+)?\s*[-–—]\s*\d+(?:[.,]\d+)?\b|\b\d+\.\d+\b/gu;

// Unicode superscript digits ⁰¹²³⁴⁵⁶⁷⁸⁹ → ASCII. Sources and answers mix
// "×10⁹/L" with "x10^9/L"; folding superscripts to ASCII before extraction and
// matching keeps ANC/WBC thresholds (central to the clozapine use-case) from
// being mangled or silently dropped.
const SUPERSCRIPT_DIGITS: Record<string, string> = {
  "⁰": "0",
  "¹": "1",
  "²": "2",
  "³": "3",
  "⁴": "4",
  "⁵": "5",
  "⁶": "6",
  "⁷": "7",
  "⁸": "8",
  "⁹": "9",
};

function foldSuperscripts(text: string): string {
  return text.replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹]/g, (ch) => SUPERSCRIPT_DIGITS[ch] ?? ch);
}

function normalizeNumericToken(raw: string): string {
  return foldSuperscripts(raw)
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-")
    .replace(/,/g, ".")
    .replace(/µ/g, "μ")
    .replace(/ug\b/g, "mcg")
    .replace(/×10\^?(\d+)/g, "x10^$1")
    .replace(/x10(\d)/g, "x10^$1")
    .trim();
}

export function extractNumericTokens(text: string): string[] {
  if (!text) return [];
  const folded = foldSuperscripts(text);
  const tokens = new Set<string>();
  for (const match of folded.matchAll(NUMERIC_TOKEN_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  for (const match of folded.matchAll(SIGNIFICANT_BARE_NUMBER_PATTERN)) {
    const normalized = normalizeNumericToken(match[0]);
    if (normalized) tokens.add(normalized);
  }
  return [...tokens];
}

function tableFactText(fact: DocumentTableFact): string {
  // Diff-review completion of audit H1: rich-mode prompts resolve a "table
  // snippet" from these fact-metadata fields when no image is attached
  // (tableSnippetForFact in rag.ts), so numbers the model copies from them
  // must count as verified too.
  const metadata = (fact.metadata ?? {}) as Record<string, unknown>;
  const metadataString = (key: string) => (typeof metadata[key] === "string" ? (metadata[key] as string) : "");
  const metadataCells = Array.isArray(metadata.cells) ? (metadata.cells as unknown[]).map(String).join(" ") : "";
  return [
    fact.table_title,
    fact.row_label,
    fact.clinical_parameter,
    fact.threshold_value,
    fact.action,
    metadataString("accessible_table_markdown"),
    metadataString("table_text_snippet"),
    metadataCells,
  ]
    .filter(Boolean)
    .join(" ");
}

// The verification corpus must cover the SAME text the model was shown in
// buildRagSourceBlock (rag.ts): retrieval_synopsis and image table text are
// rendered into the prompt, so a number the model faithfully copied from them
// must count as verified. Omitting them blanked correct dose/threshold answers
// whose figures lived only in a synopsis or table-crop text (audit H1); this
// mirrors sourceTextForQuoteVerification in rag.ts.
function sourceTextForResult(result: SearchResult): string {
  const parts: string[] = [result.content ?? ""];
  if (result.adjacent_context) parts.push(result.adjacent_context);
  if (result.section_heading) parts.push(result.section_heading);
  if (result.retrieval_synopsis) parts.push(result.retrieval_synopsis);
  if (result.table_facts?.length) parts.push(result.table_facts.map(tableFactText).join(" "));
  if (result.memory_cards?.length) parts.push(result.memory_cards.map((card) => card.content).join(" "));
  if (result.index_unit) parts.push([result.index_unit.title, result.index_unit.content].filter(Boolean).join(" "));
  if (result.images?.length) {
    parts.push(
      result.images
        .map((image) =>
          [image.tableLabel, image.tableTitle, image.caption, image.tableTextSnippet, image.accessibleTableMarkdown]
            .filter(Boolean)
            .join(" "),
        )
        .join(" "),
    );
  }
  return parts.join(" ");
}

export type NumericVerification = {
  /** Every numeric/dose/threshold token extracted from the answer. */
  answerTokens: string[];
  /** Tokens from the answer NOT found in any cited chunk's text. */
  unverifiedTokens: string[];
  /** True when at least one numeric token is unsupported by cited sources. */
  hasUnverifiedNumbers: boolean;
};

// Verify every numeric token in `answerText` against the numeric tokens of the
// chunks the answer actually cites. Only cited chunks count — an answer that
// cites nothing has no support, so all of its numbers are unverified.
//
// B1: matching is by SET MEMBERSHIP of normalized numeric tokens, never by
// substring. Substring matching let "2.5 mg" match inside "12.5 mg" (a 5x dose
// error) and "500 mg" inside "1500 mg". We extract the source's tokens with the
// SAME extractor used on the answer, so a number is verified only when an exact
// normalized token (e.g. "2.5mg") is present in the source's token set.
export function verifyAnswerNumbers(
  answerText: string,
  citations: Array<Pick<Citation, "chunk_id">>,
  results: SearchResult[],
): NumericVerification {
  const answerTokens = extractNumericTokens(answerText);
  if (answerTokens.length === 0) {
    return { answerTokens, unverifiedTokens: [], hasUnverifiedNumbers: false };
  }

  const citedIds = new Set(citations.map((citation) => citation.chunk_id));
  const citedResults = results.filter((result) => citedIds.has(result.id));
  // N1: fail closed. If nothing the answer cites maps to a known chunk, we have
  // no scoped evidence — treat every numeric token as unverified rather than
  // matching against the full unfiltered result set (which could "verify" a
  // number that lives in a chunk the answer never cited).
  if (citedResults.length === 0) {
    return { answerTokens, unverifiedTokens: answerTokens, hasUnverifiedNumbers: answerTokens.length > 0 };
  }

  // Top-level citations do not identify which sentence each citation supports.
  // Require a numeric claim to be present in every cited chunk rather than
  // allowing an unrelated citation to verify a number by union membership.
  const sourceTokenSets = citedResults.map((result) => sourceNumericTokenSet([result]));
  const unverifiedTokens = answerTokens.filter((token) => !sourceTokenSets.every((tokens) => tokens.has(token)));

  return {
    answerTokens,
    unverifiedTokens,
    hasUnverifiedNumbers: unverifiedTokens.length > 0,
  };
}

// Build the union of normalized numeric tokens across a set of source chunks
// using the same extractor applied to the answer, so verification is an exact
// token-membership test rather than a substring scan.
function sourceNumericTokenSet(results: SearchResult[]): Set<string> {
  const tokens = new Set<string>();
  for (const result of results) {
    for (const token of extractNumericTokens(sourceTextForResult(result))) {
      tokens.add(token);
    }
  }
  return tokens;
}

export const VERIFY_AGAINST_SOURCE_NOTE =
  "CRITICAL: Some figures in this answer could not be matched verbatim to the cited sources — verify against the source documents before acting.";

// GEN-C2 / GEN-H2: verify every numeric/dose/threshold token in the generated
// answer against the text of its cited chunks. Unsupported figures are recorded
// on the answer and an explicit "verify against source" caveat is appended so a
// paraphrased/mis-transcribed dose can never read as authoritative.
const actionableNumericAnswerPattern =
  /\b(?:dose|dosage|dosing|mg|mcg|microgram|micrograms|route|oral|intramuscular|\bim\b|\bpo\b|frequency|daily|twice|weekly|monthly|hourly|threshold|cutoff|cut-off|anc|fbc|wbc|withhold|cease|stop|discontinue|red\s+(?:result|range|zone)|amber\s+(?:result|range|zone)|green\s+(?:result|range|zone)|monitor|monitoring|interval|repeat|review|risk\s+score|risk|score|escalat|urgent)\b/i;

const actionableNumericSectionKinds = new Set<AnswerSectionKind>([
  "medication_dose",
  "thresholds",
  "monitoring_timing",
  "escalation_risk",
  "required_actions",
]);

function hasActionableNumericContext(answer: RagAnswer) {
  if (!answer.grounded || answer.confidence === "unsupported") return false;
  if (answer.queryClass === "medication_dose_risk" || answer.queryClass === "table_threshold") return true;
  if (
    (answer.answerSections ?? []).some((section) => section.kind && actionableNumericSectionKinds.has(section.kind))
  ) {
    return true;
  }
  const text = [
    answer.answer,
    answer.routingReason,
    ...(answer.answerSections ?? []).flatMap((section) => [section.heading, section.body]),
  ]
    .filter(Boolean)
    .join(" ");
  return actionableNumericAnswerPattern.test(text);
}

export function applyNumericVerification(answer: RagAnswer): RagAnswer {
  const sources = answer.sources ?? [];
  const unverified = new Set<string>();

  // B4: the model is instructed to put dose details in structured
  // answerSections (kind medication_dose), so a top-level-only scan never sees
  // section-body doses. Verify the top-level answer AND every section body.
  // Each section is scoped to its own citation_chunk_ids when present, so a
  // dose is only credited against the chunks that section actually cites;
  // sections with no citations fall back to the answer-level citations.
  const answerVerification = verifyAnswerNumbers(answer.answer, answer.citations, sources);
  for (const token of answerVerification.unverifiedTokens) unverified.add(token);

  for (const section of answer.answerSections ?? []) {
    const sectionCitations =
      section.citation_chunk_ids.length > 0
        ? section.citation_chunk_ids.map((chunk_id) => ({ chunk_id }))
        : answer.citations;
    const sectionVerification = verifyAnswerNumbers(section.body, sectionCitations, sources);
    for (const token of sectionVerification.unverifiedTokens) unverified.add(token);
  }

  if (unverified.size === 0) return answer;

  const unverifiedTokens = [...unverified];
  answer.unverifiedNumericTokens = unverifiedTokens;
  answer.faithfulnessWarning = VERIFY_AGAINST_SOURCE_NOTE;
  // P8: never bold a figure the system could not verify against the cited sources — bold emphasis
  // must track verification, or an unverified dose/threshold reads as authoritative while its caveat
  // sits in a separate block. Un-wrap **…** only around segments carrying an unverified token.
  answer.answer = unboldUnverifiedNumbers(answer.answer, unverified);
  if (answer.answerSections?.length) {
    answer.answerSections = answer.answerSections.map((section) => ({
      ...section,
      body: unboldUnverifiedNumbers(section.body, unverified),
    }));
  }
  // Surface as a source gap so the UI's existing gap rendering shows it, and
  // never let an answer with unverified clinical numbers claim high confidence.
  // This gate runs more than once on the model path (parse-time and finalize-time), so REPLACE any
  // earlier faithfulness caveat rather than appending a duplicate "CRITICAL…" gap; the latest run
  // carries the freshest token list.
  const caveat: ConflictOrGap = {
    type: "gap",
    message: `${VERIFY_AGAINST_SOURCE_NOTE} Unverified figures: ${unverifiedTokens.join(", ")}.`,
  };
  answer.conflictsOrGaps = [
    ...(answer.conflictsOrGaps ?? []).filter((gap) => !gap.message.startsWith(VERIFY_AGAINST_SOURCE_NOTE)),
    caveat,
  ];
  if (hasActionableNumericContext(answer)) {
    answer.answer =
      "I found source material, but the generated answer included clinical numbers that could not be matched verbatim to its cited source chunks. Review the source passages directly before using this for dose, threshold, route, timing, monitoring, or risk decisions.";
    answer.grounded = false;
    answer.confidence = "unsupported";
    answer.responseMode = "evidence_gap";
    answer.answerSections = [];
    answer.citations = [];
    answer.quoteCards = [];
    answer.routingReason = appendRoutingReason(answer.routingReason, "numeric_faithfulness_gate_source_gap");
    return answer;
  }
  if (answer.confidence === "high") answer.confidence = "medium";
  return answer;
}

// Remove bold emphasis around any **…** segment that contains a numeric token the source-numeric
// verification could not confirm, leaving the text intact (just un-emphasised). Verified bold stays.
export function unboldUnverifiedNumbers(text: string, unverified: Set<string>): string {
  if (!unverified.size || !text.includes("**")) return text;
  return text.replace(/\*\*([^*]+)\*\*/g, (full, inner: string) =>
    extractNumericTokens(inner).some((token) => unverified.has(token)) ? inner : full,
  );
}
