import crossModeDifferentialIndex from "@/data/cross-mode-differentials-index.json";
import type { CrossModeDifferentialCatalog } from "@/lib/cross-mode-links";

// Returns the precomputed, lightweight cross-mode differentials catalog
// (src/data/cross-mode-differentials-index.json, generated by
// scripts/build-cross-mode-differentials-index.mjs). Importing the ~53 KB trimmed
// index — instead of @/lib/differentials — keeps the lazily-loaded cross-mode chunk
// from statically pulling the ~1.2 MB differentials snapshot just to build a tiny
// {slug,title,clinicalHinge} + presentations + aliases catalog.
//
// tests/cross-mode-differentials-index.test.ts asserts this equals the live
// projection over the full snapshot, and `npm run check:cross-mode-index` fails when
// the committed index is stale, so the two can never drift.
export function crossModeDifferentialCatalog(): CrossModeDifferentialCatalog {
  return crossModeDifferentialIndex as CrossModeDifferentialCatalog;
}
