import therapiesIndexJson from "@/data/therapies-index.json";
import { rankTherapyCandidates } from "@/lib/therapy-ranking";

// Server-side therapy catalogue. Backed by src/data/therapies-index.json — a trimmed,
// rankable projection of the ~2.5 MB public Therapy Compass dataset (regenerated by
// scripts/build-therapies-index.mjs). The interactive tool screens still fetch the full
// dataset client-side via src/components/therapy-compass/data/use-therapy-data.ts; this
// module exists so routes can resolve a therapy by slug server-side (generateStaticParams /
// notFound / generateMetadata) and so the universal-search "therapies" domain can rank the
// library without shipping the full dataset into the server graph.

export type TherapyIndexRecord = {
  slug: string;
  name: string;
  category: string | null;
  modality: string | null;
  clinicalSummary: string | null;
  bestUsedFor: string | null;
  targetSymptoms: string | null;
  indications: string | null;
  reviewStatus: string;
  patientSheetAvailable: boolean;
  briefInterventionAvailable: boolean;
  tags: string[];
  aliases: string[];
};

export const therapyRecords = therapiesIndexJson as TherapyIndexRecord[];

const bySlug = new Map(therapyRecords.map((record) => [record.slug, record]));

export function findTherapyRecord(slug: string): TherapyIndexRecord | undefined {
  return bySlug.get(slug);
}

export function therapyRecordExists(slug: string): boolean {
  return bySlug.has(slug);
}

export function therapySlugs(): string[] {
  return therapyRecords.map((record) => record.slug);
}

/** Slugs whose record ships a brief-intervention version (the rest 404 that route). */
export function therapyBriefSlugs(): string[] {
  return therapyRecords.filter((record) => record.briefInterventionAvailable).map((record) => record.slug);
}

/** Slugs whose record ships a patient sheet (the rest 404 that route). */
export function therapySheetSlugs(): string[] {
  return therapyRecords.filter((record) => record.patientSheetAvailable).map((record) => record.slug);
}

/** True when a therapy still awaits qualified-clinician sign-off. */
export function therapyNeedsReview(record: TherapyIndexRecord): boolean {
  return record.reviewStatus !== "reviewed";
}

export type TherapySearchMatch = { record: TherapyIndexRecord; score: number };

/**
 * Rank the therapy library for a query through the shared universal profile.
 * The full catalogue uses the same ranking owner with its established profile.
 * An empty query returns
 * the alphabetical library (stable order) so the universal-search domain can
 * still surface a browse list.
 */
export function searchTherapyRecords(query: string): TherapySearchMatch[] {
  return rankTherapyCandidates(therapyRecords, query, "universal");
}
