import therapiesIndexJson from "@/data/therapies-index.json";

// Server-side therapy catalogue. Backed by src/data/therapies-index.json — a trimmed,
// rankable projection of the ~2.5 MB public Therapy Compass dataset (regenerated by
// scripts/build-therapies-index.mjs). The interactive tool screens still fetch the full
// dataset client-side via src/components/therapy-compass/data/use-therapy-data.ts; this
// module exists so routes can resolve a therapy by slug server-side (generateStaticParams /
// notFound / generateMetadata) and so the universal-search "therapies" domain can rank the
// library without shipping the full dataset into the server graph.

export type TherapyIndexRecord = {
  slug: string;
  name: string;
  category: string | null;
  modality: string | null;
  clinicalSummary: string | null;
  bestUsedFor: string | null;
  targetSymptoms: string | null;
  indications: string | null;
  reviewStatus: string;
  patientSheetAvailable: boolean;
  briefInterventionAvailable: boolean;
  tags: string[];
  aliases: string[];
};

export const therapyRecords = therapiesIndexJson as TherapyIndexRecord[];

const bySlug = new Map(therapyRecords.map((record) => [record.slug, record]));

export function findTherapyRecord(slug: string): TherapyIndexRecord | undefined {
  return bySlug.get(slug);
}

export function therapyRecordExists(slug: string): boolean {
  return bySlug.has(slug);
}

export function therapySlugs(): string[] {
  return therapyRecords.map((record) => record.slug);
}

/** Slugs whose record ships a brief-intervention version (the rest 404 that route). */
export function therapyBriefSlugs(): string[] {
  return therapyRecords.filter((record) => record.briefInterventionAvailable).map((record) => record.slug);
}

/** Slugs whose record ships a patient sheet (the rest 404 that route). */
export function therapySheetSlugs(): string[] {
  return therapyRecords.filter((record) => record.patientSheetAvailable).map((record) => record.slug);
}

/** True when a therapy still awaits qualified-clinician sign-off. */
export function therapyNeedsReview(record: TherapyIndexRecord): boolean {
  return record.reviewStatus !== "reviewed";
}

const normalize = (value: string | null | undefined) =>
  (value ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

function haystackFor(record: TherapyIndexRecord): string {
  return normalize(
    [
      record.name,
      record.category,
      record.modality,
      record.bestUsedFor,
      record.targetSymptoms,
      record.clinicalSummary,
      record.indications,
      record.tags.join(" "),
      record.aliases.join(" "),
    ]
      .filter(Boolean)
      .join(" "),
  );
}

export type TherapySearchMatch = { record: TherapyIndexRecord; score: number };

/**
 * Rank the therapy library for a query. Mirrors the client scorer in
 * data/select.ts but runs over the trimmed server index. An empty query returns
 * the alphabetical library (stable order) so the universal-search domain can
 * still surface a browse list.
 */
export function searchTherapyRecords(query: string): TherapySearchMatch[] {
  const normalizedQuery = normalize(query);
  const queryTokens = normalizedQuery.split(" ").filter(Boolean);

  return therapyRecords
    .map((record, index) => {
      const name = normalize(record.name);
      const aliases = record.aliases.map(normalize);
      const tags = normalize(record.tags.join(" "));
      const bestUsedFor = normalize(record.bestUsedFor);
      const targetSymptoms = normalize(record.targetSymptoms);
      const haystack = haystackFor(record);

      // No query → preserve alphabetical order as a descending browse score.
      let score = normalizedQuery ? 0 : therapyRecords.length - index;

      if (normalizedQuery) {
        if (name === normalizedQuery) score += 100;
        else if (name.startsWith(normalizedQuery)) score += 55;
        else if (name.includes(normalizedQuery)) score += 30;
        if (aliases.some((alias) => alias === normalizedQuery)) score += 60;
        else if (aliases.some((alias) => alias.includes(normalizedQuery))) score += 22;
        if (tags.includes(normalizedQuery)) score += 18;
        if (bestUsedFor.includes(normalizedQuery)) score += 10;
        if (targetSymptoms.includes(normalizedQuery)) score += 8;
        for (const token of queryTokens) {
          if (name.includes(token)) score += 12;
          if (aliases.some((alias) => alias.includes(token))) score += 8;
          if (tags.includes(token)) score += 6;
          if (haystack.includes(token)) score += 3;
        }
      }

      return score > 0 ? { record, score } : null;
    })
    .filter((match): match is TherapySearchMatch => Boolean(match))
    .sort((left, right) => right.score - left.score || left.record.name.localeCompare(right.record.name));
}
