import therapiesIndexJson from "@/data/therapies-index.json";
import { rankTherapyCandidates } from "@/lib/therapy-ranking";

// Server-side therapy catalogue. Backed by src/data/therapies-index.json — a trimmed,
// rankable projection of the ~2.5 MB public Therapy Compass dataset (regenerated by
// scripts/build-therapies-index.mjs). The interactive tool screens still fetch the full
// dataset client-side via src/components/therapy-compass/data/use-therapy-data.ts; this
// module exists so routes can resolve a therapy by slug server-side (generateStaticParams /
// notFound / generateMetadata) and so the universal-search "therapies" domain can rank the
// library without shipping the full dataset into the server graph.

export type TherapyIndexRecord = {
  slug: string;
  name: string;
  category: string | null;
  clinicalSummary: string | null;
  bestUsedFor: string | null;
  targetSymptoms: string | null;
  indications: string | null;
  reviewStatus: string;
  patientSheetAvailable: boolean;
  briefInterventionAvailable: boolean;
  tags: string[];
  aliases: string[];
};

export const therapyRecords = therapiesIndexJson as TherapyIndexRecord[];

const bySlug = new Map(therapyRecords.map((record) => [record.slug, record]));

function defaultTherapyEnvironment(): string | undefined {
  return process.env.PLAYWRIGHT_OFFLINE_MODE === "true" ? "development" : process.env.NODE_ENV;
}

/**
 * Whether production withholds therapy records that have not completed clinical
 * review.
 *
 * Was implicitly `true`: production filtered every record whose `reviewStatus`
 * was not `reviewed`, which — with the whole catalogue unreviewed — meant an
 * empty library, and `devOnly` on the mode hid the entrance entirely. The owner
 * lifted both on 2026-08-18, deliberately and with the numbers in hand: 205
 * records, 0 reviewed, 1435 unticked checklist items.
 *
 * Written as a named constant rather than deleting the filter, for three
 * reasons. Re-arming the gate is a one-word edit if that decision is revisited;
 * the condition stays greppable, so "why is unreviewed content live?" has an
 * answer at the point of the decision; and `therapyNeedsReview` keeps its
 * meaning for every caller that still surfaces review state to the reader —
 * which, now that this filter is off, is the only remaining protection.
 *
 * Nothing here changes a record's data. `reviewStatus` is still `needs_review`,
 * because the alternative — relabelling records as reviewed — would have been a
 * false clinical attestation rather than a product decision.
 */
const HIDE_UNREVIEWED_IN_PRODUCTION = false;

/** Production may expose only records that have completed clinical review. */
export function therapyRecordsForEnvironment(environment = defaultTherapyEnvironment()): TherapyIndexRecord[] {
  return HIDE_UNREVIEWED_IN_PRODUCTION && environment === "production"
    ? therapyRecords.filter((record) => !therapyNeedsReview(record))
    : therapyRecords;
}

export function findTherapyRecord(
  slug: string,
  environment = defaultTherapyEnvironment(),
): TherapyIndexRecord | undefined {
  const record = bySlug.get(slug);
  if (!record) return undefined;
  return !HIDE_UNREVIEWED_IN_PRODUCTION || environment !== "production" || !therapyNeedsReview(record)
    ? record
    : undefined;
}

export function therapyRecordExists(slug: string, environment = defaultTherapyEnvironment()): boolean {
  return Boolean(findTherapyRecord(slug, environment));
}

export function therapySlugs(environment = defaultTherapyEnvironment()): string[] {
  return therapyRecordsForEnvironment(environment).map((record) => record.slug);
}

/** Slugs whose record ships a brief-intervention version (the rest 404 that route). */
export function therapyBriefSlugs(environment = defaultTherapyEnvironment()): string[] {
  return therapyRecordsForEnvironment(environment)
    .filter((record) => record.briefInterventionAvailable)
    .map((record) => record.slug);
}

/** Slugs whose record ships a patient sheet (the rest 404 that route). */
export function therapySheetSlugs(environment = defaultTherapyEnvironment()): string[] {
  return therapyRecordsForEnvironment(environment)
    .filter((record) => record.patientSheetAvailable)
    .map((record) => record.slug);
}

/** True when a therapy still awaits qualified-clinician sign-off. */
export function therapyNeedsReview(record: TherapyIndexRecord): boolean {
  return record.reviewStatus !== "reviewed";
}

export type TherapySearchMatch = { record: TherapyIndexRecord; score: number };

/**
 * Rank the production-safe therapy library through the shared Therapy scorer.
 * An empty query returns the alphabetical library (stable order) so the
 * universal-search domain can still surface a browse list.
 */
export function searchTherapyRecords(query: string, environment = defaultTherapyEnvironment()): TherapySearchMatch[] {
  return rankTherapyCandidates(therapyRecordsForEnvironment(environment), query);
}
