/**
 * Care Plan — deterministic synthetic fixtures.
 *
 * Every person, clinician, team, hospital, plan, presentation, review, and
 * identifier below is invented. The only intentionally real details are the
 * verified public crisis telephone numbers in `publicCrisisContacts`.
 *
 * Nothing here reads a clock, a network, a random source, or a browser API.
 * Every timestamp is derived from `PROTOTYPE_NOW` so the whole prototype is
 * reproducible byte for byte.
 *
 * The prose is written to be imitated. Whatever these fixtures do is what every
 * real plan written in this tool will copy, so `whatMakesItWorse` describes what
 * the service does rather than what the person does wrong, `agreedEdApproach`
 * names who agreed the position and when and never uses a prohibitive
 * construction, and `whatWouldMakeThisDifferent` names concrete new findings.
 */

import { addIsoDays, addIsoMonths } from "./domain";
import {
  REVIEW_DUE_SOON_DAYS,
  REVIEW_INTERVAL_MONTHS,
  type CmhtContact,
  type EdPresentation,
  type EdSite,
  type IdentificationPolicy,
  type IdentificationReview,
  type ManagementPlan,
  type ManagementPlanVersion,
  type Patient,
  type PersonalSafetyPlan,
  type PersonalSafetyPlanVersion,
  type PresentationAmendment,
  type PrototypeUser,
  type PublicCrisisContact,
  type ReviewTrigger,
} from "./types";

/** The single fixed "now" for the whole prototype. Australia/Perth, no DST. */
export const PROTOTYPE_NOW = "2026-08-20T14:30:00+08:00";

export const SYNTHETIC_DATA_MARKER = "Synthetic prototype — fictional people, teams, and hospitals";

/** Replace the time of day on a derived date, so fixture timestamps read like
 *  real working hours instead of every event landing on the same minute. */
function atPerthTime(iso: string, hourAndMinute: string): string {
  return `${iso.slice(0, 11)}${hourAndMinute}:00+08:00`;
}

const daysAgo = (days: number, hourAndMinute: string): string =>
  atPerthTime(addIsoDays(PROTOTYPE_NOW, -days), hourAndMinute);
const monthsAgo = (months: number, hourAndMinute: string): string =>
  atPerthTime(addIsoMonths(PROTOTYPE_NOW, -months), hourAndMinute);

/** Every review date is its own approval date plus the shared review interval. */
const reviewDueFrom = (approvedAt: string): string => addIsoMonths(approvedAt, REVIEW_INTERVAL_MONTHS);

// Approval dates chosen so the fixture set covers all three review states
// against PROTOTYPE_NOW without hardcoding an unrelated calendar date.
const ROWAN_V1_APPROVED_AT = monthsAgo(20, "10:00");
const ROWAN_V2_APPROVED_AT = monthsAgo(3, "11:05");
const MIRA_V1_APPROVED_AT = atPerthTime(
  addIsoDays(addIsoMonths(PROTOTYPE_NOW, -REVIEW_INTERVAL_MONTHS), -(REVIEW_DUE_SOON_DAYS + 7)),
  "15:40",
);
const EVELYN_V1_APPROVED_AT = monthsAgo(16, "13:25");
const ROWAN_SAFETY_CREATED_AT = atPerthTime(
  addIsoDays(addIsoMonths(PROTOTYPE_NOW, -REVIEW_INTERVAL_MONTHS), Math.floor(REVIEW_DUE_SOON_DAYS / 2)),
  "10:20",
);

export const identificationPolicy = {
  id: "SYN-IDENTIFICATION-POLICY-001",
  status: "pending_governance",
  thresholdCount: null,
  thresholdLookbackMonths: null,
  manualReferralEnabled: true,
  explanation:
    "No eligibility rule exists in this prototype. Local clinical and privacy governance must decide who is offered a Management Plan, and on what basis, before this is used operationally. Presentation activity is shown as an objective observation over a named window only: it never creates eligibility, a label for a person, a severity claim, a care pathway, or a plan. Any patient may be referred for Identification Review by an authorised clinician with a stated reason.",
} satisfies IdentificationPolicy;

export const syntheticUsers = [
  {
    id: "SYN-USER-ED-001",
    displayName: "Dr Casey Example",
    title: "Emergency Physician, North River Hospital ED",
    role: "ed_clinician",
  },
  {
    id: "SYN-USER-LIAISON-001",
    displayName: "Morgan Sample",
    title: "ED Mental Health Liaison Clinician",
    role: "liaison_clinician",
  },
  {
    id: "SYN-USER-SENIOR-001",
    displayName: "Dr Taylor Fiction",
    title: "Consultant Psychiatrist, North River Health Service",
    role: "senior_clinician",
  },
  {
    id: "SYN-USER-COORD-001",
    displayName: "Riley Demo",
    title: "Care Planning Coordinator",
    role: "plan_coordinator",
  },
] satisfies readonly PrototypeUser[];

export const syntheticPatients = [
  {
    id: "SYN-PATIENT-001",
    fullName: "Rowan Sample",
    preferredName: "Rowan",
    aliases: ["Ro Sample"],
    mrn: "SYN-MRN-0001",
    dateOfBirth: "1986-04-12",
    ageCohort: "adult",
    pronouns: "they/them",
    homeHealthService: "North River Health Service",
    cmhtId: "SYN-CMHT-001",
    managementPlanId: "SYN-MGMT-PLAN-001",
    personalSafetyPlanId: "SYN-SAFETY-PLAN-001",
  },
  {
    id: "SYN-PATIENT-002",
    fullName: "Mira Example",
    preferredName: "Mira",
    aliases: ["Mira Example-Hale"],
    mrn: "SYN-MRN-0002",
    dateOfBirth: "1948-09-22",
    ageCohort: "older_adult",
    pronouns: "she/her",
    homeHealthService: "Coastal Plains Health Service",
    cmhtId: "SYN-CMHT-002",
    managementPlanId: "SYN-MGMT-PLAN-002",
    personalSafetyPlanId: "SYN-SAFETY-PLAN-002",
  },
  {
    id: "SYN-PATIENT-003",
    fullName: "Jordan Test",
    preferredName: "Jordan",
    aliases: [],
    mrn: "SYN-MRN-0003",
    dateOfBirth: "1994-02-03",
    ageCohort: "adult",
    pronouns: "he/him",
    homeHealthService: "Wandoo District Health Service",
    cmhtId: "SYN-CMHT-003",
    managementPlanId: "SYN-MGMT-PLAN-003",
    personalSafetyPlanId: "SYN-SAFETY-PLAN-003",
  },
  {
    id: "SYN-PATIENT-004",
    fullName: "Evelyn Demo",
    preferredName: "Evie",
    aliases: [],
    mrn: "SYN-MRN-0004",
    dateOfBirth: "1979-11-30",
    ageCohort: "adult",
    pronouns: "she/her",
    homeHealthService: "North River Health Service",
    cmhtId: "SYN-CMHT-001",
    managementPlanId: "SYN-MGMT-PLAN-004",
    personalSafetyPlanId: "SYN-SAFETY-PLAN-004",
  },
  {
    id: "SYN-PATIENT-005",
    fullName: "Alex Fiction",
    preferredName: "Alex",
    aliases: [],
    mrn: "SYN-MRN-0005",
    dateOfBirth: "2001-06-18",
    ageCohort: "adult",
    pronouns: "they/them",
    homeHealthService: "North River Health Service",
    cmhtId: "SYN-CMHT-001",
    managementPlanId: "SYN-MGMT-PLAN-005",
    personalSafetyPlanId: "SYN-SAFETY-PLAN-005",
  },
] satisfies readonly Patient[];

export const syntheticEdSites = [
  { id: "SYN-ED-001", name: "North River Hospital ED", healthService: "North River Health Service" },
  { id: "SYN-ED-002", name: "Coastal Plains Hospital ED", healthService: "Coastal Plains Health Service" },
  { id: "SYN-ED-003", name: "Wandoo District Hospital ED", healthService: "Wandoo District Health Service" },
] satisfies readonly EdSite[];

export const syntheticCmhtContacts = [
  {
    id: "SYN-CMHT-001",
    name: "North River CMHT",
    catchment: "North River metropolitan catchment",
    sharedMailbox: "north-river.cmht@example.org",
    dutyTelephoneDisplay: "0491 570 210",
    dutyTelephoneUri: "+61491570210",
    operatingHours: "Monday to Friday, 8:30 am to 5:00 pm AWST",
    timezone: "Australia/Perth",
    careCoordinator: "Sam Placeholder",
    afterHoursLabel:
      "Outside those hours, the Mental Health Emergency Response Line (MHERL) covers metropolitan Perth. MHERL is a telephone triage and support line and is not an emergency service; call 000 in an emergency.",
    afterHoursTelephoneDisplay: "1300 555 788",
    afterHoursTelephoneUri: "1300555788",
    verifiedAt: daysAgo(21, "09:30"),
    verificationState: "verified",
  },
  {
    id: "SYN-CMHT-002",
    name: "Coastal Plains Older Adult CMHT",
    catchment: "Coastal Plains and Peel older-adult catchment",
    sharedMailbox: "coastal-plains.olderadult.cmht@example.org",
    dutyTelephoneDisplay: "0491 570 211",
    dutyTelephoneUri: "+61491570211",
    operatingHours: "Monday to Friday, 8:30 am to 4:30 pm AWST",
    timezone: "Australia/Perth",
    careCoordinator: "Devon Sample",
    afterHoursLabel:
      "Outside those hours, the Mental Health Emergency Response Line (MHERL) covers the Peel region. MHERL is a telephone triage and support line and is not an emergency service; call 000 in an emergency.",
    afterHoursTelephoneDisplay: "1800 676 822",
    afterHoursTelephoneUri: "1800676822",
    verifiedAt: monthsAgo(7, "09:30"),
    verificationState: "review_due",
  },
  {
    id: "SYN-CMHT-003",
    name: "Wandoo District CMHT",
    catchment: "Wandoo District regional catchment",
    sharedMailbox: "wandoo-district.cmht@example.org",
    dutyTelephoneDisplay: "0491 570 212",
    dutyTelephoneUri: "+61491570212",
    operatingHours: "Monday to Friday, 8:00 am to 4:30 pm AWST",
    timezone: "Australia/Perth",
    careCoordinator: null,
    afterHoursLabel:
      "Outside those hours, Rurallink covers regional and remote Western Australia from 4:30 pm to 8:30 am on weeknights and 24 hours on weekends and public holidays. Rurallink is a telephone triage and support line and is not an emergency service; call 000 in an emergency.",
    afterHoursTelephoneDisplay: "1800 552 002",
    afterHoursTelephoneUri: "1800552002",
    verifiedAt: monthsAgo(19, "09:30"),
    verificationState: "unverified",
  },
] satisfies readonly CmhtContact[];

/**
 * The only non-fictional contact details in the prototype. Verified against the
 * public sources below on 20 August 2026. If a number or an availability window
 * has changed since, correct it here rather than anywhere it is displayed.
 */
export const publicCrisisContacts = [
  {
    id: "SYN-CRISIS-CONTACT-001",
    name: "Emergency services",
    telephoneDisplay: "000",
    telephoneUri: "000",
    coverage: "Australia-wide",
    availability: "24 hours, every day",
    isEmergencyService: true,
    caveat: null,
    sourceUrl: "https://www.triplezero.gov.au/",
    verifiedOn: "2026-08-20",
  },
  {
    id: "SYN-CRISIS-CONTACT-002",
    name: "Mental Health Emergency Response Line (MHERL) — Perth metropolitan",
    telephoneDisplay: "1300 555 788",
    telephoneUri: "1300555788",
    coverage: "Metropolitan Perth",
    availability: "24 hours, every day",
    isEmergencyService: false,
    caveat: "MHERL is a telephone triage and support line. It is not an emergency service; call 000 in an emergency.",
    sourceUrl:
      "https://emhs.health.wa.gov.au/Hospitals-and-Services/Mental-Health-Alcohol-and-Other-Drugs/Inpatient-and-Other-Services/MHERL",
    verifiedOn: "2026-08-20",
  },
  {
    id: "SYN-CRISIS-CONTACT-003",
    name: "Mental Health Emergency Response Line (MHERL) — Peel",
    telephoneDisplay: "1800 676 822",
    telephoneUri: "1800676822",
    coverage: "Peel region",
    availability: "24 hours, every day",
    isEmergencyService: false,
    caveat: "MHERL is a telephone triage and support line. It is not an emergency service; call 000 in an emergency.",
    sourceUrl:
      "https://emhs.health.wa.gov.au/Hospitals-and-Services/Mental-Health-Alcohol-and-Other-Drugs/Inpatient-and-Other-Services/MHERL",
    verifiedOn: "2026-08-20",
  },
  {
    id: "SYN-CRISIS-CONTACT-004",
    name: "Rurallink",
    telephoneDisplay: "1800 552 002",
    telephoneUri: "1800552002",
    coverage: "Regional and remote Western Australia",
    availability: "4:30 pm to 8:30 am on weeknights, and 24 hours on weekends and public holidays",
    isEmergencyService: false,
    caveat:
      "Rurallink is a telephone triage and support line. It is not an emergency service; call 000 in an emergency.",
    sourceUrl:
      "https://emhs.health.wa.gov.au/Hospitals-and-Services/Mental-Health-Alcohol-and-Other-Drugs/Inpatient-and-Other-Services/Rurallink",
    verifiedOn: "2026-08-20",
  },
] satisfies readonly PublicCrisisContact[];

export const syntheticManagementPlans = [
  {
    id: "SYN-MGMT-PLAN-001",
    patientId: "SYN-PATIENT-001",
    versionIds: ["SYN-MGMT-VERSION-001", "SYN-MGMT-VERSION-002"],
    currentVersionId: "SYN-MGMT-VERSION-002",
  },
  {
    id: "SYN-MGMT-PLAN-002",
    patientId: "SYN-PATIENT-002",
    versionIds: ["SYN-MGMT-VERSION-003", "SYN-MGMT-VERSION-004"],
    currentVersionId: "SYN-MGMT-VERSION-003",
  },
  {
    id: "SYN-MGMT-PLAN-003",
    patientId: "SYN-PATIENT-003",
    versionIds: [],
    currentVersionId: null,
  },
  {
    id: "SYN-MGMT-PLAN-004",
    patientId: "SYN-PATIENT-004",
    versionIds: ["SYN-MGMT-VERSION-005"],
    currentVersionId: null,
  },
  {
    id: "SYN-MGMT-PLAN-005",
    patientId: "SYN-PATIENT-005",
    versionIds: ["SYN-MGMT-VERSION-006"],
    currentVersionId: null,
  },
] satisfies readonly ManagementPlan[];

export const syntheticManagementPlanVersions = [
  {
    id: "SYN-MGMT-VERSION-001",
    planId: "SYN-MGMT-PLAN-001",
    version: 1,
    state: "superseded",
    reviewState: null,
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: "SYN-USER-SENIOR-001",
    createdAt: monthsAgo(21, "14:10"),
    submittedAt: monthsAgo(20, "09:20"),
    approvedAt: ROWAN_V1_APPROVED_AT,
    reviewDueAt: reviewDueFrom(ROWAN_V1_APPROVED_AT),
    revisionReason: "First agreed version, written with Rowan after the December 2024 joint review.",
    participationState: "discussed",
    consentedSupportPeople: ["Jess Sample — sister, contactable with Rowan's agreement on the day"],
    returnedReason: null,
    withdrawalReason: null,
    withdrawnBy: null,
    withdrawnAt: null,
    sharedWithPatientAt: null,
    content: {
      howToApproach: [
        "Introduce yourself by name and role, and say how long you expect the assessment to take.",
        "Ask Rowan what they would like to happen before offering options.",
      ],
      whatHelps: [
        "A quiet space away from the main corridor, offered early rather than after distress has escalated.",
        "Telling Rowan the expected wait, and updating them when it changes.",
      ],
      whatMakesItWorse: [
        "Waiting in the main corridor within sight of the ambulance bay; the noise and passing traffic reliably increase distress.",
        "Being asked to repeat the whole history to each new staff member.",
      ],
      agreedEdApproach: [
        "Agreed with Rowan, the North River CMHT and Dr Taylor Fiction on 20 December 2024.",
        "The usual agreed default is assessment in ED and discharge home the same day where that is safe, with a CMHT follow-up call within one working day.",
        "Admission remains available whenever the treating team judges it necessary. This plan records the approach that has usually helped and does not set a ceiling on care.",
      ],
      whatWouldMakeThisDifferent: [
        "New or worsening physical symptoms: chest pain, breathlessness, fever, head injury, seizure, or a fall.",
        "Any first presentation of confusion, disorientation, or a change in conscious state, which has not been part of Rowan's usual pattern.",
        "A stated plan with means and preparation, or an attempt before arrival. This plan describes usual continuity care and does not apply to that presentation.",
      ],
      whyThisPlanExists:
        "Written so that Rowan does not have to renegotiate the same approach while distressed. It supports continuity and never replaces fresh triage, physical assessment, mental-state assessment, immediate risk assessment, clinical judgement, or legal obligations.",
      whatThePersonWants: ["To be told what is happening and roughly how long it will take."],
      practicalNeeds: [],
      physicalHealthAndMedication: [
        "Documented allergy to penicillin; check the hospital allergy record before prescribing.",
      ],
      whoElseIsInvolved: ["North River CMHT is the durable service contact."],
      reviewTriggers: ["Any change of care coordinator, CMHT, or living arrangements."],
    },
  },
  {
    id: "SYN-MGMT-VERSION-002",
    planId: "SYN-MGMT-PLAN-001",
    version: 2,
    state: "current",
    reviewState: "within_review",
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: "SYN-USER-SENIOR-001",
    createdAt: monthsAgo(4, "15:45"),
    submittedAt: monthsAgo(3, "08:50"),
    approvedAt: ROWAN_V2_APPROVED_AT,
    reviewDueAt: reviewDueFrom(ROWAN_V2_APPROVED_AT),
    revisionReason:
      "Updated at the May 2026 joint review: added the short-stay step and the sensory preferences Rowan asked for.",
    participationState: "co_produced",
    consentedSupportPeople: ["Jess Sample — sister, contactable with Rowan's agreement on the day"],
    returnedReason: null,
    withdrawalReason: null,
    withdrawnBy: null,
    withdrawnAt: null,
    sharedWithPatientAt: atPerthTime(addIsoDays(ROWAN_V2_APPROVED_AT, 2), "12:15"),
    content: {
      howToApproach: [
        "Introduce yourself by name and role, and say how long you expect the assessment to take. Rowan settles quickly when the plan for the next hour is said out loud.",
        "Ask Rowan what they would like to happen before offering options. They will usually say directly what they need.",
        "Use short sentences and one question at a time, and leave a pause for the answer before adding another question.",
        "Rowan uses they/them pronouns. Getting this right early makes the rest of the conversation easier.",
      ],
      whatHelps: [
        "A quiet, low-stimulus space away from the main corridor, offered early rather than after distress has escalated.",
        "A drink, a blanket, and a charged phone. Rowan settles considerably once they can contact their sister Jess.",
        "Telling Rowan the expected wait, and updating them when it changes, even when the news is that the wait is longer.",
        "Offering the same familiar approach Rowan has already agreed with the North River CMHT, rather than starting a fresh negotiation at the bedside.",
      ],
      whatMakesItWorse: [
        "Waiting in the main corridor within sight of the ambulance bay. The noise and passing traffic reliably increase distress.",
        "Being asked to repeat the whole history to each new staff member. Read this plan and the triage note first, then confirm only what has changed.",
        "Security staff standing close by when no safety concern has arisen. Their presence reads as an accusation and makes the conversation harder.",
        "Unexplained waits. A wait with a reason attached is tolerable; a silent one is not.",
      ],
      agreedEdApproach: [
        "Agreed with Rowan, the North River CMHT and Dr Taylor Fiction on 20 May 2026, and confirmed at each review since.",
        "The usual agreed default is assessment in ED, a period in the short-stay area where that helps, and discharge home the same day with a CMHT follow-up call within one working day.",
        "Admission remains available whenever the treating team judges it necessary. This plan records the approach that has usually helped; it does not set a ceiling on care and does not bind the clinician in front of Rowan.",
        "Where the agreed default is not followed, record the reason in the presentation so the CMHT can review it with Rowan.",
      ],
      whatWouldMakeThisDifferent: [
        "New or worsening physical symptoms: chest pain, breathlessness, fever, head injury, seizure, or a fall. Assess these on their own merits rather than attributing them to distress.",
        "Any first presentation of confusion, disorientation, or a change in conscious state. This has not been part of Rowan's usual pattern and needs medical assessment.",
        "A stated plan with means and preparation, or an attempt before arrival. This plan describes usual continuity care and does not apply to that presentation.",
        "Pregnancy, a medicine started or stopped in the last two weeks, or a suspected overdose of any substance.",
        "A safeguarding concern about Rowan, or about a child or dependent adult in their household.",
      ],
      whyThisPlanExists:
        "Rowan has attended North River Hospital ED several times over the last year, usually in the evening and usually after a stretch of poor sleep and a conflict at home. Each attendance has followed a similar course, so Rowan, the North River CMHT and the ED agreed a shared approach that Rowan does not have to renegotiate while distressed. This plan supports continuity. It never replaces fresh triage, physical assessment, mental-state assessment, immediate risk assessment, clinical judgement, or legal obligations.",
      whatThePersonWants: [
        "To be told what is happening and roughly how long it will take, rather than being left to guess.",
        "To go home the same day where that is safe, with a CMHT call the next working day.",
        "To have Jess contacted only with Rowan's agreement on the day, not automatically.",
        "To be addressed as Rowan, and referred to as they/them.",
      ],
      practicalNeeds: [
        "No interpreter needed. When distressed, Rowan takes in written information more easily than spoken instructions, so write the plan down.",
        "Sensory: bright overhead lighting and repeated overhead paging are difficult. A side room with the door ajar works better than a closed door.",
        "Rowan has asked that peer support be offered when someone is available.",
      ],
      physicalHealthAndMedication: [
        "Documented allergy to penicillin. Check the hospital allergy record before prescribing anything.",
        "Long-standing asthma. Take breathlessness seriously and assess it physically rather than reading it as anxiety.",
        "The authoritative medicines record is the hospital medication chart and the community pharmacy record. This plan deliberately holds no doses and no medicines list.",
      ],
      whoElseIsInvolved: [
        "North River CMHT is the durable service contact. Care coordinator Sam Placeholder, involvement current.",
        "General practitioner at a North River practice, involvement current.",
        "Jess Sample, sister. Rowan consents to her being contacted when Rowan agrees on the day.",
      ],
      reviewTriggers: [
        "Two or more presentations where the plan was recorded as not helpful.",
        "Any change of care coordinator, CMHT, or living arrangements.",
        "A mental-health or medical admission.",
        "Rowan asking for the plan to be changed.",
      ],
    },
  },
  {
    id: "SYN-MGMT-VERSION-003",
    planId: "SYN-MGMT-PLAN-002",
    version: 1,
    state: "current",
    reviewState: "overdue",
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: "SYN-USER-SENIOR-001",
    createdAt: atPerthTime(addIsoDays(MIRA_V1_APPROVED_AT, -12), "11:30"),
    submittedAt: atPerthTime(addIsoDays(MIRA_V1_APPROVED_AT, -4), "09:15"),
    approvedAt: MIRA_V1_APPROVED_AT,
    reviewDueAt: reviewDueFrom(MIRA_V1_APPROVED_AT),
    revisionReason: "First agreed version, written after the July 2025 joint review with Mira and her son Daniel.",
    participationState: "discussed",
    consentedSupportPeople: ["Daniel Example — son, contactable at any time with Mira's agreement"],
    returnedReason: null,
    withdrawalReason: null,
    withdrawnBy: null,
    withdrawnAt: null,
    sharedWithPatientAt: null,
    content: {
      howToApproach: [
        "Speak a little more slowly, and check that Mira has her hearing aids in before you start. She will say if she has not.",
        "Sit down to talk. Mira finds standing conversations at the bedside hard to follow.",
        "Offer to ring her son Daniel early. She is much steadier once he knows where she is.",
      ],
      whatHelps: [
        "A chair with arms and a warm blanket. Mira is often cold and sore by the time she is seen.",
        "Written notes of what has been decided, in large print, so she can read them again later.",
        "Contacting the Coastal Plains Older Adult CMHT during their hours; they usually know what has changed recently.",
      ],
      whatMakesItWorse: [
        "Long waits in the corridor without a chair. Mira's back pain builds and she can no longer concentrate on the assessment.",
        "Repeating the whole history to each new clinician. Read this plan and the referral first, then confirm what has changed.",
        "Loud overhead paging and bright lights at night, which make it hard for her to follow what is being asked.",
      ],
      agreedEdApproach: [
        "Agreed with Mira, her son Daniel, and the Coastal Plains Older Adult CMHT on 16 July 2025.",
        "The usual agreed default is medical review first, given her falls and her physical health, then mental-health assessment, then home with a CMHT visit within two working days.",
        "Admission is available whenever the treating team judges it necessary. This plan records the approach that has usually helped and does not limit the care offered on the day.",
      ],
      whatWouldMakeThisDifferent: [
        "A fall with a head strike, new limb weakness, slurred speech, or facial droop. Treat as a medical emergency rather than attributing it to distress.",
        "New confusion or drowsiness that differs from her usual presentation, which may point to delirium, infection, or a medicine effect.",
        "A stated plan to end her life with means or preparation, or an attempt before arrival.",
        "Any concern that Mira is not safe at home, including a safeguarding concern about her or about her care.",
      ],
      whyThisPlanExists:
        "Mira is known to the Coastal Plains Older Adult CMHT and has attended Coastal Plains Hospital ED a few times over the past year, usually after a fall or a night of severe pain and poor sleep. The team agreed a shared approach so that the physical and the mental-health assessment happen in a consistent order. This plan supports continuity. It never replaces fresh triage, physical assessment, mental-state assessment, immediate risk assessment, clinical judgement, or legal obligations.",
      whatThePersonWants: [
        "To be seen sitting down, and to have Daniel told where she is.",
        "To go home the same day where that is safe, with the CMHT visiting rather than telephoning.",
      ],
      practicalNeeds: [],
      physicalHealthAndMedication: [
        "Chronic back pain and a history of falls. Assess pain early; it is often the reason she cannot engage with the mental-health assessment.",
        "The authoritative medicines record is the hospital medication chart and her community pharmacy record. This plan holds no doses and no medicines list.",
      ],
      whoElseIsInvolved: [
        "Coastal Plains Older Adult CMHT is the durable service contact. Care coordinator Devon Sample, involvement current.",
        "Daniel Example, son. Mira consents to him being contacted at any time.",
      ],
      reviewTriggers: [],
    },
  },
  {
    id: "SYN-MGMT-VERSION-004",
    planId: "SYN-MGMT-PLAN-002",
    version: 2,
    state: "awaiting_approval",
    reviewState: null,
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: null,
    createdAt: daysAgo(9, "14:05"),
    submittedAt: daysAgo(6, "16:10"),
    approvedAt: null,
    reviewDueAt: addIsoMonths(PROTOTYPE_NOW, REVIEW_INTERVAL_MONTHS),
    revisionReason:
      "Submitted after the August 2026 presentation: the medical-first order needs stating more plainly, and the CMHT contact details have changed.",
    participationState: "patient_unavailable",
    consentedSupportPeople: ["Daniel Example — son, contactable at any time with Mira's agreement"],
    returnedReason: null,
    withdrawalReason: null,
    withdrawnBy: null,
    withdrawnAt: null,
    sharedWithPatientAt: null,
    content: {
      howToApproach: [
        "Speak a little more slowly, and check that Mira has her hearing aids in before you start.",
        "Sit down to talk, and offer to ring her son Daniel early.",
        "Say plainly that the physical assessment comes first, so the order does not read as her mental health being dismissed.",
      ],
      whatHelps: [
        "A chair with arms and a warm blanket, offered on arrival rather than after she asks.",
        "Written notes in large print of what has been decided.",
        "Analgesia offered early, before the mental-health assessment begins.",
      ],
      whatMakesItWorse: [
        "Long waits in the corridor without a chair, which build her back pain until she cannot concentrate.",
        "Repeating the whole history to each new clinician instead of reading the plan and the referral first.",
        "Deferring pain relief until after the mental-health assessment, which has repeatedly made the assessment unusable.",
      ],
      agreedEdApproach: [
        "Agreed with the Coastal Plains Older Adult CMHT and Dr Taylor Fiction on 14 August 2026. Mira was unwell and unable to take part, so this version is written without her involvement and must be discussed with her at the next contact.",
        "The usual agreed default is medical review and analgesia first, then mental-health assessment, then home with a CMHT visit within two working days.",
        "Admission is available whenever the treating team judges it necessary. This plan records the approach that has usually helped and does not limit the care offered on the day.",
      ],
      whatWouldMakeThisDifferent: [
        "A fall with a head strike, new limb weakness, slurred speech, or facial droop. Treat as a medical emergency rather than attributing it to distress.",
        "New confusion or drowsiness that differs from her usual presentation, which may point to delirium, infection, or a medicine effect.",
        "A stated plan to end her life with means or preparation, or an attempt before arrival.",
        "Any concern that Mira is not safe at home, including a safeguarding concern about her or about her care.",
      ],
      whyThisPlanExists:
        "Mira attends Coastal Plains Hospital ED after falls and nights of severe pain and poor sleep. The order of assessment is the part that has repeatedly gone wrong, so this version states it plainly. This plan supports continuity. It never replaces fresh triage, physical assessment, mental-state assessment, immediate risk assessment, clinical judgement, or legal obligations.",
      whatThePersonWants: [
        "To be seen sitting down, and to have Daniel told where she is.",
        "To have her pain treated before she is asked to talk about how she is coping.",
      ],
      practicalNeeds: ["Large-print written information. Hearing aids in place before the conversation starts."],
      physicalHealthAndMedication: [
        "Chronic back pain and a history of falls. Assess pain early.",
        "The authoritative medicines record is the hospital medication chart and her community pharmacy record.",
      ],
      whoElseIsInvolved: [
        "Coastal Plains Older Adult CMHT is the durable service contact. Care coordinator Devon Sample, involvement current.",
        "Daniel Example, son. Mira consents to him being contacted at any time.",
      ],
      reviewTriggers: [
        "Any presentation where analgesia was not offered before the mental-health assessment.",
        "Any change of care coordinator or living arrangements.",
      ],
    },
  },
  {
    id: "SYN-MGMT-VERSION-005",
    planId: "SYN-MGMT-PLAN-004",
    version: 1,
    state: "withdrawn",
    reviewState: null,
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: "SYN-USER-SENIOR-001",
    createdAt: monthsAgo(17, "10:40"),
    submittedAt: monthsAgo(16, "09:05"),
    approvedAt: EVELYN_V1_APPROVED_AT,
    reviewDueAt: reviewDueFrom(EVELYN_V1_APPROVED_AT),
    revisionReason: "First agreed version, written with Evelyn after the April 2025 review.",
    participationState: "co_produced",
    consentedSupportPeople: [],
    returnedReason: null,
    withdrawalReason:
      "Withdrawn at the July 2026 review. Evelyn's circumstances have changed substantially since this version was agreed, and she asked that it not be used until a new plan is written with her. Superseded content stays readable in history.",
    withdrawnBy: "SYN-USER-SENIOR-001",
    withdrawnAt: daysAgo(47, "16:20"),
    sharedWithPatientAt: monthsAgo(15, "11:00"),
    content: {
      howToApproach: [
        "Ask Evie how she would like to be addressed; she prefers Evie rather than her full name.",
        "Offer a female clinician where one is available, and say when one is not.",
      ],
      whatHelps: [
        "A room with a door that closes, and a clear statement of who else will come in and when.",
        "Being told the plan for the next hour, and being told again when it changes.",
      ],
      whatMakesItWorse: [
        "Being assessed in a curtained bay where the conversation can be overheard by people waiting nearby.",
        "Repeated handovers between staff without the incoming clinician reading the plan first.",
      ],
      agreedEdApproach: [
        "Agreed with Evelyn, the North River CMHT and Dr Taylor Fiction on 20 April 2025.",
        "The usual agreed default was assessment in ED and discharge home the same day where safe, with a CMHT call the next working day.",
        "Admission remained available whenever the treating team judged it necessary; this version never set a ceiling on care.",
      ],
      whatWouldMakeThisDifferent: [
        "Any new physical symptom, head injury, or suspected overdose, which is assessed on its own merits.",
        "A stated plan with means and preparation, or an attempt before arrival, which this plan does not cover.",
        "Any safeguarding concern about Evelyn or about someone in her household.",
      ],
      whyThisPlanExists:
        "Written so that Evelyn did not have to explain the same preferences at every attendance. It supported continuity and never replaced fresh triage, physical assessment, mental-state assessment, immediate risk assessment, clinical judgement, or legal obligations.",
      whatThePersonWants: ["To be called Evie, and to have privacy for the conversation."],
      practicalNeeds: ["A room with a door rather than a curtained bay."],
      physicalHealthAndMedication: [
        "The authoritative medicines record is the hospital medication chart and her community pharmacy record.",
      ],
      whoElseIsInvolved: ["North River CMHT was the durable service contact at the time this version was agreed."],
      reviewTriggers: ["Any change of living arrangements or care coordinator."],
    },
  },
  {
    id: "SYN-MGMT-VERSION-006",
    planId: "SYN-MGMT-PLAN-005",
    version: 1,
    state: "draft",
    reviewState: null,
    authorId: "SYN-USER-LIAISON-001",
    ownerId: "SYN-USER-LIAISON-001",
    approverId: null,
    createdAt: daysAgo(26, "13:15"),
    submittedAt: daysAgo(19, "10:05"),
    approvedAt: null,
    reviewDueAt: addIsoMonths(PROTOTYPE_NOW, REVIEW_INTERVAL_MONTHS),
    revisionReason: "First draft, written after the July 2026 liaison contact.",
    participationState: "declined",
    consentedSupportPeople: [],
    returnedReason:
      "Returned for changes on 5 August 2026: Alex declined to take part in writing this, which must be stated in the plan itself rather than only in the metadata, and the agreed ED approach needs to name who agreed it and when.",
    withdrawalReason: null,
    withdrawnBy: null,
    withdrawnAt: null,
    sharedWithPatientAt: null,
    content: {
      howToApproach: [
        "Alex asked not to take part in writing this plan. Say so plainly when you use it, and offer again to write it together.",
        "Keep the first conversation short and say what will happen next.",
      ],
      whatHelps: ["A seat in a quieter area, and a clear time for the next update."],
      whatMakesItWorse: [
        "Being left in the waiting room with no update; Alex has left before assessment on two occasions after a long silent wait.",
      ],
      agreedEdApproach: [
        "Agreed between the North River CMHT and the ED liaison team on 24 July 2026. Alex declined to take part, so this is a service-side agreement only and must be revisited with them.",
        "The usual agreed default is assessment in ED with an early update on expected waiting time, then a decision made on the day.",
      ],
      whatWouldMakeThisDifferent: [
        "Any new physical symptom, head injury, or suspected overdose, which is assessed on its own merits.",
        "A stated plan with means and preparation, or an attempt before arrival, which this draft does not cover.",
        "Any indication that Alex has nowhere safe to go on discharge, which changes the disposition question entirely.",
      ],
      whyThisPlanExists:
        "A draft written after two presentations that ended before assessment was complete. It is not approved and must not be used as a Current Plan.",
      whatThePersonWants: [],
      practicalNeeds: [],
      physicalHealthAndMedication: [],
      whoElseIsInvolved: ["North River CMHT, first contact made; involvement not yet established."],
      reviewTriggers: [],
    },
  },
] satisfies readonly ManagementPlanVersion[];

export const syntheticPersonalSafetyPlans = [
  {
    id: "SYN-SAFETY-PLAN-001",
    patientId: "SYN-PATIENT-001",
    versionIds: ["SYN-SAFETY-VERSION-001"],
    currentVersionId: "SYN-SAFETY-VERSION-001",
  },
  {
    id: "SYN-SAFETY-PLAN-002",
    patientId: "SYN-PATIENT-002",
    versionIds: ["SYN-SAFETY-VERSION-002"],
    currentVersionId: "SYN-SAFETY-VERSION-002",
  },
  {
    id: "SYN-SAFETY-PLAN-003",
    patientId: "SYN-PATIENT-003",
    versionIds: ["SYN-SAFETY-VERSION-003"],
    currentVersionId: null,
  },
  {
    id: "SYN-SAFETY-PLAN-004",
    patientId: "SYN-PATIENT-004",
    versionIds: ["SYN-SAFETY-VERSION-004"],
    currentVersionId: "SYN-SAFETY-VERSION-004",
  },
  {
    id: "SYN-SAFETY-PLAN-005",
    patientId: "SYN-PATIENT-005",
    versionIds: [],
    currentVersionId: null,
  },
] satisfies readonly PersonalSafetyPlan[];

export const syntheticPersonalSafetyPlanVersions = [
  {
    id: "SYN-SAFETY-VERSION-001",
    planId: "SYN-SAFETY-PLAN-001",
    version: 1,
    state: "current",
    reviewState: "due_soon",
    authorId: "SYN-USER-LIAISON-001",
    createdAt: ROWAN_SAFETY_CREATED_AT,
    confirmedAt: atPerthTime(addIsoDays(ROWAN_SAFETY_CREATED_AT, 1), "09:45"),
    reviewDueAt: reviewDueFrom(ROWAN_SAFETY_CREATED_AT),
    patientConfirmation: "confirmed",
    collaborationNote: "Written with Rowan over two sessions. Rowan chose the wording and asked for a printed copy.",
    content: {
      warningSigns: [
        "Two or three nights of broken sleep in a row.",
        "Not answering messages from Jess for more than a day.",
        "Thoughts that everyone would manage better without me.",
      ],
      saferSurroundings: [
        "Jess keeps the spare medicines at her place.",
        "I put my keys and phone charger by the door so leaving the flat is easy.",
      ],
      reasonsForLiving: ["My nephew.", "The allotment, especially in spring.", "Finishing the course I started."],
      selfStrategies: [
        "Cold water on my wrists and face.",
        "Walking to the end of the street and back, twice.",
        "Putting on the podcast I know well so the room is not silent.",
      ],
      connectionPeopleAndPlaces: ["The late-opening library.", "The allotment.", "Jess's kitchen."],
      personalSupports: [
        { name: "Jess Sample", relationship: "Sister", phone: "0491 570 220" },
        { name: "Ari Placeholder", relationship: "Friend", phone: "0491 570 222" },
      ],
      professionalAndEmergencySupport: [
        "North River CMHT, Monday to Friday 8:30 am to 5:00 pm, 0491 570 210.",
        "Mental Health Emergency Response Line (MHERL), 1300 555 788, 24 hours. Not an emergency service.",
        "In an emergency, call 000.",
      ],
    },
  },
  {
    id: "SYN-SAFETY-VERSION-002",
    planId: "SYN-SAFETY-PLAN-002",
    version: 1,
    state: "current",
    reviewState: "within_review",
    authorId: "SYN-USER-LIAISON-001",
    createdAt: monthsAgo(5, "11:20"),
    confirmedAt: null,
    reviewDueAt: reviewDueFrom(monthsAgo(5, "11:20")),
    patientConfirmation: "discussed_not_confirmed",
    collaborationNote:
      "Discussed with Mira at the ward review. She wanted to think about it and has not yet confirmed the wording; ask her again at the next contact.",
    content: {
      warningSigns: ["Pain keeping me awake for several nights.", "Not wanting to answer the phone to Daniel."],
      saferSurroundings: ["Daniel holds the spare key and checks in on Sundays."],
      reasonsForLiving: ["Daniel and the grandchildren.", "The garden."],
      selfStrategies: ["Sitting in the sun on the back step.", "The radio on in the kitchen."],
      connectionPeopleAndPlaces: ["The Thursday craft group at the community hall."],
      personalSupports: [{ name: "Daniel Example", relationship: "Son", phone: "0491 570 221" }],
      professionalAndEmergencySupport: [
        "Coastal Plains Older Adult CMHT, Monday to Friday 8:30 am to 4:30 pm, 0491 570 211.",
        "Mental Health Emergency Response Line (MHERL) Peel, 1800 676 822, 24 hours. Not an emergency service.",
        "In an emergency, call 000.",
      ],
    },
  },
  {
    id: "SYN-SAFETY-VERSION-003",
    planId: "SYN-SAFETY-PLAN-003",
    version: 1,
    state: "draft",
    reviewState: null,
    authorId: "SYN-USER-ED-001",
    createdAt: daysAgo(5, "23:10"),
    confirmedAt: null,
    reviewDueAt: null,
    patientConfirmation: "unavailable",
    collaborationNote:
      "Started in ED while Jordan was waiting for transport home. He left before it could be finished, so this stays a draft and is not his plan yet.",
    content: {
      warningSigns: ["Long stretches awake at night."],
      saferSurroundings: [],
      reasonsForLiving: [],
      selfStrategies: ["Driving out to the river."],
      connectionPeopleAndPlaces: [],
      personalSupports: [],
      professionalAndEmergencySupport: [
        "Wandoo District CMHT, Monday to Friday 8:00 am to 4:30 pm, 0491 570 212.",
        "Rurallink, 1800 552 002, 4:30 pm to 8:30 am weeknights and 24 hours at weekends. Not an emergency service.",
        "In an emergency, call 000.",
      ],
    },
  },
  {
    id: "SYN-SAFETY-VERSION-004",
    planId: "SYN-SAFETY-PLAN-004",
    version: 1,
    state: "current",
    reviewState: "within_review",
    authorId: "SYN-USER-LIAISON-001",
    createdAt: monthsAgo(2, "15:05"),
    confirmedAt: null,
    reviewDueAt: reviewDueFrom(monthsAgo(2, "15:05")),
    patientConfirmation: "declined",
    collaborationNote:
      "Evie declined to write a safety plan and asked that the crisis numbers alone be kept on file. That is what this version holds, and it is recorded as her decision rather than as a gap.",
    content: {
      warningSigns: [],
      saferSurroundings: [],
      reasonsForLiving: [],
      selfStrategies: [],
      connectionPeopleAndPlaces: [],
      personalSupports: [],
      professionalAndEmergencySupport: [
        "North River CMHT, Monday to Friday 8:30 am to 5:00 pm, 0491 570 210.",
        "Mental Health Emergency Response Line (MHERL), 1300 555 788, 24 hours. Not an emergency service.",
        "In an emergency, call 000.",
      ],
    },
  },
] satisfies readonly PersonalSafetyPlanVersion[];

export const syntheticEdPresentations = [
  {
    id: "SYN-PRESENTATION-001",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(9, "21:40"),
    siteId: "SYN-ED-001",
    presentingIndication: "Escalating distress after a night without sleep",
    assessmentOutcome: "Admitted to the mental health unit for a short period of respite and review",
    note: "Came in by taxi late evening after two sleepless nights; agreed with the team that a short admission would help, and was admitted.",
    disposition: "mental_health_admission",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Out of hours; message left on the shared mailbox for the morning",
    managementPlanVersionId: "SYN-MGMT-VERSION-002",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: true,
    reviewReason:
      "First admission since the plan was agreed. The plan's usual default is same-day discharge, so the team should look at whether it still describes what happens.",
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(9, "23:15"),
  },
  {
    id: "SYN-PRESENTATION-002",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(34, "19:05"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress after a conflict at home",
    assessmentOutcome: "Settled with a quiet room and a call to the CMHT; home the same evening",
    note: "Arrived upset after an argument at home; settled once moved out of the corridor, and went home with the CMHT to call the next morning.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the duty clinician, who arranged a call for the next working day",
    managementPlanVersionId: "SYN-MGMT-VERSION-002",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-LIAISON-001",
    recordedAt: daysAgo(34, "21:30"),
  },
  {
    id: "SYN-PRESENTATION-003",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(62, "17:20"),
    siteId: "SYN-ED-002",
    presentingIndication: "Distress while staying with family away from home",
    assessmentOutcome: "Assessed and discharged home the same evening",
    note: "Presented while staying with family in the Coastal Plains area; the department did not have the quiet space the plan asks for, so the assessment happened in a curtained bay.",
    disposition: "discharged_home",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: "SYN-MGMT-VERSION-002",
    planAvailability: "available",
    planUse: "partially_used",
    planHelpfulness: "mixed",
    deviationOccurred: true,
    deviationReason: "No side room was free, so the low-stimulus space the plan asks for could not be offered.",
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(62, "20:00"),
  },
  {
    id: "SYN-PRESENTATION-004",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(108, "22:15"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress and thoughts of self-harm",
    assessmentOutcome: "Assessed, safety plan reviewed, home the same night",
    note: "Late arrival with thoughts of self-harm; the safety plan was reviewed together and Rowan went home with their sister.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Out of hours; message left on the shared mailbox",
    managementPlanVersionId: "SYN-MGMT-VERSION-001",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(108, "23:50"),
  },
  {
    id: "SYN-PRESENTATION-005",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(167, "18:50"),
    siteId: "SYN-ED-001",
    presentingIndication: "",
    assessmentOutcome: "",
    note: "Brought in by a friend after a difficult day; settled with a quiet room and went home after two hours.",
    disposition: "discharged_home",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: "SYN-MGMT-VERSION-001",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(167, "21:05"),
  },
  {
    id: "SYN-PRESENTATION-006",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(244, "20:10"),
    siteId: "SYN-ED-002",
    presentingIndication: "Distress after a long wait at another service",
    assessmentOutcome: "Assessed and discharged home the same night",
    note: "Waited four hours in a corridor before being seen; by then the conversation was very hard and the plan's approach could not be followed.",
    disposition: "discharged_home",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: "SYN-MGMT-VERSION-001",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "not_helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: true,
    reviewReason:
      "The plan asks for an early quiet space and regular updates about the wait. Neither happened, and the department should look at whether the plan can be followed at that time of night.",
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(244, "23:40"),
  },
  {
    id: "SYN-PRESENTATION-007",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(331, "16:35"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress after stopping sleep medicine",
    assessmentOutcome: "Assessed and discharged home with a CMHT call arranged",
    note: "Came in after a week of poor sleep; assessed, reassured, and went home with a CMHT call arranged for the next day.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the duty clinician",
    managementPlanVersionId: "SYN-MGMT-VERSION-001",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-LIAISON-001",
    recordedAt: daysAgo(331, "19:00"),
  },
  {
    id: "SYN-PRESENTATION-008",
    patientId: "SYN-PATIENT-001",
    arrivedAt: daysAgo(430, "15:20"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress after a bereavement",
    assessmentOutcome: "Assessed and discharged home the same afternoon",
    note: "Presented in the afternoon after a bereavement; assessed and went home the same afternoon with follow-up arranged.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the duty clinician",
    managementPlanVersionId: "SYN-MGMT-VERSION-001",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(430, "18:10"),
  },
  {
    id: "SYN-PRESENTATION-009",
    patientId: "SYN-PATIENT-002",
    arrivedAt: daysAgo(21, "13:25"),
    siteId: "SYN-ED-002",
    presentingIndication: "Fall at home with back pain and low mood",
    assessmentOutcome: "No fracture on imaging; mental-health assessment deferred until analgesia given",
    note: "Fell at home in the morning; the mental-health assessment was attempted before pain relief and had to be repeated later, which Mira found exhausting.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the care coordinator, who arranged a home visit",
    managementPlanVersionId: "SYN-MGMT-VERSION-003",
    planAvailability: "available",
    planUse: "partially_used",
    planHelpfulness: "mixed",
    deviationOccurred: true,
    deviationReason:
      "The plan asks for medical review and pain relief first. The mental-health assessment was started before analgesia because the department was busy.",
    reviewSuggested: true,
    reviewReason:
      "The order of assessment is the part of the plan that keeps going wrong. It needs to be stated more plainly, and the CMHT contact details have changed.",
    recordedBy: "SYN-USER-LIAISON-001",
    recordedAt: daysAgo(21, "17:50"),
  },
  {
    id: "SYN-PRESENTATION-010",
    patientId: "SYN-PATIENT-002",
    arrivedAt: daysAgo(75, "10:15"),
    siteId: "SYN-ED-002",
    presentingIndication: "Severe back pain and several nights without sleep",
    assessmentOutcome: "Analgesia given, assessed, and discharged home with a CMHT visit arranged",
    note: "Came in by ambulance with severe pain after several sleepless nights; pain relief first, then assessment, then home with a CMHT visit arranged.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the care coordinator",
    managementPlanVersionId: "SYN-MGMT-VERSION-003",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(75, "14:20"),
  },
  {
    id: "SYN-PRESENTATION-011",
    patientId: "SYN-PATIENT-002",
    arrivedAt: daysAgo(190, "09:40"),
    siteId: "SYN-ED-002",
    presentingIndication: "Fall at home, no injury found",
    assessmentOutcome: "Observed for four hours and discharged home",
    note: "Fell getting out of bed; observed for four hours, no injury found, and went home with her son.",
    disposition: "short_stay",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Left a message on the shared mailbox",
    managementPlanVersionId: "SYN-MGMT-VERSION-003",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "helpful",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(190, "14:05"),
  },
  {
    id: "SYN-PRESENTATION-012",
    patientId: "SYN-PATIENT-003",
    arrivedAt: daysAgo(5, "22:50"),
    siteId: "SYN-ED-003",
    presentingIndication: "Distress after a long drive, thoughts of self-harm",
    assessmentOutcome: "Assessed and discharged home with a Wandoo District CMHT referral",
    note: "Drove in from out of town late at night with thoughts of self-harm; assessed, referred to the CMHT, and left before transport home was arranged.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Out of hours; referral emailed to the shared mailbox",
    managementPlanVersionId: null,
    planAvailability: "not_applicable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(5, "23:55"),
  },
  {
    id: "SYN-PRESENTATION-013",
    patientId: "SYN-PATIENT-003",
    arrivedAt: daysAgo(48, "20:05"),
    siteId: "SYN-ED-003",
    presentingIndication: "",
    assessmentOutcome: "",
    note: "Arrived in the evening in distress and left after two hours before the assessment was finished.",
    disposition: "left_before_completion",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: null,
    planAvailability: "not_applicable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(48, "22:30"),
  },
  {
    id: "SYN-PRESENTATION-014",
    patientId: "SYN-PATIENT-003",
    arrivedAt: daysAgo(121, "18:30"),
    siteId: "SYN-ED-003",
    presentingIndication: "Alcohol use and low mood",
    assessmentOutcome: "Assessed once sober and discharged home the following morning",
    note: "Brought in by a neighbour in the evening; assessed once sober the next morning and went home with a follow-up letter.",
    disposition: "short_stay",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: null,
    planAvailability: "not_applicable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(120, "09:10"),
  },
  {
    id: "SYN-PRESENTATION-015",
    patientId: "SYN-PATIENT-003",
    arrivedAt: daysAgo(260, "14:45"),
    siteId: "SYN-ED-003",
    presentingIndication: "Chest pain, later found to be non-cardiac",
    assessmentOutcome: "Cardiac cause excluded; distress discussed and follow-up offered",
    note: "Came in with chest pain in the afternoon; cardiac causes excluded, and the distress underneath it was discussed before discharge.",
    disposition: "discharged_home",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: null,
    planAvailability: "not_applicable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(260, "19:20"),
  },
  {
    id: "SYN-PRESENTATION-016",
    patientId: "SYN-PATIENT-004",
    arrivedAt: daysAgo(16, "11:10"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress after a change in housing",
    assessmentOutcome: "Assessed and discharged home with a social work referral",
    note: "Came in mid-morning after being told she has to move; assessed and referred to social work, and went home the same day.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Spoke to the duty clinician",
    managementPlanVersionId: null,
    planAvailability: "unavailable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(16, "14:35"),
  },
  {
    id: "SYN-PRESENTATION-017",
    patientId: "SYN-PATIENT-004",
    arrivedAt: daysAgo(140, "19:55"),
    siteId: "SYN-ED-001",
    presentingIndication: "Distress and difficulty sleeping",
    assessmentOutcome: "Assessed and discharged home with a CMHT call arranged",
    note: "Evening presentation after several difficult weeks; assessed and went home with a CMHT call arranged.",
    disposition: "discharged_home",
    cmhtContactAttempt: "attempted",
    cmhtContactOutcome: "Left a message on the shared mailbox",
    managementPlanVersionId: "SYN-MGMT-VERSION-005",
    planAvailability: "available",
    planUse: "used",
    planHelpfulness: "mixed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-LIAISON-001",
    recordedAt: daysAgo(140, "22:15"),
  },
  {
    id: "SYN-PRESENTATION-018",
    patientId: "SYN-PATIENT-005",
    arrivedAt: daysAgo(3, "20:25"),
    siteId: "SYN-ED-001",
    presentingIndication: "",
    assessmentOutcome: "",
    note: "Arrived in the evening, waited about three hours without an update, and left before the assessment was complete.",
    disposition: "left_before_completion",
    cmhtContactAttempt: "not_attempted",
    cmhtContactOutcome: "",
    managementPlanVersionId: null,
    planAvailability: "not_applicable",
    planUse: "not_applicable",
    planHelpfulness: "not_assessed",
    deviationOccurred: false,
    deviationReason: null,
    reviewSuggested: false,
    reviewReason: null,
    recordedBy: "SYN-USER-ED-001",
    recordedAt: daysAgo(3, "23:40"),
  },
] satisfies readonly EdPresentation[];

export const syntheticPresentationAmendments = [
  {
    id: "SYN-AMENDMENT-001",
    presentationId: "SYN-PRESENTATION-002",
    field: "assessmentOutcome",
    originalValue: "Settled with a quiet room; home the same evening",
    replacementValue: "Settled with a quiet room and a call to the CMHT; home the same evening",
    reason: "The CMHT call was made but not recorded at the time, and it is the part the community team needs to see.",
    authorId: "SYN-USER-LIAISON-001",
    amendedAt: daysAgo(33, "08:45"),
  },
  {
    id: "SYN-AMENDMENT-002",
    presentationId: "SYN-PRESENTATION-003",
    field: "planHelpfulness",
    originalValue: "helpful",
    replacementValue: "mixed",
    reason:
      "Recorded as helpful at the end of the shift. On reflection only part of the plan could be followed, because no side room was free, so the answer is corrected rather than left overstating what happened.",
    authorId: "SYN-USER-ED-001",
    amendedAt: daysAgo(60, "10:30"),
  },
] satisfies readonly PresentationAmendment[];

export const syntheticReviewTriggers = [
  {
    id: "SYN-TRIGGER-001",
    patientId: "SYN-PATIENT-002",
    managementPlanId: "SYN-MGMT-PLAN-002",
    source: "plan_use_feedback",
    sourceId: "SYN-PRESENTATION-009",
    reason:
      "The plan was available and used, and the clinician recorded that it helped only in part: the assessment order the plan asks for was not followed.",
    status: "open",
    createdAt: daysAgo(21, "18:05"),
    resolvedAt: null,
    resolution: null,
  },
  {
    id: "SYN-TRIGGER-002",
    patientId: "SYN-PATIENT-001",
    managementPlanId: "SYN-MGMT-PLAN-001",
    source: "presentation_outcome",
    sourceId: "SYN-PRESENTATION-001",
    reason:
      "First mental-health admission since this version was agreed. The plan's usual default is same-day discharge, so the team should check whether it still describes what happens.",
    status: "open",
    createdAt: daysAgo(9, "23:20"),
    resolvedAt: null,
    resolution: null,
  },
  {
    id: "SYN-TRIGGER-003",
    patientId: "SYN-PATIENT-001",
    managementPlanId: "SYN-MGMT-PLAN-001",
    source: "plan_use_feedback",
    sourceId: "SYN-PRESENTATION-006",
    reason: "The plan was recorded as not helpful after a four-hour corridor wait with no updates.",
    status: "resolved",
    createdAt: daysAgo(244, "23:45"),
    resolvedAt: monthsAgo(3, "09:30"),
    resolution:
      "Discussed at the May 2026 review with Rowan. The version 2 plan now names the early quiet space and the update on waiting time explicitly.",
  },
] satisfies readonly ReviewTrigger[];

export const syntheticIdentificationReviews = [
  {
    id: "SYN-IDENT-REVIEW-001",
    patientId: "SYN-PATIENT-003",
    reason:
      "Jordan has attended Wandoo District Hospital ED several times over the past year, twice leaving before assessment was complete, and has no coordinated plan. Referred so the team can consider together whether one would help him.",
    referredBy: "SYN-USER-ED-001",
    referredAt: daysAgo(12, "10:15"),
    status: "open",
    decision: null,
    decisionReason: null,
    decidedBy: null,
    decidedAt: null,
  },
  {
    id: "SYN-IDENT-REVIEW-002",
    patientId: "SYN-PATIENT-005",
    reason:
      "Two presentations that ended before assessment was complete. Referred to consider whether coordinated planning would help Alex.",
    referredBy: "SYN-USER-LIAISON-001",
    referredAt: daysAgo(60, "09:00"),
    status: "closed",
    decision: "revisit_later",
    decisionReason:
      "The team agreed a plan may help but that Alex should be asked first, and they declined to take part at this stage. Agreed to revisit after the next liaison contact.",
    decidedBy: "SYN-USER-COORD-001",
    decidedAt: daysAgo(50, "14:30"),
  },
  {
    id: "SYN-IDENT-REVIEW-003",
    patientId: "SYN-PATIENT-004",
    reason:
      "Evelyn's plan was withdrawn in July and she has attended once since. Referred so the team can decide whether to write a new plan with her.",
    referredBy: "SYN-USER-LIAISON-001",
    referredAt: daysAgo(40, "11:45"),
    status: "open",
    decision: null,
    decisionReason: null,
    decidedBy: null,
    decidedAt: null,
  },
] satisfies readonly IdentificationReview[];
