"use client";

import Link from "next/link";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { EmptyState, InlineNotice, ignoreUnavailableActivation } from "@/components/ui-primitives";
import { BrowserPrintButton, PrintOutput, PrintSection } from "@/components/ui/print-output";

import styles from "./care-plan.module.css";
import {
  buildPatientSnapshot,
  canPerformAction,
  getCurrentPatientPlanVersion,
  getOpenPatientPlanDraft,
  isPatientPlanVersionStale,
} from "./domain";
import { PROTOTYPE_NOW } from "./fixtures";
import { groupPatientResources } from "./patient-plan-fixtures";
import { PATIENT_PLAN_SECTION_LEAD_IN } from "./patient-plan-transform";
import { useCarePlanPrototype } from "./prototype-provider";
import { getPrototypeMutationBlockReason } from "./prototype-state";
import {
  DefinitionRow,
  NOT_RECORDED,
  PROTOTYPE_OUTCOME_TONE,
  PROTOTYPE_ROLE_LABEL,
  SectionFrame,
  StatusMark,
  SyntheticMarker,
  formatPerthDate,
} from "./prototype-ui";
import { carePlanRoute } from "./routes";
import type {
  Patient,
  PatientPlanVersion,
  PatientResource,
  PrototypeScenario,
  PrototypeUser,
  SyntheticId,
} from "./types";

/**
 * The Patient Plan: the patient-facing edition of an approved Management Plan
 * Version, and the copy the person takes away.
 *
 * The Management Plan is written by clinicians for clinicians. This is the same
 * agreement in the person's own voice — the same eight headings whether it is
 * read here or printed, so the page and the paper cannot say two different
 * things.
 *
 * Two rules shape everything below.
 *
 * A gap is never printed. A gap is a place the offline conversion refused to
 * guess, and approval is blocked while any remains, so an approved copy has
 * nothing missing from it. That is why this surface shows gaps loudly on a draft
 * and the printed copy has no notion of one.
 *
 * A stale copy is never quietly repaired. When the Management Plan moves on, the
 * patient copy is marked as needing updating and stays completely readable. It
 * is not regenerated, hidden, or withdrawn: the person may be holding the paper,
 * and this application's account of what they were given has to match what they
 * actually have.
 *
 * The synthetic marker is rendered *inside* the printed subtree deliberately.
 * The shared print rule makes everything outside `[data-print-output]`
 * invisible, so the shell header's marker cannot reach the paper — and a sheet
 * carrying somebody's care plan and four real crisis telephone numbers with
 * nothing saying the content is fictional is the exact failure this guards
 * against. It has been introduced twice already.
 */

function displayName(users: readonly PrototypeUser[], id: SyntheticId | null): string | undefined {
  if (id === null) return undefined;
  return users.find((user) => user.id === id)?.displayName;
}

/**
 * The eight sections, generated by iterating the version's own list. One
 * rendering serves the screen and the paper.
 *
 * `gaps` is the one thing the two surfaces must not share. On the draft a gap is
 * shown with its reason, because a clinician needs to see what is still owed and
 * why the machine would not attempt it. On paper there are none, because a
 * version carrying one cannot be approved — and were one ever to reach here it
 * is omitted outright rather than printed as a heading with nothing beneath it.
 * "My reasons for living — Not recorded" was printed on a person's own safety
 * plan once; nothing in this file may reproduce it.
 */
function PatientPlanSections({
  sections,
  gaps = "state",
}: {
  sections: readonly PatientPlanVersion["sections"][number][];
  /** `state` — the working copy: a gap is shown with its reason.
   *  `omit` — the person's own copy: a gap is not printed at all. */
  gaps?: "state" | "omit";
}) {
  const shown = sections.filter((section) => gaps === "state" || !section.gap);
  return (
    <div data-testid="care-plan-patient-plan-sections" className={styles.patientPlanSections}>
      {shown.map((section) => (
        <PrintSection key={section.key} className={styles.patientPlanSection}>
          <h3 id={`care-plan-patient-plan-section-${section.key}`} className={styles.patientPlanSectionHeading}>
            {section.heading}
          </h3>
          <p className={styles.patientPlanLeadIn}>{PATIENT_PLAN_SECTION_LEAD_IN[section.key]}</p>
          {section.gap ? (
            <div data-testid={`care-plan-patient-plan-gap-${section.key}`} className={styles.patientPlanGap}>
              <StatusMark tone="warning" label="A clinician needs to write this" />
              <p className={styles.patientPlanGapReason}>{section.gapReason ?? NOT_RECORDED}</p>
            </div>
          ) : (
            <ul className={styles.contentList}>
              {section.body.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ul>
          )}
        </PrintSection>
      ))}
    </div>
  );
}

/**
 * The person's resources, grouped by category.
 *
 * The crisis contacts are the only real details on the page, and they say so:
 * each carries its stated limitation, its hours, and the public page it was
 * checked against, because a reader who dials a number on this sheet must reach
 * a service rather than a fictional one.
 */
function PatientPlanResources({ resources }: { resources: readonly PatientResource[] }) {
  const groups = groupPatientResources(resources);
  if (groups.length === 0) return null;
  return (
    <div data-testid="care-plan-patient-plan-resources" className={styles.patientPlanResources}>
      {groups.map((group) => (
        <PrintSection key={group.category} className={styles.patientPlanResourceGroup}>
          <h3 className={styles.patientPlanSectionHeading}>{group.label}</h3>
          {group.resources.map((resource) => (
            <div key={resource.id} className={resource.isRealContact ? styles.crisisEntry : styles.patientPlanResource}>
              <p className={resource.isRealContact ? styles.crisisName : styles.patientPlanResourceName}>
                {resource.contact === null || resource.isRealContact
                  ? resource.name
                  : `${resource.name} — ${resource.contact}`}
              </p>
              <p className={resource.isRealContact ? styles.crisisDetail : styles.patientPlanResourceDetail}>
                {resource.detail}
              </p>
              {resource.sourceUrl === null ? null : (
                <p className={resource.isRealContact ? styles.crisisSource : styles.patientPlanResourceDetail}>
                  <a href={resource.sourceUrl} className={styles.inlineLink}>
                    {resource.sourceUrl}
                  </a>
                </p>
              )}
            </div>
          ))}
        </PrintSection>
      ))}
    </div>
  );
}

/**
 * The notice a Current patient copy carries once the Management Plan it was
 * written from has been replaced. Derived every render from the two identifiers,
 * never stored.
 */
function StaleNotice({ version, patient }: { version: PatientPlanVersion; patient: Patient }) {
  return (
    <p role="status" data-testid="care-plan-patient-plan-stale" className={styles.patientPlanStale}>
      <strong>This copy needs updating.</strong>{" "}
      {`The Management Plan has moved on since version ${version.version} of ${patient.preferredName}'s own copy was written. Everything in it is still shown, and nothing has been changed or taken away: ${patient.preferredName} may be holding a printed copy, and what this page says they were given has to stay true. Go through it with them and write a new one.`}
    </p>
  );
}

function PatientPlanIdentityBand({ patient }: { patient: Patient }) {
  return (
    <div data-testid="care-plan-patient-plan-identity" className={styles.identityBand}>
      <SyntheticMarker />
      <h2 className={styles.patientName}>{patient.fullName}</h2>
      <p className={styles.sectionDescription}>{`${patient.mrn} — born ${formatPerthDate(patient.dateOfBirth)}`}</p>
    </div>
  );
}

export function PatientPlanSurface({ patientId, scenario }: { patientId: string | null; scenario: PrototypeScenario }) {
  const { state, dispatch } = useCarePlanPrototype();
  const snapshot = patientId === null ? null : buildPatientSnapshot(state, patientId as SyntheticId, PROTOTYPE_NOW);

  if (snapshot === null) {
    return (
      <EmptyState
        testId="care-plan-patient-plan-no-patient"
        title="No patient is open."
        body="Open a synthetic patient from Home or Patients, then choose Patient Plan."
      />
    );
  }

  const { patient, managementPlan, currentManagementVersion } = snapshot;

  if (scenario === "identity-uncertain") {
    return (
      <section aria-label={`${patient.fullName} Patient Plan`} className={styles.workspace}>
        <p role="alert" data-testid="care-plan-identity-uncertain" className={styles.identityUncertain}>
          <strong>This record has not been confirmed as the right person.</strong> Nothing of this plan is shown,
          because this is the copy written to be handed to somebody. Return to search and choose the record again.
        </p>
      </section>
    );
  }

  const plan = state.patientPlans.find((candidate) => candidate.patientId === patient.id) ?? null;
  const current = plan === null ? null : getCurrentPatientPlanVersion(state.patientPlanVersions, plan.id);
  const draft = plan === null ? null : getOpenPatientPlanDraft(state.patientPlanVersions, plan.id);
  const stale = isPatientPlanVersionStale(current, managementPlan?.currentVersionId ?? null);

  const actor = state.users.find((user) => user.id === state.activeUserId) ?? null;
  const mayAuthor = actor !== null && canPerformAction(actor.role, "approve_patient_plan");
  const createBlockedReason = getPrototypeMutationBlockReason(state, {
    type: "create-patient-plan-draft",
    patientId: patient.id,
  });

  const ownership = (
    <SectionFrame
      id="care-plan-patient-plan-ownership"
      heading="Whose copy this is"
      testId="care-plan-patient-plan-ownership"
      tone="boundary"
    >
      <p className={styles.boundaryStatement}>
        {`This is ${patient.preferredName}'s own copy of the plan, written to be read by ${patient.preferredName} rather than by a clinician. It carries the same agreement as the Management Plan, in ${patient.preferredName}'s own voice.`}
      </p>
      <p className={styles.boundaryStatement}>
        It is produced by a fixed offline conversion that runs on this device. No language model, and no service of any
        kind, is involved at any point. Anything the conversion could not turn into everyday words with confidence is
        left blank for a clinician to write, and a copy with a blank in it cannot be approved.
      </p>
    </SectionFrame>
  );

  const authoringLink = mayAuthor ? (
    <p className={styles.planFooterLink}>
      <Link href={carePlanRoute.patientPlanEdit(patient.id)} className={styles.inlineLink}>
        {draft === null ? "Write a new copy with this person" : `Continue draft version ${draft.version}`}
      </Link>
    </p>
  ) : (
    <p data-testid="care-plan-patient-plan-authoring-unavailable" className={styles.sectionDescription}>
      {actor === null
        ? "No synthetic user is selected, so nothing written here could be attributed to anyone."
        : `${actor.displayName} is signed in with the ${PROTOTYPE_ROLE_LABEL[actor.role].toLowerCase()} role, which does not carry writing or approving a patient copy. Any clinical role can.`}
    </p>
  );

  const createControl =
    currentManagementVersion === null ? (
      <p data-testid="care-plan-patient-plan-no-source" className={styles.noCurrentPlan}>
        {`${patient.preferredName} has no Current Plan, so there is nothing to make a patient copy of. A draft or a withdrawn version is not an agreed plan, and a copy of one would describe care nobody agreed to.`}
      </p>
    ) : createBlockedReason !== null ? (
      <>
        <Button
          variant="primary"
          aria-disabled="true"
          aria-describedby="care-plan-patient-plan-create-blocked"
          onClick={ignoreUnavailableActivation}
        >
          Create the patient copy
        </Button>
        <p
          id="care-plan-patient-plan-create-blocked"
          role="alert"
          data-testid="care-plan-patient-plan-create-blocked"
          className={styles.contactWarning}
        >
          {createBlockedReason}
        </p>
      </>
    ) : (
      <Button variant="primary" onClick={() => dispatch({ type: "create-patient-plan-draft", patientId: patient.id })}>
        Create the patient copy
      </Button>
    );

  return (
    <section
      aria-label={`${patient.fullName} Patient Plan`}
      data-testid="care-plan-patient-plan-surface"
      className={styles.workspace}
    >
      <PatientPlanIdentityBand patient={patient} />
      {ownership}

      {state.lastOutcome === null ? null : (
        <InlineNotice tone={PROTOTYPE_OUTCOME_TONE[state.lastOutcome.kind]}>{state.lastOutcome.message}</InlineNotice>
      )}

      {stale && current !== null ? <StaleNotice version={current} patient={patient} /> : null}

      {current === null ? (
        <SectionFrame id="care-plan-patient-plan-none" heading="No approved copy">
          <p data-testid="care-plan-patient-plan-no-current" className={styles.noCurrentPlan}>
            {`${patient.preferredName} has no approved Patient Plan. Nothing is shown in its place, because a draft is not a copy anybody has agreed to hand over.`}
          </p>
          {draft === null ? null : (
            <div data-testid="care-plan-patient-plan-draft-notice" className={styles.patientPlanDraftNotice}>
              <StatusMark tone="neutral" label={`Draft version ${draft.version}`} />
              <p className={styles.sectionDescription}>
                {`A draft was started on ${formatPerthDate(draft.createdAt)}. It has ${
                  draft.sections.filter((section) => section.gap).length
                } of ${draft.sections.length} sections still to write, and cannot be approved until they are.`}
              </p>
            </div>
          )}
          <div className={styles.sectionActions}>{createControl}</div>
          {authoringLink}
        </SectionFrame>
      ) : (
        <>
          <SectionFrame id="care-plan-patient-plan-version" heading="This copy" testId="care-plan-patient-plan-version">
            <div className={styles.metadataMarks}>
              <StatusMark tone="success" label={`Version ${current.version}`} />
              {stale ? <StatusMark tone="warning" label="Needs updating" /> : null}
            </div>
            <dl className={styles.definitionGrid}>
              <DefinitionRow term="Approved by">{displayName(state.users, current.approvedBy)}</DefinitionRow>
              <DefinitionRow term="Approved on">{formatPerthDate(current.approvedAt)}</DefinitionRow>
              <DefinitionRow term="Written from Management Plan version">
                {String(
                  state.managementPlanVersions.find((version) => version.id === current.derivedFromManagementVersionId)
                    ?.version ?? NOT_RECORDED,
                )}
              </DefinitionRow>
            </dl>
          </SectionFrame>

          <SectionFrame id="care-plan-patient-plan-content" heading={`${patient.preferredName}'s copy`}>
            <PatientPlanSections sections={current.sections} />
          </SectionFrame>

          <SectionFrame id="care-plan-patient-plan-resource-list" heading="Resources on this copy">
            <PatientPlanResources resources={current.resources} />
          </SectionFrame>

          <SectionFrame id="care-plan-patient-plan-actions" heading="This copy on paper" tone="secondary">
            <p className={styles.sectionDescription}>
              {`The printed copy is written to ${patient.preferredName}, carries only ${patient.preferredName}'s preferred name and record number, and holds nothing from the clinical record beyond what is on this page.`}
            </p>
            <p className={styles.planFooterLink}>
              <Link href={carePlanRoute.patientPlanPrint(patient.id)} className={styles.inlineLink}>
                Print this copy
              </Link>
            </p>
            {authoringLink}
          </SectionFrame>
        </>
      )}
    </section>
  );
}

/**
 * The printed-at stamp, formatted from `PROTOTYPE_NOW` alone. Deterministic by
 * construction: the prototype reads no clock, so two runs of the same route
 * produce the same sheet of paper.
 */
function perthStamp(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(iso);
  if (match === null) return NOT_RECORDED;
  const hour24 = Number(match[4]);
  const meridiem = hour24 < 12 ? "am" : "pm";
  const hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  return `${match[3]}/${match[2]}/${match[1]} at ${hour12}:${match[5]} ${meridiem} AWST`;
}

const PRINTED_AT = `This copy was printed on ${perthStamp(PROTOTYPE_NOW)}.`;

export function PatientPlanPrintSurface({
  patientId,
  scenario,
}: {
  patientId: string | null;
  scenario: PrototypeScenario;
}) {
  const { state, dispatch } = useCarePlanPrototype();
  const [printFailed, setPrintFailed] = useState(false);
  const snapshot = patientId === null ? null : buildPatientSnapshot(state, patientId as SyntheticId, PROTOTYPE_NOW);

  if (snapshot === null) {
    return (
      <EmptyState
        testId="care-plan-patient-plan-no-patient"
        title="No patient is open."
        body="Open a synthetic patient from Home or Patients, then choose Patient Plan."
      />
    );
  }

  const { patient, managementPlan } = snapshot;

  // Printing is exempt from the offline block and from nothing else. Paper
  // carrying a nearby person's plan cannot be taken back once it has left the
  // room, so identity uncertainty stops it outright and nothing is offered.
  if (scenario === "identity-uncertain") {
    return (
      <section aria-label={`${patient.fullName} Patient Plan, printed copy`} className={styles.workspace}>
        <p role="alert" data-testid="care-plan-identity-uncertain" className={styles.identityUncertain}>
          <strong>This record has not been confirmed as the right person.</strong> Nothing is offered for printing,
          because paper carrying a nearby person&rsquo;s plan cannot be taken back. Return to search and choose the
          record again.
        </p>
      </section>
    );
  }

  const plan = state.patientPlans.find((candidate) => candidate.patientId === patient.id) ?? null;
  const version = plan === null ? null : getCurrentPatientPlanVersion(state.patientPlanVersions, plan.id);

  if (version === null) {
    return (
      <section
        aria-label={`${patient.fullName} Patient Plan, printed copy`}
        data-testid="care-plan-patient-plan-print-surface"
        className={styles.workspace}
      >
        <p data-testid="care-plan-patient-plan-print-unavailable" className={styles.noCurrentPlan}>
          {`${patient.preferredName} has no approved Patient Plan, so there is nothing to print. A draft is not a copy anybody has agreed to hand over, and a draft on paper is a plan somebody may follow.`}
        </p>
        <p className={styles.planFooterLink}>
          <Link href={carePlanRoute.patientPlan(patient.id)} className={styles.inlineLink}>
            Back to the Patient Plan
          </Link>
        </p>
      </section>
    );
  }

  const blockedReason = getPrototypeMutationBlockReason(state, {
    type: "record-patient-plan-print-intent",
    patientId: patient.id,
  });
  const stale = isPatientPlanVersionStale(version, managementPlan?.currentVersionId ?? null);

  return (
    <section
      aria-label={`${patient.fullName} Patient Plan, printed copy`}
      data-testid="care-plan-patient-plan-print-surface"
      className={styles.workspace}
    >
      <div className={styles.printControls} data-print-hide="true">
        {blockedReason !== null ? (
          <Button
            variant="primary"
            aria-disabled="true"
            aria-describedby="care-plan-patient-plan-print-blocked"
            onClick={ignoreUnavailableActivation}
          >
            Print Patient Plan
          </Button>
        ) : scenario === "print-failure" ? (
          // The print-failure specimen. The browser is never asked to print, and
          // no intent is recorded either: an audit line saying the print view
          // was opened would be untrue.
          <Button variant="primary" onClick={() => setPrintFailed(true)}>
            Print Patient Plan
          </Button>
        ) : (
          <BrowserPrintButton
            label="Print Patient Plan"
            // Recorded before the browser is asked to print: a print dialogue
            // can block until the reader dismisses it, and may never return.
            onBeforePrint={() => dispatch({ type: "record-patient-plan-print-intent", patientId: patient.id })}
          />
        )}
        <Link href={carePlanRoute.patientPlan(patient.id)} className={styles.inlineLink}>
          Back to the Patient Plan
        </Link>
      </div>

      {blockedReason === null ? null : (
        <p
          id="care-plan-patient-plan-print-blocked"
          role="alert"
          data-testid="care-plan-patient-plan-print-blocked"
          className={styles.contactWarning}
        >
          {blockedReason}
        </p>
      )}

      {stale ? (
        <div data-print-hide="true">
          <StaleNotice version={version} patient={patient} />
        </div>
      ) : null}

      {printFailed ? (
        <p role="alert" data-testid="care-plan-patient-plan-print-failure" className={styles.launchFailure}>
          <strong>The print view could not be opened.</strong> Nothing was printed, and nothing was recorded. The whole
          copy is still on this page: read it from the screen, write the numbers down, or try printing again from the
          browser&rsquo;s own menu.
        </p>
      ) : null}

      {state.lastOutcome === null ? null : (
        <div data-testid="care-plan-patient-plan-print-outcome" data-print-hide="true">
          <InlineNotice tone={PROTOTYPE_OUTCOME_TONE[state.lastOutcome.kind]}>{state.lastOutcome.message}</InlineNotice>
        </div>
      )}

      <PrintOutput
        testId="care-plan-patient-plan-print-output"
        className={styles.patientPlanPaper}
        monochrome
        confidential
        printedAt={PRINTED_AT}
        provenance="Synthetic Care Plan prototype. Nothing on this page describes a real person, team, or hospital, and nothing here was saved. The public telephone numbers are the only real details on it."
      >
        <PrintSection className={styles.patientPlanPaperHead}>
          <SyntheticMarker />
          <h2 className={styles.patientPlanPaperTitle}>My plan</h2>
          {/*
            Minimum necessary, and nothing beyond it. A preferred name and a
            record number are what a person needs to know the sheet is theirs and
            what a service needs to match it to them. A date of birth, an
            address, a pronoun, a home service, an episode, the Management Plan's
            version history, its owner, its approver, its review date, or
            anything about what a clinician thinks is not on this page: none of
            it helps the reader and all of it travels.
          */}
          <dl className={styles.definitionGrid}>
            <DefinitionRow term="Name">{patient.preferredName}</DefinitionRow>
            <DefinitionRow term="Record number">{patient.mrn}</DefinitionRow>
            <DefinitionRow term="Version">{String(version.version)}</DefinitionRow>
            <DefinitionRow term="Agreed on">{formatPerthDate(version.approvedAt)}</DefinitionRow>
          </dl>
          <p data-testid="care-plan-patient-plan-paper-intro" className={styles.patientPlanPaperIntro}>
            This is your copy of the plan you and your team wrote together. Keep it somewhere you can find it quickly,
            and bring it with you if you can. If something in it stops fitting, tell someone on your team so you can
            write it again together.
          </p>
        </PrintSection>

        <PatientPlanSections sections={version.sections} gaps="omit" />

        <PatientPlanResources resources={version.resources} />
      </PrintOutput>
    </section>
  );
}
