"use client";

import Link from "next/link";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { EmptyState, InlineNotice, ignoreUnavailableActivation } from "@/components/ui-primitives";
import { BrowserPrintButton, PrintOutput, PrintSection } from "@/components/ui/print-output";

import styles from "./care-plan.module.css";
import {
  buildPatientSnapshot,
  canPerformAction,
  deriveReviewState,
  getCurrentSafetyPlanVersion,
  getOpenSafetyPlanDraft,
} from "./domain";
import { PROTOTYPE_NOW, publicCrisisContacts } from "./fixtures";
import { PatientNavigation } from "./patient-navigation";
import { useCarePlanPrototype } from "./prototype-provider";
import { getPrototypeMutationBlockReason } from "./prototype-state";
import {
  DefinitionRow,
  NOT_RECORDED,
  PATIENT_CONFIRMATION_EXPLANATION,
  PATIENT_CONFIRMATION_LABEL,
  PROTOTYPE_OUTCOME_TONE,
  PROTOTYPE_ROLE_LABEL,
  REVIEW_STATE_LABEL,
  REVIEW_STATE_UNKNOWN_LABEL,
  ReviewWarning,
  SAFETY_PLAN_SECTION_KEYS,
  SAFETY_PLAN_SECTION_LABEL,
  SAFETY_PLAN_SUPPORTS_KEY,
  SectionFrame,
  StatusMark,
  SyntheticMarker,
  formatPerthDate,
  safetyPlanConfirmationRow,
} from "./prototype-ui";
import { carePlanRoute } from "./routes";
import type {
  CmhtContact,
  Patient,
  PersonalSafetyPlanVersion,
  PrototypeScenario,
  PrototypeUser,
  SafetyPlanContent,
  SyntheticId,
} from "./types";

/**
 * The Personal Safety Plan: the patient's own document, and the printed copy
 * they take away with them.
 *
 * This is not a Management Plan and it is not a clinical record about a person —
 * it is a record *by* a person, in their own words, about what keeps them safe.
 * Everything here follows from that. The seven headings are written the way the
 * person would say them, the printed sheet is addressed to them rather than to a
 * clinician, and there is no senior-approval step anywhere: waiting on a
 * consultant's signature for somebody's own coping strategies would be a
 * category error, and the emergency department at 2am — where a safety plan is
 * most often actually made — has no consultant to wait for.
 *
 * The four patient-confirmation states are described and never scored. A person
 * who declines to write one has made a decision about their own document; a
 * person nobody has been able to ask has an empty record, not a failing one.
 *
 * The synthetic marker is rendered *inside* the printed subtree deliberately.
 * The shared print rule makes everything outside `[data-print-output]`
 * invisible, so the shell header's marker cannot reach the paper — and a sheet
 * carrying a person's own words and four real crisis telephone numbers with
 * nothing saying the content is fictional is the exact failure this guards
 * against. It has been introduced twice already.
 */

function displayName(users: readonly PrototypeUser[], id: SyntheticId | null): string | undefined {
  if (id === null) return undefined;
  return users.find((user) => user.id === id)?.displayName;
}

function SafetyList({ items }: { items: readonly string[] }) {
  if (items.length === 0) return <p className={styles.sectionEmpty}>{NOT_RECORDED}</p>;
  return (
    <ul className={styles.contentList}>
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

function SupportList({ supports }: { supports: SafetyPlanContent["personalSupports"] }) {
  if (supports.length === 0) return <p className={styles.sectionEmpty}>{NOT_RECORDED}</p>;
  return (
    <ul className={styles.safetySupportList}>
      {supports.map((support) => (
        <li key={`${support.name}-${support.phone}`} className={styles.safetySupportRow}>
          <span className={styles.safetySupportName}>{support.name}</span>
          <span className={styles.safetySupportDetail}>{support.relationship}</span>
          <span className={styles.safetySupportDetail}>{support.phone}</span>
        </li>
      ))}
    </ul>
  );
}

/** Whether a section holds anything at all, whichever of the two shapes it has. */
function sectionHasContent(content: SafetyPlanContent, key: keyof SafetyPlanContent): boolean {
  return key === SAFETY_PLAN_SUPPORTS_KEY ? content.personalSupports.length > 0 : content[key].length > 0;
}

/** The six sections that are the person's own words. The seventh is the list of
 *  services, which is nobody's own words and is required in every state. */
const OWN_WORDS_SECTION_KEYS = SAFETY_PLAN_SECTION_KEYS.filter((key) => key !== "professionalAndEmergencySupport");

export function hasOwnWords(content: SafetyPlanContent): boolean {
  return OWN_WORDS_SECTION_KEYS.some((key) => sectionHasContent(content, key));
}

/**
 * The seven sections, generated by iterating `SAFETY_PLAN_SECTION_KEYS` rather
 * than by writing the list out. One rendering serves both the screen and the
 * paper, so the person's own document cannot say two different things in two
 * places, and an eighth section cannot appear by hand.
 *
 * Each section is a `PrintSection`, so the browser is asked not to split it
 * across a page break: half of somebody's reasons for living on the previous
 * sheet is not an acceptable printed document.
 *
 * `emptySections` is the one thing the two surfaces must not share.
 *
 * On the clinical reading surface an empty section says `Not recorded`, because
 * a clinician needs to tell an empty section from a section nobody asked about.
 * On the person's own printed copy that same treatment produces a sheet handed
 * to them reading "My reasons for living — Not recorded", under a sentence
 * claiming these are their own words. That is the worst line this prototype
 * could emit, it is addressed to the person it is about, and it is reached by
 * the ordinary path: the fixture for a person who declined
 * (`SYN-SAFETY-VERSION-004`) is Current with all six arrays empty, and the
 * authoring form's own defaults allow a version with no own words to be made
 * current. So the printed copy omits an empty section outright — heading and
 * all — and the surface says instead, in the second person, what the sheet does
 * hold.
 */
function SafetyPlanSections({
  content,
  emptySections = "state",
}: {
  content: SafetyPlanContent;
  /** `state` — the clinical surface: an empty section reads `Not recorded`.
   *  `omit` — the patient's own copy: an empty section is not printed at all. */
  emptySections?: "state" | "omit";
}) {
  const keys = SAFETY_PLAN_SECTION_KEYS.filter((key) => emptySections === "state" || sectionHasContent(content, key));
  return (
    <div data-testid="care-plan-safety-sections" className={styles.safetySections}>
      {keys.map((key) => (
        <PrintSection key={key} className={styles.safetySection}>
          <h3 id={`care-plan-safety-section-${key}`} className={styles.safetySectionHeading}>
            {SAFETY_PLAN_SECTION_LABEL[key]}
          </h3>
          {key === SAFETY_PLAN_SUPPORTS_KEY ? (
            <SupportList supports={content.personalSupports} />
          ) : (
            <SafetyList items={content[key]} />
          )}
        </PrintSection>
      ))}
    </div>
  );
}

/** The confirmation mark and the sentence that goes with it. Never a verdict on
 *  the person, on any of the four answers. */
function ConfirmationState({ version }: { version: PersonalSafetyPlanVersion }) {
  return (
    <div data-testid="care-plan-safety-confirmation" className={styles.safetyConfirmation}>
      <StatusMark tone="info" label={PATIENT_CONFIRMATION_LABEL[version.patientConfirmation]} />
      <p className={styles.sectionDescription}>{PATIENT_CONFIRMATION_EXPLANATION[version.patientConfirmation]}</p>
    </div>
  );
}

/**
 * Used by the reading surface only. The printed copy builds its own head, so
 * the section navigation below never reaches paper — it is `data-print-hide`
 * either way, but a document handed to a person should not depend on that.
 */
function SafetyIdentityBand({ patient }: { patient: Patient }) {
  return (
    <div data-testid="care-plan-safety-identity" className={styles.identityBand}>
      <SyntheticMarker />
      <h2 className={styles.patientName}>{patient.fullName}</h2>
      <p className={styles.sectionDescription}>{`${patient.mrn} — born ${formatPerthDate(patient.dateOfBirth)}`}</p>
      <PatientNavigation patientId={patient.id} activeSection="safetyPlan" />
    </div>
  );
}

export function SafetyPlanSurface({ patientId, scenario }: { patientId: string | null; scenario: PrototypeScenario }) {
  const { state } = useCarePlanPrototype();
  const snapshot = patientId === null ? null : buildPatientSnapshot(state, patientId as SyntheticId, PROTOTYPE_NOW);

  if (snapshot === null) {
    return (
      <EmptyState
        testId="care-plan-safety-no-patient"
        title="No patient is open."
        body="Open a synthetic patient from Home or Patients, then choose Personal Safety Plan."
      />
    );
  }

  const { patient, currentSafetyPlanVersion } = snapshot;

  if (scenario === "identity-uncertain") {
    return (
      <section aria-label={`${patient.fullName} Personal Safety Plan`} className={styles.workspace}>
        <p role="alert" data-testid="care-plan-identity-uncertain" className={styles.identityUncertain}>
          <strong>This record has not been confirmed as the right person.</strong> Nothing of this plan is shown,
          because a safety plan is one person&rsquo;s own words about their own life. Return to search and choose the
          record again.
        </p>
      </section>
    );
  }

  const draft = getOpenSafetyPlanDraft(state.personalSafetyPlanVersions, patient.personalSafetyPlanId);
  const actor = state.users.find((user) => user.id === state.activeUserId) ?? null;
  const mayAuthor = actor !== null && canPerformAction(actor.role, "author_safety_plan");
  const reviewState =
    currentSafetyPlanVersion?.reviewDueAt == null
      ? null
      : deriveReviewState(currentSafetyPlanVersion.reviewDueAt, PROTOTYPE_NOW);

  const ownership = (
    <SectionFrame
      id="care-plan-safety-ownership"
      heading="Whose plan this is"
      testId="care-plan-safety-ownership"
      tone="boundary"
    >
      <p className={styles.boundaryStatement}>
        {`This is ${patient.preferredName}'s own Personal Safety Plan, written in ${patient.preferredName}'s own words. It sets out what ${patient.preferredName} has said helps when things get hard, and who ${patient.preferredName} would contact.`}
      </p>
      <p className={styles.boundaryStatement}>
        It is not a Management Plan, it is not a risk assessment, and it never replaces fresh assessment of the person
        in front of you.
      </p>
    </SectionFrame>
  );

  const authoring = mayAuthor ? (
    <p className={styles.planFooterLink}>
      <Link href={carePlanRoute.safetyPlanEdit(patient.id)} className={styles.inlineLink}>
        Start a new version with this person
      </Link>
      {" — writing one needs no sign-off from anybody else."}
    </p>
  ) : (
    <p data-testid="care-plan-safety-authoring-unavailable" className={styles.sectionDescription}>
      {actor === null
        ? "No synthetic user is selected, so nothing written here could be attributed to anyone."
        : `${actor.displayName} is signed in with the ${PROTOTYPE_ROLE_LABEL[actor.role].toLowerCase()} role, which does not carry writing a Personal Safety Plan. Any clinical role can write one with this person.`}
    </p>
  );

  if (currentSafetyPlanVersion === null) {
    return (
      <section
        aria-label={`${patient.fullName} Personal Safety Plan`}
        data-testid="care-plan-safety-surface"
        className={styles.workspace}
      >
        <SafetyIdentityBand patient={patient} />
        {ownership}
        <SectionFrame id="care-plan-safety-none" heading="No current version">
          <p data-testid="care-plan-safety-no-current" className={styles.noCurrentPlan}>
            {`${patient.preferredName} has no current Personal Safety Plan. Nothing is shown in its place, because there is nothing this person has agreed to.`}
          </p>
          {draft === null ? null : (
            <div data-testid="care-plan-safety-draft-notice" className={styles.safetyDraftNotice}>
              <StatusMark tone="neutral" label={`Draft version ${draft.version}`} />
              <p className={styles.sectionDescription}>
                {`A draft was started on ${formatPerthDate(draft.createdAt)} by ${
                  displayName(state.users, draft.authorId) ?? "an unrecorded clinician"
                }. It is not ${patient.preferredName}'s plan yet, so its content is not shown here as though it were.`}
              </p>
              <p className={styles.sectionDescription}>{draft.collaborationNote}</p>
              <StatusMark tone="info" label={PATIENT_CONFIRMATION_LABEL[draft.patientConfirmation]} />
            </div>
          )}
          {authoring}
        </SectionFrame>
      </section>
    );
  }

  const confirmationRow = safetyPlanConfirmationRow(currentSafetyPlanVersion, {
    withDate: "Confirmed with this person on",
    withoutDate: "Confirmed with this person",
  });

  return (
    <section
      aria-label={`${patient.fullName} Personal Safety Plan`}
      data-testid="care-plan-safety-surface"
      className={styles.workspace}
    >
      <SafetyIdentityBand patient={patient} />
      {ownership}

      <ReviewWarning reviewState={reviewState} reviewDueAt={currentSafetyPlanVersion.reviewDueAt} />

      <SectionFrame id="care-plan-safety-version" heading="This version" testId="care-plan-safety-version">
        <div className={styles.metadataMarks}>
          <StatusMark tone="success" label={`Version ${currentSafetyPlanVersion.version}`} />
          <StatusMark
            tone="neutral"
            label={reviewState === null ? REVIEW_STATE_UNKNOWN_LABEL : REVIEW_STATE_LABEL[reviewState]}
          />
        </div>
        <dl className={styles.definitionGrid}>
          {/*
            Present only when this person confirmed and the record holds when.
            `ConfirmationState` below states the participation state in words in
            every case, so a missing row here is never the only account of it.
          */}
          {confirmationRow === null ? null : (
            <DefinitionRow term={confirmationRow.term}>{confirmationRow.detail}</DefinitionRow>
          )}
          <DefinitionRow term="Next review due">{formatPerthDate(currentSafetyPlanVersion.reviewDueAt)}</DefinitionRow>
          <DefinitionRow term="Written with this person by">
            {displayName(state.users, currentSafetyPlanVersion.authorId)}
          </DefinitionRow>
          <DefinitionRow term="How this version was written">
            {currentSafetyPlanVersion.collaborationNote === "" ? undefined : currentSafetyPlanVersion.collaborationNote}
          </DefinitionRow>
        </dl>
        <ConfirmationState version={currentSafetyPlanVersion} />
      </SectionFrame>

      <SectionFrame id="care-plan-safety-plan" heading={`${patient.preferredName}'s own words`}>
        <SafetyPlanSections content={currentSafetyPlanVersion.content} />
      </SectionFrame>

      <SectionFrame id="care-plan-safety-actions" heading="This plan on paper" tone="secondary">
        <p className={styles.sectionDescription}>
          {`The printed copy is written to ${patient.preferredName}, carries only ${patient.preferredName}'s preferred name and record number, and lists the crisis numbers to ring.`}
        </p>
        <p className={styles.planFooterLink}>
          <Link href={carePlanRoute.safetyPlanPrint(patient.id)} className={styles.inlineLink}>
            Print this plan
          </Link>
        </p>
        {authoring}
      </SectionFrame>
    </section>
  );
}

/**
 * The printed-at stamp, formatted from `PROTOTYPE_NOW` alone. Deterministic by
 * construction: the prototype reads no clock, so two runs of the same route
 * produce the same sheet of paper.
 */
function perthStamp(iso: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(iso);
  if (match === null) return NOT_RECORDED;
  const hour24 = Number(match[4]);
  const meridiem = hour24 < 12 ? "am" : "pm";
  const hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  return `${match[3]}/${match[2]}/${match[1]} at ${hour12}:${match[5]} ${meridiem} AWST`;
}

const PRINTED_AT = `This copy was printed on ${perthStamp(PROTOTYPE_NOW)}.`;

/**
 * Who to ring. The person's own team first, then the public crisis lines.
 *
 * The four public numbers are real and stay real. This sheet prints under "who
 * do I call at 2am", and a reader who dials a number on it must reach a service
 * rather than a fictional one — so they are read from the verified fixtures with
 * their stated limitations, their hours, and the official page each was checked
 * against. MHERL and Rurallink are telephone triage and support lines, not
 * emergency services, and the sheet says so beside each number rather than once
 * in a footnote.
 */
function CrisisContacts({ cmht }: { cmht: CmhtContact | null }) {
  return (
    <PrintSection testId="care-plan-safety-crisis" className={styles.safetySection}>
      <h3 className={styles.safetySectionHeading}>If you need help now</h3>
      {cmht === null ? null : (
        <div className={styles.crisisEntry}>
          <p className={styles.crisisName}>Your community mental health team</p>
          <p className={styles.crisisDetail}>{`${cmht.name} — ${cmht.dutyTelephoneDisplay}`}</p>
          <p className={styles.crisisDetail}>{cmht.operatingHours}</p>
        </div>
      )}
      {publicCrisisContacts.map((contact) => (
        <div key={contact.id} className={styles.crisisEntry}>
          <p className={styles.crisisName}>{`${contact.name} — ${contact.telephoneDisplay}`}</p>
          <p className={styles.crisisDetail}>{`${contact.coverage}. ${contact.availability}.`}</p>
          {contact.caveat === null ? null : <p className={styles.crisisCaveat}>{contact.caveat}</p>}
          <p className={styles.crisisSource}>
            {`Checked on ${formatPerthDate(contact.verifiedOn)} — `}
            <a href={contact.sourceUrl} className={styles.inlineLink}>
              {contact.sourceUrl}
            </a>
          </p>
        </div>
      ))}
    </PrintSection>
  );
}

export function SafetyPlanPrintSurface({
  patientId,
  scenario,
}: {
  patientId: string | null;
  scenario: PrototypeScenario;
}) {
  const { state, dispatch } = useCarePlanPrototype();
  const [printFailed, setPrintFailed] = useState(false);
  const snapshot = patientId === null ? null : buildPatientSnapshot(state, patientId as SyntheticId, PROTOTYPE_NOW);

  if (snapshot === null) {
    return (
      <EmptyState
        testId="care-plan-safety-no-patient"
        title="No patient is open."
        body="Open a synthetic patient from Home or Patients, then choose Personal Safety Plan."
      />
    );
  }

  const { patient, cmht } = snapshot;

  // Printing is exempt from the offline block and from nothing else. Paper
  // carrying a nearby person's safety plan cannot be taken back once it has left
  // the room, so identity uncertainty stops it outright and nothing is offered.
  if (scenario === "identity-uncertain") {
    return (
      <section aria-label={`${patient.fullName} Personal Safety Plan, printed copy`} className={styles.workspace}>
        <p role="alert" data-testid="care-plan-identity-uncertain" className={styles.identityUncertain}>
          <strong>This record has not been confirmed as the right person.</strong> Nothing is offered for printing,
          because paper carrying a nearby person&rsquo;s own words cannot be taken back. Return to search and choose the
          record again.
        </p>
      </section>
    );
  }

  const version = getCurrentSafetyPlanVersion(state.personalSafetyPlanVersions, patient.personalSafetyPlanId);

  if (version === null) {
    return (
      <section
        aria-label={`${patient.fullName} Personal Safety Plan, printed copy`}
        data-testid="care-plan-safety-print-surface"
        className={styles.workspace}
      >
        <p data-testid="care-plan-safety-print-unavailable" className={styles.noCurrentPlan}>
          {`${patient.preferredName} has no current Personal Safety Plan, so there is nothing to print. A draft is not this person's plan, and a draft on paper is a plan somebody may follow.`}
        </p>
        <p className={styles.planFooterLink}>
          <Link href={carePlanRoute.safetyPlan(patient.id)} className={styles.inlineLink}>
            Back to the Personal Safety Plan
          </Link>
        </p>
      </section>
    );
  }

  const blockedReason = getPrototypeMutationBlockReason(state, {
    type: "record-safety-plan-print-intent",
    patientId: patient.id,
  });
  // Whether this version holds any of the person's own words at all. A version
  // that holds none is a legitimate, deliberately demonstrated state — the
  // person declined, or nobody has been able to ask them — and the sheet must
  // not claim to be in their words when it is not.
  const ownWords = hasOwnWords(version.content);
  // Second person, because this sheet is addressed to the person themselves.
  const paperConfirmationRow = safetyPlanConfirmationRow(version, {
    withDate: "Confirmed with you on",
    withoutDate: "Confirmed with you",
  });

  return (
    <section
      aria-label={`${patient.fullName} Personal Safety Plan, printed copy`}
      data-testid="care-plan-safety-print-surface"
      className={styles.workspace}
    >
      <div className={styles.printControls} data-print-hide="true">
        {blockedReason !== null ? (
          <Button
            variant="primary"
            aria-disabled="true"
            aria-describedby="care-plan-safety-print-blocked"
            onClick={ignoreUnavailableActivation}
          >
            Print Personal Safety Plan
          </Button>
        ) : scenario === "print-failure" ? (
          // The print-failure specimen. The browser is never asked to print, and
          // no intent is recorded either: an audit line saying the print view was
          // opened would be untrue, and an application's own account of itself
          // must not claim more than it did.
          <Button variant="primary" onClick={() => setPrintFailed(true)}>
            Print Personal Safety Plan
          </Button>
        ) : (
          <BrowserPrintButton
            label="Print Personal Safety Plan"
            // Recorded before the browser is asked to print: a print dialogue can
            // block until the reader dismisses it, and may never return.
            onBeforePrint={() => dispatch({ type: "record-safety-plan-print-intent", patientId: patient.id })}
          />
        )}
        <Link href={carePlanRoute.safetyPlan(patient.id)} className={styles.inlineLink}>
          Back to the Personal Safety Plan
        </Link>
      </div>

      {blockedReason === null ? null : (
        <p
          id="care-plan-safety-print-blocked"
          role="alert"
          data-testid="care-plan-safety-print-blocked"
          className={styles.contactWarning}
        >
          {blockedReason}
        </p>
      )}

      {printFailed ? (
        <p role="alert" data-testid="care-plan-safety-print-failure" className={styles.launchFailure}>
          <strong>The print view could not be opened.</strong> Nothing was printed, and nothing was recorded. The whole
          plan is still on this page: read it from the screen, write the numbers down, or try printing again from the
          browser&rsquo;s own menu.
        </p>
      ) : null}

      {state.lastOutcome === null ? null : (
        <div data-testid="care-plan-safety-print-outcome" data-print-hide="true">
          <InlineNotice tone={PROTOTYPE_OUTCOME_TONE[state.lastOutcome.kind]}>{state.lastOutcome.message}</InlineNotice>
        </div>
      )}

      <PrintOutput
        testId="care-plan-safety-print-output"
        className={styles.safetyPaper}
        monochrome
        confidential
        printedAt={PRINTED_AT}
        provenance="Synthetic Care Plan prototype. Nothing on this page describes a real person, team, or hospital, and nothing here was saved. The public telephone numbers are the only real details on it."
      >
        <PrintSection className={styles.safetyPaperHead}>
          <SyntheticMarker />
          <h2 className={styles.safetyPaperTitle}>My Personal Safety Plan</h2>
          {/*
            Minimum necessary, and nothing beyond it. A preferred name and a
            record number are what a person needs to know the sheet is theirs and
            what a service needs to match it to them. A date of birth, an
            address, a pronoun, a home service, an episode, a plan version
            history, or anything about what a clinician thinks is not on this
            page, because none of it helps the reader and all of it travels.
          */}
          <dl className={styles.definitionGrid}>
            <DefinitionRow term="Name">{patient.preferredName}</DefinitionRow>
            <DefinitionRow term="Record number">{patient.mrn}</DefinitionRow>
            <DefinitionRow term="Version">{String(version.version)}</DefinitionRow>
            {/*
              Omitted entirely when this person did not confirm. A row reading
              `Not recorded` on a sheet addressed to the person tells them
              nothing they can use and reads as a mark against them, and the
              states with no confirmation are exactly the states where nothing
              was confirmed — saying so twice adds nothing. When they did
              confirm but the record does not hold when, the row says that in
              words rather than borrowing the day the version went live.
            */}
            {paperConfirmationRow === null ? null : (
              <DefinitionRow term={paperConfirmationRow.term}>{paperConfirmationRow.detail}</DefinitionRow>
            )}
          </dl>
          <p data-testid="care-plan-safety-paper-intro" className={styles.safetyPaperIntro}>
            {ownWords
              ? "This is your plan, in your own words. Keep it somewhere you can find it quickly. If it stops fitting, or something changes, tell someone on your team so you can write it again together."
              : "This copy holds the numbers to ring if you need help. Nothing else has been written down, and that is fine — it is your plan and yours to decide about. If you ever want to add your own part of it, someone on your team can write it with you."}
          </p>
        </PrintSection>

        <SafetyPlanSections content={version.content} emptySections="omit" />

        <CrisisContacts cmht={cmht} />
      </PrintOutput>
    </section>
  );
}
