import { spawnSync } from "node:child_process";

import { describe, expect, it } from "vitest";

import { diagnoseCodexCloud } from "../scripts/diagnose-codex-cloud.mjs";

const healthy = {
  nodeVersion: "26.8.1",
  npmVersion: "11.17.0",
  pythonVersion: "3.12.13",
  cloudLockContents:
    "# This file is autogenerated by pip-compile with Python 3.12\nsetuptools==83.0.0 --hash=sha256:test",
  setupStep: null,
  setupExitCode: null,
};

describe("Codex Cloud diagnostics", () => {
  it("reports a healthy aligned runtime", () => {
    expect(diagnoseCodexCloud(healthy)).toEqual([]);
  });

  it("explains the Python lock mismatch that previously stopped setup", () => {
    const issues = diagnoseCodexCloud({
      ...healthy,
      cloudLockContents: "# This file is autogenerated by pip-compile with Python 3.11\n",
      setupStep: "python-worker-requirements",
      setupExitCode: "1",
    });
    expect(issues.map((issue) => issue.code)).toEqual(["CLOUD_PYTHON_LOCK_TARGET", "SETUP_COMMAND_FAILED"]);
    expect(issues[0]?.fix).toContain("Python 3.12");
    expect(issues[1]?.fix).toContain("pip error immediately above");
  });

  it("reports an unavailable Cloud Python interpreter", () => {
    const issues = diagnoseCodexCloud({ ...healthy, pythonVersion: null });
    expect(issues.map((issue) => issue.code)).toEqual(["CLOUD_PYTHON_RUNTIME"]);
    expect(issues[0]?.issue).toContain("could not be executed");
    expect(issues[0]?.fix).toContain("Python 3.12");
  });

  it("does not mistake a desktop Python version for Cloud runtime drift", () => {
    const environment = { ...process.env };
    delete environment.CODEX_CLOUD;
    delete environment.CODEX_CLOUD_OCR_PYTHON;
    const result = spawnSync(process.execPath, ["scripts/diagnose-codex-cloud.mjs"], {
      cwd: process.cwd(),
      encoding: "utf8",
      env: environment,
    });

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain("status=NOT_APPLICABLE issues=0");
    expect(result.stdout).toContain("local Python versions are not Cloud runtime evidence");
    expect(result.stdout).not.toContain("CLOUD_PYTHON_RUNTIME");
  });
});
