import { describe, expect, it } from "vitest";

import { diagnoseCodexCloud } from "../scripts/diagnose-codex-cloud.mjs";

const healthy = {
  nodeVersion: "24.18.1",
  npmVersion: "11.17.0",
  pythonVersion: "3.12.13",
  cloudLockContents:
    "# This file is autogenerated by pip-compile with Python 3.12\nsetuptools==83.0.0 --hash=sha256:test",
  setupStep: null,
  setupExitCode: null,
};

describe("Codex Cloud diagnostics", () => {
  it("reports a healthy aligned runtime", () => {
    expect(diagnoseCodexCloud(healthy)).toEqual([]);
  });

  it("explains the Python lock mismatch that previously stopped setup", () => {
    const issues = diagnoseCodexCloud({
      ...healthy,
      cloudLockContents: "# This file is autogenerated by pip-compile with Python 3.11\n",
      setupStep: "python-worker-requirements",
      setupExitCode: "1",
    });
    expect(issues.map((issue) => issue.code)).toEqual(["CLOUD_PYTHON_LOCK_TARGET", "SETUP_COMMAND_FAILED"]);
    expect(issues[0]?.fix).toContain("Python 3.12");
    expect(issues[1]?.fix).toContain("pip error immediately above");
  });
});
