export type WardRole = "flow" | "ed" | "ward";

export type MovementStage =
  "placement_requested" | "destination_review" | "bed_held" | "handover_ready" | "moving" | "arrived";

export type PatientCohort = "Adult" | "Older adult";
export type WardSetting = "Open" | "Secure";

export type WardPatient = {
  id: string;
  urgency: 1 | 2 | 3;
  elapsed: string;
  cohort: PatientCohort;
  setting: WardSetting;
  catchment: "North" | "East" | "South" | "Country";
  voluntaryStatus:
    "Voluntary" | "Referred for psychiatric examination" | "Detained awaiting examination" | "Involuntary inpatient";
  legalDetail: string;
  destinationCode: string;
  destinationName: string;
  stage: MovementStage;
  owner: string;
  score: number;
  referredTo: string;
  referralStatus: string;
  transport: string;
  blocker: string;
  recommendationReasons: string[];
  alternatives: Array<{
    hospitalCode: string;
    hospitalName: string;
    score: number;
    reason: string;
    /** Synthetic transport outlook for this alternative, where one has been modelled. */
    etaLabel?: string;
  }>;
};

export type WardHospital = {
  id: string;
  code: string;
  name: string;
  region: "North" | "East" | "South" | "Country";
  /** WACHS services sit outside the three metropolitan health services. */
  service: "North Metro" | "East Metro" | "South Metro" | "WACHS" | "Private";
  settings: WardSetting[];
  cohorts: PatientCohort[];
  beds: number;
  /** Confirmed empty and allocatable now. */
  available: number;
  /** Reserved for a named movement until a stated expiry. */
  held: number;
  /** A subset of `occupied` expected to free after a named action. Not yet allocatable. */
  potential: number;
  /** Present but unusable, with a reason. */
  blocked: number;
  /** In use. `available + held + blocked + occupied` always equals `beds`. */
  occupied: number;
  lastConfirmed: string;
};

export const wardPatients: WardPatient[] = [
  {
    id: "WF-204",
    urgency: 1,
    elapsed: "6h 18m",
    cohort: "Adult",
    setting: "Open",
    catchment: "South",
    voluntaryStatus: "Voluntary",
    legalDetail: "No Mental Health Act transport form required",
    destinationCode: "FSH",
    destinationName: "Fiona Stanley Hospital",
    stage: "destination_review",
    owner: "Flow coordinator",
    score: 92,
    referredTo: "FSH Adult Open",
    referralStatus: "Destination review",
    transport: "Ready · estimated 35 min",
    blocker: "Awaiting destination confirmation",
    recommendationReasons: [
      "South catchment is the local service",
      "Exact adult open-ward capability",
      "Four allocatable beds confirmed at 10:40",
      "Transport is ready within 35 minutes",
    ],
    alternatives: [
      {
        hospitalCode: "FRE",
        hospitalName: "Fremantle",
        score: 81,
        reason: "Local alternative · 8 available",
        etaLabel: "On time · 45 min",
      },
      {
        hospitalCode: "RCK",
        hospitalName: "Rockingham",
        score: 76,
        reason: "Local alternative · 6 available",
        etaLabel: "Delayed · 1h 15m",
      },
    ],
  },
  {
    id: "WF-198",
    urgency: 2,
    elapsed: "3h 40m",
    cohort: "Older adult",
    setting: "Secure",
    catchment: "East",
    voluntaryStatus: "Referred for psychiatric examination",
    legalDetail: "Form 1A ready · review timing due 12:15",
    destinationCode: "RPH",
    destinationName: "Royal Perth Hospital",
    stage: "destination_review",
    owner: "ED mental health team",
    score: 86,
    referredTo: "RPH Older Adult Secure",
    referralStatus: "Review overdue by 1h 12m",
    transport: "Request ready · risk documents complete",
    blocker: "Destination response overdue",
    recommendationReasons: [
      "East catchment is the local service",
      "Older-adult secure capability matches",
      "Statutory timing contributes to priority",
      "Transport documentation is complete",
    ],
    alternatives: [
      { hospitalCode: "SCG", hospitalName: "Sir Charles Gairdner", score: 75, reason: "Statewide secure option" },
      { hospitalCode: "GRY", hospitalName: "Graylands", score: 72, reason: "Capability fit · catchment escalation" },
    ],
  },
  {
    id: "WF-201",
    urgency: 2,
    elapsed: "5h 05m",
    cohort: "Adult",
    setting: "Open",
    catchment: "South",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "FSH",
    destinationName: "Fiona Stanley Hospital",
    stage: "destination_review",
    owner: "Flow coordinator",
    score: 81,
    referredTo: "FSH Adult Open",
    referralStatus: "Destination review",
    transport: "Booked · ETA delayed by 90 min",
    blocker: "Transport delay",
    recommendationReasons: [
      "South catchment is the local service",
      "Adult open capability matches",
      "Transport delay raises operational priority",
    ],
    alternatives: [
      { hospitalCode: "FRE", hospitalName: "Fremantle", score: 77, reason: "Local alternative" },
      { hospitalCode: "RCK", hospitalName: "Rockingham", score: 71, reason: "Local alternative" },
    ],
  },
  {
    id: "WF-209",
    urgency: 3,
    elapsed: "7h 20m",
    cohort: "Adult",
    setting: "Open",
    catchment: "Country",
    voluntaryStatus: "Referred for psychiatric examination",
    legalDetail: "Form 1A ready · MHPF transfer coordination",
    destinationCode: "RCK",
    destinationName: "Rockingham General Hospital",
    stage: "placement_requested",
    owner: "WACHS MHETS",
    score: 76,
    referredTo: "Rockingham Adult Open",
    referralStatus: "Referral sent",
    transport: "Requested · provider response pending",
    blocker: "Metro destination not yet confirmed",
    recommendationReasons: [
      "Country transfer escalation is active",
      "Adult open capability matches",
      "MHPF coordination is recorded",
    ],
    alternatives: [
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 72, reason: "Statewide capability fit" },
      { hospitalCode: "FRE", hospitalName: "Fremantle", score: 69, reason: "Statewide capability fit" },
    ],
  },
  {
    id: "WF-212",
    urgency: 3,
    elapsed: "9h 35m",
    cohort: "Older adult",
    setting: "Open",
    catchment: "South",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "FRE",
    destinationName: "Fremantle Hospital",
    stage: "bed_held",
    owner: "Ward manager",
    score: 74,
    referredTo: "Fremantle Older Adult Open",
    referralStatus: "Bed held until 11:20",
    transport: "Booked · pickup 11:05",
    blocker: "Handover acknowledgement pending",
    recommendationReasons: [
      "South catchment is the local service",
      "Older-adult open capability matches",
      "Time-limited bed hold is active",
    ],
    alternatives: [
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 70, reason: "Local alternative" },
      { hospitalCode: "SCG", hospitalName: "Sir Charles Gairdner", score: 64, reason: "Statewide alternative" },
    ],
  },
  {
    id: "WF-187",
    urgency: 3,
    elapsed: "10h 05m",
    cohort: "Adult",
    setting: "Secure",
    catchment: "East",
    voluntaryStatus: "Detained awaiting examination",
    legalDetail: "Form 4A ready · timing due 13:00",
    destinationCode: "RPH",
    destinationName: "Royal Perth Hospital",
    stage: "destination_review",
    owner: "ED mental health team",
    score: 71,
    referredTo: "RPH Adult Secure",
    referralStatus: "Destination review",
    transport: "Request ready · Form 4A attached",
    blocker: "Secure suitability review pending",
    recommendationReasons: [
      "East catchment is the local service",
      "Adult secure capability matches",
      "Legal transport documentation is ready",
    ],
    alternatives: [
      { hospitalCode: "GRY", hospitalName: "Graylands", score: 67, reason: "Statewide secure option" },
      { hospitalCode: "SCG", hospitalName: "Sir Charles Gairdner", score: 62, reason: "Statewide secure option" },
    ],
  },
  {
    id: "WF-210",
    urgency: 3,
    elapsed: "11h 20m",
    cohort: "Older adult",
    setting: "Open",
    catchment: "Country",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary transfer · WACHS transport plan",
    destinationCode: "ALB",
    destinationName: "Albany Health Campus",
    stage: "handover_ready",
    owner: "Ward manager",
    score: 69,
    referredTo: "Albany Older Adult Open",
    referralStatus: "Accepted · handover ready",
    transport: "Booked · pickup 12:10",
    blocker: "No blocker",
    recommendationReasons: [
      "Country catchment destination is local",
      "Older-adult open capability matches",
      "Handover and transport are ready",
    ],
    alternatives: [
      { hospitalCode: "BUN", hospitalName: "Bunbury", score: 60, reason: "Country alternative" },
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 55, reason: "Statewide escalation" },
    ],
  },
  {
    id: "WF-199",
    urgency: 3,
    elapsed: "12h 05m",
    cohort: "Adult",
    setting: "Open",
    catchment: "East",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "RPH",
    destinationName: "Royal Perth Hospital",
    stage: "destination_review",
    owner: "Flow coordinator",
    score: 65,
    referredTo: "RPH Adult Open",
    referralStatus: "Destination review",
    transport: "Not yet required",
    blocker: "Awaiting suitability response",
    recommendationReasons: [
      "East catchment is the local service",
      "Adult open capability matches",
      "Seven allocatable beds confirmed",
    ],
    alternatives: [
      { hospitalCode: "ARM", hospitalName: "Armadale", score: 61, reason: "Local alternative" },
      { hospitalCode: "BTY", hospitalName: "Bentley", score: 58, reason: "Local alternative" },
    ],
  },
  {
    id: "WF-215",
    urgency: 3,
    elapsed: "12h 40m",
    cohort: "Adult",
    setting: "Open",
    catchment: "North",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "SCG",
    destinationName: "Sir Charles Gairdner Hospital",
    stage: "placement_requested",
    owner: "Flow coordinator",
    score: 63,
    referredTo: "SCGH Adult Open",
    referralStatus: "Referral ready",
    transport: "Not yet required",
    blocker: "Referral not yet sent",
    recommendationReasons: ["North catchment is local", "Adult open capability matches"],
    alternatives: [
      { hospitalCode: "JND", hospitalName: "Joondalup", score: 59, reason: "Local alternative" },
      { hospitalCode: "GRY", hospitalName: "Graylands", score: 54, reason: "Local alternative" },
    ],
  },
  {
    id: "WF-193",
    urgency: 3,
    elapsed: "13h 15m",
    cohort: "Adult",
    setting: "Open",
    catchment: "South",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "RCK",
    destinationName: "Rockingham General Hospital",
    stage: "moving",
    owner: "Flow coordinator",
    score: 61,
    referredTo: "Rockingham Adult Open",
    referralStatus: "Accepted · moving",
    transport: "Collected · ETA 10:58",
    blocker: "No blocker",
    recommendationReasons: ["Accepted destination", "Transport collected"],
    alternatives: [
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 55, reason: "Local alternative" },
      { hospitalCode: "FRE", hospitalName: "Fremantle", score: 52, reason: "Local alternative" },
    ],
  },
  {
    id: "WF-202",
    urgency: 3,
    elapsed: "13h 45m",
    cohort: "Older adult",
    setting: "Open",
    catchment: "North",
    voluntaryStatus: "Involuntary inpatient",
    legalDetail: "Involuntary order current · transfer authority ready",
    destinationCode: "GRY",
    destinationName: "Graylands Hospital",
    stage: "bed_held",
    owner: "Ward manager",
    score: 59,
    referredTo: "Graylands Older Adult Open",
    referralStatus: "Bed held until 12:00",
    transport: "Requested",
    blocker: "Provider ETA pending",
    recommendationReasons: ["North catchment option", "Older-adult capability matches"],
    alternatives: [
      { hospitalCode: "SCG", hospitalName: "Sir Charles Gairdner", score: 53, reason: "Local alternative" },
      { hospitalCode: "RPH", hospitalName: "Royal Perth", score: 50, reason: "Statewide alternative" },
    ],
  },
  {
    id: "WF-206",
    urgency: 3,
    elapsed: "14h 05m",
    cohort: "Adult",
    setting: "Open",
    catchment: "Country",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary transfer · WACHS transport plan",
    destinationCode: "BUN",
    destinationName: "Bunbury Regional Hospital",
    stage: "handover_ready",
    owner: "WACHS MHETS",
    score: 57,
    referredTo: "Bunbury Adult Open",
    referralStatus: "Accepted · handover ready",
    transport: "Booked",
    blocker: "No blocker",
    recommendationReasons: ["Country catchment destination", "Handover is ready"],
    alternatives: [
      { hospitalCode: "ALB", hospitalName: "Albany", score: 49, reason: "Country alternative" },
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 44, reason: "Statewide escalation" },
    ],
  },
  {
    id: "WF-217",
    urgency: 3,
    elapsed: "14h 30m",
    cohort: "Adult",
    setting: "Open",
    catchment: "East",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary admission pathway",
    destinationCode: "ARM",
    destinationName: "Armadale Health Service",
    stage: "placement_requested",
    owner: "ED mental health team",
    score: 54,
    referredTo: "Armadale Adult Open",
    referralStatus: "Referral ready",
    transport: "Not yet required",
    blocker: "ED readiness check incomplete",
    recommendationReasons: ["East catchment is local", "Adult open capability matches"],
    alternatives: [
      { hospitalCode: "RPH", hospitalName: "Royal Perth", score: 50, reason: "Local alternative" },
      { hospitalCode: "BTY", hospitalName: "Bentley", score: 48, reason: "Local alternative" },
    ],
  },
  {
    id: "WF-221",
    urgency: 3,
    elapsed: "15h 10m",
    cohort: "Older adult",
    setting: "Open",
    catchment: "Country",
    voluntaryStatus: "Voluntary",
    legalDetail: "Voluntary transfer · WACHS coordination",
    destinationCode: "ALB",
    destinationName: "Albany Health Campus",
    stage: "arrived",
    owner: "Ward manager",
    score: 50,
    referredTo: "Albany Older Adult Open",
    referralStatus: "Arrived · closure pending",
    transport: "Arrived",
    blocker: "Closure acknowledgement pending",
    recommendationReasons: ["Arrival recorded", "Closure is the next owned action"],
    alternatives: [
      { hospitalCode: "BUN", hospitalName: "Bunbury", score: 41, reason: "Not required" },
      { hospitalCode: "FSH", hospitalName: "Fiona Stanley", score: 38, reason: "Not required" },
    ],
  },
];

const movementStageLabels: Array<{ id: MovementStage; label: string; shortLabel: string }> = [
  { id: "placement_requested", label: "Placement requested", shortLabel: "Requested" },
  { id: "destination_review", label: "Destination review", shortLabel: "Review" },
  { id: "bed_held", label: "Bed held", shortLabel: "Held" },
  { id: "handover_ready", label: "Handover ready", shortLabel: "Ready" },
  { id: "moving", label: "Moving", shortLabel: "Moving" },
  { id: "arrived", label: "Arrived", shortLabel: "Arrived" },
];

/**
 * Counts are derived from `wardPatients` so the pipeline strip can never advertise more
 * movements than any other surface is able to show.
 */
export const movementStages = movementStageLabels.map((stage) => ({
  ...stage,
  count: wardPatients.filter((patient) => patient.stage === stage.id).length,
}));

export const wardHospitals: WardHospital[] = [
  {
    id: "scgh",
    code: "SCGH",
    name: "Sir Charles Gairdner",
    region: "North",
    service: "North Metro",
    settings: ["Open", "Secure"],
    cohorts: ["Adult", "Older adult"],
    beds: 36,
    available: 12,
    held: 2,
    potential: 3,
    blocked: 1,
    occupied: 21,
    lastConfirmed: "10:38",
  },
  {
    id: "graylands",
    code: "GRY",
    name: "Graylands",
    region: "North",
    service: "North Metro",
    settings: ["Open", "Secure"],
    cohorts: ["Adult", "Older adult"],
    beds: 28,
    available: 7,
    held: 1,
    potential: 2,
    blocked: 0,
    occupied: 20,
    lastConfirmed: "10:28",
  },
  {
    id: "joondalup",
    code: "JND",
    name: "Joondalup",
    region: "North",
    service: "North Metro",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 32,
    available: 5,
    held: 0,
    potential: 1,
    blocked: 1,
    occupied: 26,
    lastConfirmed: "10:40",
  },
  {
    id: "rph",
    code: "RPH",
    name: "Royal Perth",
    region: "East",
    service: "East Metro",
    settings: ["Open", "Secure"],
    cohorts: ["Adult", "Older adult"],
    beds: 32,
    available: 7,
    held: 1,
    potential: 2,
    blocked: 0,
    occupied: 24,
    lastConfirmed: "10:36",
  },
  {
    id: "bentley",
    code: "BTY",
    name: "Bentley",
    region: "East",
    service: "East Metro",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 26,
    available: 5,
    held: 1,
    potential: 1,
    blocked: 0,
    occupied: 20,
    lastConfirmed: "10:39",
  },
  {
    id: "armadale",
    code: "ARM",
    name: "Armadale",
    region: "East",
    service: "East Metro",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 26,
    available: 3,
    held: 0,
    potential: 1,
    blocked: 1,
    occupied: 22,
    lastConfirmed: "10:35",
  },
  {
    id: "sjog",
    code: "SJG",
    name: "St John of God",
    region: "East",
    service: "Private",
    settings: ["Open"],
    cohorts: ["Adult"],
    beds: 24,
    available: 3,
    held: 0,
    potential: 1,
    blocked: 0,
    occupied: 21,
    lastConfirmed: "10:26",
  },
  {
    id: "fsh",
    code: "FSH",
    name: "Fiona Stanley",
    region: "South",
    service: "South Metro",
    settings: ["Open", "Secure"],
    cohorts: ["Adult", "Older adult"],
    beds: 30,
    available: 9,
    held: 1,
    potential: 2,
    blocked: 0,
    occupied: 20,
    lastConfirmed: "10:40",
  },
  {
    id: "fremantle",
    code: "FRE",
    name: "Fremantle",
    region: "South",
    service: "South Metro",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 28,
    available: 8,
    held: 1,
    potential: 1,
    blocked: 0,
    occupied: 19,
    lastConfirmed: "10:39",
  },
  {
    id: "rockingham",
    code: "RCK",
    name: "Rockingham",
    region: "South",
    service: "South Metro",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 28,
    available: 6,
    held: 1,
    potential: 1,
    blocked: 0,
    occupied: 21,
    lastConfirmed: "10:41",
  },
  {
    id: "mandurah",
    code: "MAN",
    name: "Mandurah",
    region: "South",
    service: "South Metro",
    settings: ["Open"],
    cohorts: ["Adult"],
    beds: 28,
    available: 3,
    held: 0,
    potential: 1,
    blocked: 0,
    occupied: 25,
    lastConfirmed: "10:34",
  },
  {
    id: "albany",
    code: "ALB",
    name: "Albany",
    region: "Country",
    service: "WACHS",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 28,
    available: 4,
    held: 1,
    potential: 1,
    blocked: 0,
    occupied: 23,
    lastConfirmed: "10:37",
  },
  {
    id: "bunbury",
    code: "BUN",
    name: "Bunbury",
    region: "Country",
    service: "WACHS",
    settings: ["Open"],
    cohorts: ["Adult", "Older adult"],
    beds: 28,
    available: 6,
    held: 1,
    potential: 1,
    blocked: 0,
    occupied: 21,
    lastConfirmed: "10:39",
  },
  {
    id: "broome",
    code: "BRM",
    name: "Broome",
    region: "Country",
    service: "WACHS",
    settings: ["Open"],
    cohorts: ["Adult"],
    beds: 20,
    available: 2,
    held: 0,
    potential: 1,
    blocked: 0,
    occupied: 18,
    lastConfirmed: "10:30",
  },
  {
    id: "geraldton",
    code: "GER",
    name: "Geraldton",
    region: "Country",
    service: "WACHS",
    settings: ["Open"],
    cohorts: ["Adult"],
    beds: 22,
    available: 2,
    held: 0,
    potential: 1,
    blocked: 0,
    occupied: 20,
    lastConfirmed: "10:33",
  },
  {
    id: "kununurra",
    code: "KUN",
    name: "Kununurra",
    region: "Country",
    service: "WACHS",
    settings: ["Open"],
    cohorts: ["Adult"],
    beds: 26,
    available: 0,
    held: 1,
    potential: 1,
    blocked: 1,
    occupied: 24,
    lastConfirmed: "10:24",
  },
];

export const wardRegions = ["North", "East", "South", "Country"] as const;

export function wardPatientById(id: string) {
  return wardPatients.find((patient) => patient.id === id) ?? wardPatients[0];
}

export function wardHospitalByCode(code: string) {
  return wardHospitals.find((hospital) => hospital.code === code || hospital.code.startsWith(code)) ?? wardHospitals[0];
}

export function operationalPriorityScore(patient: WardPatient) {
  return Math.max(0, Math.min(99, patient.score - patient.urgency * 5 - 9));
}
