// Generated by scripts/build-therapies-index.mjs. Do not edit.
export const THERAPY_CATALOGUE_ASSETS = {
  full: "therapies.a9dc3ae40e9d29fa.json",
  index: "therapies-index.8455f92cf736cbfa.json",
  home: "therapies-home.211dab554c4ec62d.json",
} as const;

// The generation this one replaced. Retained on disk for exactly one deploy so a
// client whose bundle still names the previous content-addressed URL does not 404
// mid-session; older generations are pruned. `useTherapyData` also falls back to
// the unversioned alias, which covers bundles built before that fallback existed.
export const THERAPY_CATALOGUE_ASSETS_PREVIOUS = {
  full: "therapies.a9dc3ae40e9d29fa.json",
  index: "therapies-index.4b4ee988e0ff84e2.json",
  home: "therapies-home.211dab554c4ec62d.json",
} as const;
