// Generated by scripts/build-therapies-index.mjs. Do not edit.
export const THERAPY_CATALOGUE_ASSETS = {
  full: "therapies.a9dc3ae40e9d29fa.json",
  index: "therapies-index.f7a834fb99cd9d6f.json",
  home: "therapies-home.7c762071003dc6ca.json",
} as const;
