// Generated by scripts/build-therapies-index.mjs. Do not edit.
export const THERAPY_CATALOGUE_ASSETS = {
  full: "therapies.0e05d7e4191145a5.json",
  index: "therapies-index.cc0bdf69338e0a7e.json",
  home: "therapies-home.62246b1525741d11.json",
} as const;
