/**
 * Constraint-match data for the Recommend scenario popup study.
 *
 * DERIVED, NOT WRITTEN. Every row is one of the 205 records in
 * `src/data/therapies-source.json`, and its mask is the result of running the
 * shipped `RECOMMEND_CONSTRAINTS[i].match(therapy)` predicates from
 * `src/components/therapy-compass/data/select.ts` over that record. Bit `i`
 * is set when constraint `i` in ["outpatient", "inpatient", "5min", "15min", "handout", "grounding", "skills", "psychoeducation", "trauma", "avoid-mania"]
 * matches. Regenerate by re-running those predicates if the catalogue or the
 * predicates change; do not hand-edit a mask.
 *
 * It is here so the popup's live "matches N of 205" counter is the real answer
 * for any chip combination rather than an invented number. The counter covers
 * the constraint chips only: free-text relevance ranking is not modelled.
 */

export const CONSTRAINT_KEYS = [
  "outpatient",
  "inpatient",
  "5min",
  "15min",
  "handout",
  "grounding",
  "skills",
  "psychoeducation",
  "trauma",
  "avoid-mania",
] as const;

export const TOTAL_RECORDS = 205;

/** [name, category, constraint bitmask] */
export const CATALOGUE: Array<[string, string, number]> = [
  ["Acceptance and Commitment Therapy (ACT)", "Standard Talking Therapies", 380],
  ["Adherence-Focused Brief Work / Adherence Therapy", "Foundational & Engagement Therapies", 349],
  ["Adolescent CBT", "Child & Adolescent Therapies", 350],
  ["Adolescent-focused psychotherapy for anorexia nervosa", "Eating Disorder Therapies", 862],
  ["Advocacy-informed therapeutic work", "Community & Casework Support", 797],
  ["App-supported therapy", "Self-Help & Digital Therapies", 348],
  ["Applied Relaxation / Relaxation-Based Therapy", "Foundational & Engagement Therapies", 380],
  ["Arts Therapies for Psychosis", "Psychosis & Rehabilitation Therapies", 606],
  ["Behaviour Therapy", "Standard Talking Therapies", 863],
  ["Behavioural Activation (BA)", "Standard Talking Therapies", 351],
  ["Behavioural Couples Therapy (BCT)", "Family & Couple Therapies", 860],
  ["Behavioural Couples Therapy for Substance Use Disorders (BCT-SUD)", "Substance Use Therapies", 605],
  ["Behavioural parent training", "Child & Adolescent Therapies", 861],
  ["Brief low-intensity CBT", "Self-Help & Digital Therapies", 348],
  ["Brief supportive psychotherapy", "Foundational & Engagement Therapies", 351],
  ["Bright-light therapy", "Brain & Body Therapies", 92],
  ["Carer groups", "Group IPT", 541],
  ["Carer Interventions", "Family & Couple Therapies", 605],
  [
    "Carer-Focused Education and Support / Carer Psychoeducation in Psychosis",
    "Psychosis & Rehabilitation Therapies",
    732,
  ],
  ["Carer-supported meal-based interventions", "Eating Disorder Therapies", 863],
  ["CBT-informed psychological intervention for self-harm", "Foundational & Engagement Therapies", 351],
  ["Child CBT", "Child & Adolescent Therapies", 860],
  ["Circadian / rhythm-based interventions", "Brain & Body Therapies", 92],
  ["Client-Directed / Feedback-Informed Brief Work", "Foundational & Engagement Therapies", 543],
  ["Cognitive Analytic Therapy (CAT)", "Personality Disorder Therapies", 348],
  ["Cognitive Behavioural Therapy (CBT)", "Standard Talking Therapies", 351],
  [
    "Cognitive Behavioural Therapy for Bipolar Depression / Bipolar Relapse Prevention",
    "Standard Talking Therapies",
    93,
  ],
  ["Cognitive behavioural therapy for insomnia", "Standard Talking Therapies", 348],
  ["Cognitive Behavioural Therapy for Insomnia (CBT-I)", "Brain & Body Therapies", 348],
  ["Cognitive Behavioural Therapy for Psychosis (CBTp)", "Psychosis & Rehabilitation Therapies", 380],
  ["Cognitive Processing Therapy (CPT)", "Trauma Therapies", 860],
  ["Cognitive Remediation Therapy (CRT)", "Psychosis & Rehabilitation Therapies", 604],
  ["Cognitive stimulation therapy", "Brain & Body Therapies", 541],
  ["Cognitive Therapy", "Standard Talking Therapies", 861],
  ["Cognitive Therapy for PTSD (CT-PTSD)", "Trauma Therapies", 380],
  ["Community Reinforcement and Family Training (CRAFT)", "Substance Use Therapies", 541],
  ["Community reinforcement approach", "Substance Use Therapies", 351],
  ["Community-based psychosocial intervention", "Community & Casework Support", 799],
  ["Compassion-focused therapy", "Humanistic & Meaning-Based Therapies", 380],
  ["Constructivist therapies", "Humanistic & Meaning-Based Therapies", 381],
  ["Contingency Management (CM)", "Substance Use Therapies", 605],
  ["Coping-Skills Interventions", "Foundational & Engagement Therapies", 381],
  ["Couples Therapy", "Family & Couple Therapies", 892],
  ["Craving-management interventions", "Substance Use Therapies", 380],
  ["Crisis intervention / crisis-oriented brief therapy", "Foundational & Engagement Therapies", 351],
  ["Cue Exposure Therapy (CET) for Substance Use Disorders", "Substance Use Therapies", 604],
  ["DBT skills groups", "Group CBT", 380],
  ["DBT-Informed Adjunctive Emotion-Regulation Work for Eating Disorders", "Eating Disorder Therapies", 636],
  ["Developmental social-skills interventions", "Child & Adolescent Therapies", 861],
  ["Developmentally adapted DBT", "Child & Adolescent Therapies", 383],
  ["Developmentally adapted ERP", "Child & Adolescent Therapies", 862],
  ["Dialectical Behaviour Therapy (DBT)", "Personality Disorder Therapies", 380],
  ["Dignity therapy", "Humanistic & Meaning-Based Therapies", 317],
  ["Dyadic Therapy", "Family & Couple Therapies", 796],
  ["Dynamic interpersonal therapy", "Personality Disorder Therapies", 348],
  ["Eating-Disorder-Focused Cognitive Behavioural Therapy (CBT-ED / CBT-E)", "Eating Disorder Therapies", 606],
  [
    "Eating-Disorder-Focused Focal Psychodynamic Therapy (FPT) for Adult Anorexia Nervosa",
    "Eating Disorder Therapies",
    606,
  ],
  ["ECT", "Brain & Body Therapies", 540],
  ["Emotion-focused therapy", "Humanistic & Meaning-Based Therapies", 892],
  ["Empowerment-focused practice", "Community & Casework Support", 349],
  ["Existential psychotherapy", "Humanistic & Meaning-Based Therapies", 348],
  ["Experiential therapies", "Humanistic & Meaning-Based Therapies", 861],
  ["Exposure and Response Prevention (ERP)", "OCD & Exposure Therapies", 351],
  ["Exposure and Response Prevention for Tics (ERP for Tics)", "OCD & Exposure Therapies", 636],
  ["Exposure therapy", "OCD & Exposure Therapies", 350],
  ["Exposure-Based CBT / Exposure Therapy", "OCD & Exposure Therapies", 863],
  ["Eye Movement Desensitisation and Reprocessing (EMDR)", "Trauma Therapies", 348],
  ["Family Intervention for Psychosis", "Psychosis & Rehabilitation Therapies", 605],
  ["Family problem-solving interventions", "Family & Couple Therapies", 92],
  ["Family Psychoeducation for Psychosis", "Psychosis & Rehabilitation Therapies", 732],
  ["Family Therapy", "Family & Couple Therapies", 540],
  ["Family-Based Treatment for Adolescent Anorexia Nervosa (FT-AN)", "Eating Disorder Therapies", 606],
  ["Family-Based Treatment for Bulimia Nervosa (FT-BN)", "Eating Disorder Therapies", 604],
  ["Family-Focused Psychoeducation for Bipolar Disorder", "Family & Couple Therapies", 220],
  ["Family-Focused Therapy for Bipolar Disorder (FFT-BD)", "Family & Couple Therapies", 93],
  ["Functional Family Therapy (FFT)", "Family & Couple Therapies", 93],
  ["Gestalt therapy", "Humanistic & Meaning-Based Therapies", 892],
  ["Good psychiatric management", "Personality Disorder Therapies", 351],
  ["Graded Exposure", "OCD & Exposure Therapies", 863],
  ["Group exposure programmes", "Group IPT", 348],
  ["Group psychoeducation", "Group CBT", 477],
  ["Group Psychoeducation for Bipolar Disorder", "Group CBT", 220],
  ["Group relapse-prevention programmes", "Group CBT", 348],
  ["Group social-skills training", "Group IPT", 351],
  ["Guided self-help", "Self-Help & Digital Therapies", 348],
  ["Guided Self-Help for Binge Eating Disorder", "Eating Disorder Therapies", 604],
  ["Guided Self-Help for Bulimia-Nervosa", "Eating Disorder Therapies", 604],
  ["Habit reversal training / CBIT", "OCD & Exposure Therapies", 348],
  ["Habit Reversal Training for Trichotillomania and Excoriation Disorder", "OCD & Exposure Therapies", 637],
  ["Harm-reduction counselling", "Substance Use Therapies", 351],
  ["Health-anxiety-focused CBT", "Standard Talking Therapies", 860],
  ["Humanistic psychotherapy", "Humanistic & Meaning-Based Therapies", 892],
  [
    "Illness-Management-and-Recovery Style Interventions (IMR-Style Interventions)",
    "Psychosis & Rehabilitation Therapies",
    605,
  ],
  ["Imagery Rehearsal Therapy (IRT) for Nightmare Disorder", "Brain & Body Therapies", 894],
  ["Imagery rescripting", "OCD & Exposure Therapies", 380],
  ["Inference-based CBT for OCD", "OCD & Exposure Therapies", 860],
  ["Integrated CBT for PTSD and Substance Use Disorders", "Trauma Therapies", 861],
  ["Integrated dual-diagnosis psychotherapy", "Substance Use Therapies", 863],
  ["Intensive Psychodynamic Psychotherapy", "Personality Disorder Therapies", 862],
  ["Internet-delivered CBT", "Self-Help & Digital Therapies", 348],
  ["Interoceptive Exposure", "OCD & Exposure Therapies", 861],
  ["Interpersonal and Social Rhythm Therapy (IPSRT)", "Standard Talking Therapies", 93],
  ["Interpersonal Psychotherapy (IPT)", "Standard Talking Therapies", 349],
  ["Life-review therapy / reminiscence therapy", "Humanistic & Meaning-Based Therapies", 797],
  ["Low-intensity relapse-prevention programmes", "Self-Help & Digital Therapies", 604],
  ["Matrix Model", "Substance Use Therapies", 607],
  ["Maudsley Anorexia Nervosa Treatment for Adults (MANTRA)", "Eating Disorder Therapies", 607],
  ["Meaning-centred psychotherapy", "Humanistic & Meaning-Based Therapies", 828],
  ["Mentalisation-Based Therapy (MBT)", "Personality Disorder Therapies", 349],
  ["Metacognitive Therapy (MCT)", "Standard Talking Therapies", 860],
  ["Mindfulness-Based Cognitive Therapy (MBCT)", "Standard Talking Therapies", 349],
  ["Mindfulness-Based Relapse Prevention (MBRP)", "Substance Use Therapies", 861],
  ["Mindfulness-based stress reduction", "Humanistic & Meaning-Based Therapies", 380],
  ["Mindfulness-based therapies not primarily CBT-anchored", "Humanistic & Meaning-Based Therapies", 380],
  ["Mindfulness-Based Therapy for Insomnia (MBTI)", "Brain & Body Therapies", 124],
  ["Mother-Infant Therapy / Mother-Infant Psychotherapy", "Family & Couple Therapies", 94],
  ["Motivational Enhancement Therapy (MET)", "Foundational & Engagement Therapies", 861],
  ["Motivational Interviewing", "Foundational & Engagement Therapies", 861],
  ["Motivational Interviewing (MI) for Substance Use Disorders", "Substance Use Therapies", 605],
  ["Multi-Family Interventions", "Family & Couple Therapies", 604],
  ["Multidimensional family therapy", "Family & Couple Therapies", 351],
  ["Multisystemic Therapy (MST)", "Family & Couple Therapies", 607],
  ["Narrative Exposure Therapy (NET)", "Trauma Therapies", 380],
  ["Narrative therapy", "Humanistic & Meaning-Based Therapies", 349],
  ["Narrative-informed community work", "Community & Casework Support", 861],
  ["Neurodevelopmentally adapted psychosocial interventions", "Child & Adolescent Therapies", 348],
  ["Panic-focused CBT", "Standard Talking Therapies", 860],
  ["Parent Management Training (PMT)", "Child & Adolescent Therapies", 93],
  ["Parent Training", "Child & Adolescent Therapies", 604],
  ["Parent-and-Child Training", "Child & Adolescent Therapies", 605],
  ["Parent-Child Relational Therapy", "Family & Couple Therapies", 860],
  ["Parent–Child Interaction Therapy (PCIT)", "Child & Adolescent Therapies", 93],
  ["Peer recovery interventions", "Substance Use Therapies", 541],
  ["Peer Support", "Psychosis & Rehabilitation Therapies", 605],
  ["Peer-led groups", "Group IPT", 125],
  ["Person-centred / Rogerian therapy", "Humanistic & Meaning-Based Therapies", 892],
  ["Phase-Oriented Trauma Therapy", "Trauma Therapies", 892],
  ["Play therapy / play-based therapies", "Child & Adolescent Therapies", 860],
  ["Problem Management Plus / PM+", "Self-Help & Digital Therapies", 381],
  ["Problem-Solving Therapy (PST)", "Foundational & Engagement Therapies", 893],
  ["Process groups", "Group IPT", 349],
  ["Prolonged Exposure (PE)", "Trauma Therapies", 348],
  ["Psychoanalysis", "Personality Disorder Therapies", 348],
  ["Psychodynamic Psychotherapy", "Personality Disorder Therapies", 348],
  ["Psychoeducation", "Foundational & Engagement Therapies", 991],
  ["Psychoeducation for Psychosis", "Psychosis & Rehabilitation Therapies", 732],
  ["Psychoeducational recovery groups", "Group IPT", 413],
  ["Psychosis-specific self-management programmes", "Psychosis & Rehabilitation Therapies", 95],
  ["Psychosocial case planning", "Community & Casework Support", 799],
  ["Recovery groups", "Group IPT", 29],
  ["Recovery planning for addiction", "Substance Use Therapies", 351],
  ["Recovery-oriented case management", "Community & Casework Support", 797],
  ["Recovery-Oriented Psychosocial Interventions", "Psychosis & Rehabilitation Therapies", 607],
  ["Relapse Prevention Therapy for Substance Use Disorders", "Substance Use Therapies", 605],
  ["Relapse-Prevention Psychotherapy", "Foundational & Engagement Therapies", 349],
  ["Relational psychodynamic therapies", "Personality Disorder Therapies", 348],
  ["Relational-cultural therapy", "Humanistic & Meaning-Based Therapies", 380],
  ["Relationship-focused therapy", "Family & Couple Therapies", 348],
  ["Resource-linkage / coordination as therapeutic intervention", "Community & Casework Support", 797],
  ["rTMS", "Brain & Body Therapies", 605],
  ["Schema Therapy", "Personality Disorder Therapies", 348],
  ["School-refusal CBT", "Child & Adolescent Therapies", 348],
  ["Seeking Safety", "Trauma Therapies", 892],
  ["Self-Management Interventions", "Foundational & Engagement Therapies", 349],
  ["Short-Term Psychodynamic Psychotherapy (STPP)", "Personality Disorder Therapies", 348],
  ["Short-Term Psychodynamic Psychotherapy for Depression (STPP)", "Standard Talking Therapies", 348],
  ["Skills-training groups", "Group IPT", 863],
  ["Sleep Compression Therapy for Insomnia", "Brain & Body Therapies", 92],
  ["Social Cognition Training", "Psychosis & Rehabilitation Therapies", 93],
  ["Social Skills Training (SST)", "Psychosis & Rehabilitation Therapies", 607],
  ["Social-anxiety-focused CBT", "Standard Talking Therapies", 860],
  ["Social-Communication / Parent-Mediated Autism Interventions", "Child & Adolescent Therapies", 541],
  ["Social-role restoration work", "Community & Casework Support", 797],
  ["Solution-focused brief therapy", "Community & Casework Support", 381],
  ["Specialist Supportive Clinical Management (SSCM)", "Eating Disorder Therapies", 606],
  ["Stabilisation-focused trauma preparation", "Trauma Therapies", 383],
  ["STAIR (Skills Training in Affective and Interpersonal Regulation)", "Trauma Therapies", 382],
  ["Strengths-based case management", "Community & Casework Support", 543],
  ["Strengths-based practice", "Community & Casework Support", 287],
  ["Structured clinical management", "Personality Disorder Therapies", 351],
  ["Support groups", "Group IPT", 285],
  ["Supported digital CBT", "Self-Help & Digital Therapies", 348],
  ["Supported digital trauma-focused CBT", "Trauma Therapies", 380],
  ["Supported digital trauma-focused CBT (Self-Help & Digital Therapies)", "Self-Help & Digital Therapies", 348],
  ["Supported education", "Psychosis & Rehabilitation Therapies", 349],
  ["Supported Employment / Individual Placement and Support (IPS)", "Psychosis & Rehabilitation Therapies", 604],
  ["Supportive Psychotherapy", "Foundational & Engagement Therapies", 863],
  ["Supportive-Expressive / Psychodynamic Counselling Approaches for Depression", "Standard Talking Therapies", 349],
  ["Systemic Family Therapy", "Family & Couple Therapies", 540],
  ["Task-centred practice", "Community & Casework Support", 285],
  ["Telehealth-delivered psychotherapy", "Self-Help & Digital Therapies", 828],
  ["Telephone-delivered CBT", "Self-Help & Digital Therapies", 348],
  ["Transference-Focused Psychotherapy (TFP)", "Personality Disorder Therapies", 351],
  ["Trauma-Focused Cognitive Behavioural Therapy (TF-CBT)", "Trauma Therapies", 381],
  ["Trauma-Informed Skills Work", "Trauma Therapies", 892],
  ["Twelve-Step Facilitation (TSF)", "Substance Use Therapies", 605],
  ["Values-based therapies", "Humanistic & Meaning-Based Therapies", 380],
  ["Vocational Rehabilitation", "Psychosis & Rehabilitation Therapies", 605],
  ["Waitlist-bridging brief interventions", "Self-Help & Digital Therapies", 604],
  ["Wake therapy / sleep-deprivation chronotherapy", "Brain & Body Therapies", 95],
  ["Workbook-based therapy", "Self-Help & Digital Therapies", 476],
  ["Worry-focused CBT", "Standard Talking Therapies", 380],
  ["Written exposure therapy", "Trauma Therapies", 350],
  ["Youth IPT / IPT-A", "Child & Adolescent Therapies", 348],
  ["Youth trauma-focused CBT", "Child & Adolescent Therapies", 383],
];
