// Generates the crisis-line and Act-deadline "pocket pack" shown on the offline
// page, from two single sources:
//
//   - WA_CRISIS_CONTACTS (src/lib/crisis-contacts.ts) — always included.
//   - data/mha-timeframes.json — only entries the app itself treats as signed
//     off (isReviewedTimeframe in src/lib/mha-timeline.ts: status "reviewed", a
//     named reviewer, a UTC sign-off time and a reviewedContentSha256 pin that
//     still matches the entry). The owner signs those off from their own
//     computer; this script never marks anything reviewed itself. A signed-off
//     entry the app never calculates (computeAllowed: false) still shows here,
//     as a quote only — this page never shows a calculated time. When the file
//     is absent, the Act section is simply omitted.
//
// Run:
//   node scripts/run-tsx.mjs scripts/build-offline-pack.ts          # write
//   node scripts/run-tsx.mjs scripts/build-offline-pack.ts --check  # verify (CI)
//
// Only the region between the offline-pack sentinels in public/offline.html is
// generated; the rest of the page — including the brand mark, generated
// separately by scripts/generate-brand-assets.ts — is hand-written.
//
// Editing public/offline.html, including by running this script, requires a new
// unique CACHE_VERSION in public/sw.js and a new recorded hash in
// tests/pwa-manifest.test.ts, exactly as scripts/generate-brand-assets.ts
// documents. That pairing guard fails loudly, which is the intended coupling.
//
// Owner decision (approved 2026-09-25), recorded in docs/pwa.md: "The offline
// page may hold only public, non-patient information: WA crisis numbers and Act
// deadlines the owner has signed off, shown as quotes. Each item shows its
// source and the date it was checked. Nothing else is stored on the device: no
// searches, answers, documents or patient data."
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { format, resolveConfig } from "prettier";

import { WA_CRISIS_CONTACTS, type PublicCrisisContact } from "@/lib/crisis-contacts";
import { isReviewedTimeframe, type MhaTimeframeEntry } from "@/lib/mha-timeline";

export const OFFLINE_PAGE_PATH = "public/offline.html";
export const DEFAULT_TIMEFRAMES_PATH = "data/mha-timeframes.json";

export const PACK_START = "<!-- offline-pack:start (generated by scripts/build-offline-pack.ts) -->";
export const PACK_END = "<!-- offline-pack:end -->";

/**
 * A loosely-typed read of a `data/mha-timeframes.json` entry. Which entries count
 * as signed off is decided by `isReviewedTimeframe` from `src/lib/mha-timeline.ts`
 * — the same rule the form page uses — so this pack can never show an entry the
 * app itself treats as drafted. The full contract (duration arithmetic,
 * source-quote pinning) is checked by that module's own tests.
 */
export interface TimeframeEntryLike {
  id?: unknown;
  section?: unknown;
  quote?: unknown;
  status?: unknown;
  reviewedBy?: unknown;
  reviewedAt?: unknown;
  [key: string]: unknown;
}

export interface ReviewedTimeframeEntry {
  section: string;
  quote: string;
  reviewedAt: string;
  trigger: string | null;
  formCodes: string[];
  condition: string | null;
  leadIn: string | null;
  caveat: { section: string; quote: string } | null;
}

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/**
 * Formats a `YYYY-MM-DD...` date prefix as "20 August 2026", without ever
 * constructing a `Date` object — so the result cannot shift with the runtime's
 * local timezone and stays identical between a write and a `--check` run.
 */
export function formatCheckedDate(dateStr: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateStr);
  if (!match) {
    throw new Error(`build-offline-pack: expected a YYYY-MM-DD date, got ${JSON.stringify(dateStr)}`);
  }
  const [, year, month, day] = match;
  const monthName = MONTH_NAMES[Number(month) - 1];
  if (!monthName) {
    throw new Error(`build-offline-pack: invalid month in date ${JSON.stringify(dateStr)}`);
  }
  return `${Number(day)} ${monthName} ${year}`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function optionalText(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value : null;
}

/**
 * Reads `data/mha-timeframes.json` (or an override path) and returns only the
 * entries the owner has actually signed off, by the app's own rule
 * (`isReviewedTimeframe`): `status: "reviewed"`, a named reviewer, a UTC
 * sign-off time and a content pin that still matches. Everything else (missing
 * file, drafted entries, an incompletely-stamped row, an entry edited after
 * sign-off) is silently excluded — this pack shows only what the owner has approved.
 */
export function loadReviewedTimeframes(path: string): ReviewedTimeframeEntry[] {
  if (!existsSync(path)) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (cause) {
    throw new Error(
      `build-offline-pack: ${path} is not valid JSON: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  }

  const entries =
    parsed && typeof parsed === "object" && Array.isArray((parsed as { entries?: unknown }).entries)
      ? ((parsed as { entries: TimeframeEntryLike[] }).entries as TimeframeEntryLike[])
      : [];

  const reviewed: ReviewedTimeframeEntry[] = [];
  for (const entry of entries) {
    if (!entry || typeof entry !== "object") continue;
    if (!isReviewedTimeframe(entry as unknown as MhaTimeframeEntry)) continue;
    if (typeof entry.section !== "string" || entry.section.length === 0) {
      throw new Error(`build-offline-pack: a reviewed entry in ${path} is missing "section"`);
    }
    if (typeof entry.quote !== "string" || entry.quote.length === 0) {
      throw new Error(`build-offline-pack: a reviewed entry in ${path} is missing "quote"`);
    }
    const caveat = entry.caveat as { section?: unknown; quote?: unknown } | undefined;
    reviewed.push({
      section: entry.section,
      quote: entry.quote,
      reviewedAt: entry.reviewedAt as string,
      trigger: optionalText(entry.trigger),
      formCodes: Array.isArray(entry.formCodes)
        ? entry.formCodes.filter((code): code is string => typeof code === "string" && code.trim().length > 0)
        : [],
      condition: optionalText(entry.condition),
      leadIn: optionalText(entry.leadIn),
      caveat:
        caveat && optionalText(caveat.section) && optionalText(caveat.quote)
          ? { section: caveat.section as string, quote: caveat.quote as string }
          : null,
    });
  }
  return reviewed;
}

function renderCrisisContact(contact: PublicCrisisContact): string {
  const caveat = contact.caveat ? `\n          <p class="crisis-caveat">${escapeHtml(contact.caveat)}</p>` : "";
  return `        <li class="crisis-item">
          <p class="crisis-name">${escapeHtml(contact.name)}</p>
          <a class="crisis-tel" href="tel:${escapeHtml(contact.telephoneUri)}">${escapeHtml(contact.telephoneDisplay)}</a>
          <p class="crisis-availability">${escapeHtml(contact.availability)}</p>${caveat}
          <p class="crisis-checked">
            Checked ${formatCheckedDate(contact.verifiedOn)} &middot;
            <a href="${escapeHtml(contact.sourceUrl)}">Source</a>
          </p>
        </li>`;
}

function renderCrisisSection(contacts: readonly PublicCrisisContact[]): string {
  const items = contacts.map(renderCrisisContact).join("\n");
  return `      <section aria-labelledby="offline-crisis-heading" class="offline-pack-section">
        <h2 id="offline-crisis-heading">Crisis support numbers</h2>
        <ul class="crisis-list">
${items}
        </ul>
      </section>`;
}

function renderTimeframeEntry(entry: ReviewedTimeframeEntry): string {
  const lines: string[] = [];
  if (entry.trigger) lines.push(`            <p class="act-trigger">${escapeHtml(entry.trigger)}</p>`);
  if (entry.formCodes.length > 0) {
    const label = entry.formCodes.length === 1 ? "Form" : "Forms";
    lines.push(`            <p class="act-forms">${label} ${entry.formCodes.map(escapeHtml).join(", ")}</p>`);
  }
  if (entry.condition) lines.push(`            <p class="act-condition">${escapeHtml(entry.condition)}</p>`);
  const quoteText = entry.leadIn
    ? `${escapeHtml(entry.leadIn)} &hellip; ${escapeHtml(entry.quote)}`
    : escapeHtml(entry.quote);
  lines.push(`            <blockquote class="act-quote">&ldquo;${quoteText}&rdquo;</blockquote>`);
  if (entry.caveat) {
    lines.push(
      `            <p class="act-caveat">The Act also says (s ${escapeHtml(entry.caveat.section)}): &ldquo;${escapeHtml(entry.caveat.quote)}&rdquo;</p>`,
    );
  }
  lines.push(
    `            <p class="act-meta">Section ${escapeHtml(entry.section)} &middot; Signed off ${formatCheckedDate(entry.reviewedAt)}</p>`,
  );
  return `          <li class="act-item">
${lines.join("\n")}
          </li>`;
}

function renderActSection(entries: readonly ReviewedTimeframeEntry[]): string {
  if (entries.length === 0) return "";
  const items = entries.map(renderTimeframeEntry).join("\n");
  return `\n      <section aria-labelledby="offline-act-heading" class="offline-pack-section">
        <h2 id="offline-act-heading">Mental Health Act deadlines</h2>
        <p class="pack-caution">Reference only — check against the Act and your service's procedure.</p>
        <ul class="act-list">
${items}
        </ul>
      </section>`;
}

/**
 * Builds the unformatted markup for the region between the offline-pack
 * sentinels, from `WA_CRISIS_CONTACTS` plus whichever timeframes at
 * `timeframesPath` are reviewed. Pure aside from the timeframes file read, so
 * it is what tests exercise directly.
 */
export function buildOfflinePackMarkup(timeframesPath: string): string {
  const reviewed = loadReviewedTimeframes(timeframesPath);
  return `${renderCrisisSection(WA_CRISIS_CONTACTS)}${renderActSection(reviewed)}`;
}

/**
 * Replaces the region between the offline-pack sentinels in `currentHtml` with
 * `markup`, leaving the rest of the document untouched. Throws if the
 * sentinels are missing so a stripped-out marker fails loudly instead of
 * silently no-op'ing.
 */
export function applyOfflinePackMarkup(currentHtml: string, markup: string): string {
  const start = currentHtml.indexOf(PACK_START);
  const end = currentHtml.indexOf(PACK_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `public/offline.html has lost its offline-pack sentinels. Restore both of these, on their own lines: ${PACK_START} … ${PACK_END}`,
    );
  }
  const before = currentHtml.slice(0, start + PACK_START.length);
  const after = currentHtml.slice(end);
  return `${before}\n${markup}\n${after}`;
}

async function main() {
  const check = process.argv.includes("--check");
  const timeframesPath = resolve(process.cwd(), DEFAULT_TIMEFRAMES_PATH);
  const pagePath = resolve(process.cwd(), OFFLINE_PAGE_PATH);

  let actual: string;
  try {
    actual = readFileSync(pagePath, "utf8");
  } catch {
    console.error(`✗ offline-pack: ${OFFLINE_PAGE_PATH} is missing.`);
    process.exit(1);
    return;
  }

  let expected: string;
  try {
    expected = applyOfflinePackMarkup(actual, buildOfflinePackMarkup(timeframesPath));
  } catch (cause) {
    console.error(`✗ offline-pack: ${cause instanceof Error ? cause.message : cause}`);
    process.exit(1);
    return;
  }

  const options = await resolveConfig(pagePath);
  expected = await format(expected, { ...options, filepath: pagePath, parser: "html" });

  if (!check) {
    if (actual !== expected) {
      writeFileSync(pagePath, expected);
      console.log(`✓ offline-pack: wrote ${OFFLINE_PAGE_PATH} from WA_CRISIS_CONTACTS and reviewed timeframes.`);
    } else {
      console.log(`✓ offline-pack: ${OFFLINE_PAGE_PATH} already matches its sources.`);
    }
    return;
  }

  if (actual !== expected) {
    console.error(`✗ offline-pack: ${OFFLINE_PAGE_PATH} is out of sync. Run: npm run offline:build`);
    console.error("  If the page content changed, also bump CACHE_VERSION in public/sw.js");
    console.error("  and record the new offline.html hash in tests/pwa-manifest.test.ts.");
    process.exit(1);
    return;
  }
  console.log(`✓ offline-pack: ${OFFLINE_PAGE_PATH} matches WA_CRISIS_CONTACTS and reviewed timeframes.`);
}

// Guarded so unit tests can import the pure functions above without executing the CLI.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((cause) => {
    console.error(cause);
    process.exit(1);
  });
}
