import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import formsContentReview from "../data/forms-content-review.json";
import mhaSections from "../data/mha-2014-sections.json";
import { loadFormCatalogDetails, officialFormsRegisterUrl } from "../src/lib/form-catalog";

/**
 * forms:review-sheet — regenerates `docs/evidence/forms-operational-guidance-review.md`.
 *
 * Every one of the 54 forms carries operational guidance drafted from the Act and the
 * approved form, and every one is `drafted` in `data/forms-content-review.json` — no
 * clinician has signed any of it off. Sign-off is a reading task, and it was an
 * archaeology task instead: the guidance is spread across a 3000-line catalogue JSON, its
 * stated basis sits in a second file, its governing sections in a third, and the official
 * PDF behind a URL in a fourth.
 *
 * This sheet puts all of it on one line of sight per form, the way
 * `scripts/build-mha-act-sections.mjs --draft` already does for the Act summaries: what
 * the app displays, what it was drafted from, and the link to the approved form to check
 * it against. A reviewer signs one form off by setting `status` to `reviewed` with
 * `reviewedBy` and `reviewedAt` in `data/forms-content-review.json`. The caveat in the UI
 * drops for that form and stays up for the rest.
 *
 * Fully offline. Generated, never hand-edited.
 *
 * Flags:
 *   --check   exit 1 if the sheet is stale, writing nothing
 */

const repoUrl = (relative: string) => fileURLToPath(new URL(`../${relative}`, import.meta.url));
const OUT = "docs/evidence/forms-operational-guidance-review.md";

type ReviewRow = {
  code: string;
  status: string;
  sections: string[];
  contextualSections: string[];
  basis: string;
  reviewedBy: string | null;
  reviewedAt: string | null;
};

const reviewByCode = new Map(
  (formsContentReview as { forms: ReviewRow[] }).forms.map(
    (entry) => [entry.code.trim().toLowerCase(), entry] as const,
  ),
);
const sectionTitle = new Map(
  (mhaSections as { sections: { section: string; title: string }[] }).sections.map(
    (entry) => [entry.section, entry.title] as const,
  ),
);

function field(label: string, value: string | undefined) {
  const text = (value ?? "").trim();
  return text ? [`**${label}**`, "", text, ""] : [];
}

function list(label: string, values: readonly string[] | undefined) {
  if (!values?.length) return [];
  return [`**${label}**`, "", ...values.map((value) => `- ${value.trim()}`), ""];
}

function sectionLine(numbers: string[], label: string) {
  if (!numbers.length) return [];
  const rendered = numbers.map((number) => {
    const title = sectionTitle.get(number);
    return title ? `s ${number} (${title})` : `s ${number}`;
  });
  return [`**${label}** ${rendered.join("; ")}`, ""];
}

export function buildSheet() {
  const details = loadFormCatalogDetails();
  const drafted = details.filter((entry) => entry.contentReviewStatus !== "reviewed").length;

  const lines: string[] = [
    "# WA MHA 2014 forms — operational guidance review sheet",
    "",
    "<!-- Generated by scripts/build-forms-content-review-sheet.ts. Do not hand-edit. -->",
    "",
    `**${drafted} of ${details.length} forms are awaiting clinical review.**`,
    "",
    "Each entry below is what the Forms mode actually displays for that form, together with",
    "the basis it was drafted from and a link to the approved form. None of it carries",
    "clinician sign-off, and the app says so on every form until it does.",
    "",
    "A reviewer signs one form off by checking the guidance against the approved form and the",
    "sections named, then setting `status` to `reviewed` with `reviewedBy` and `reviewedAt`",
    "for that code in `data/forms-content-review.json`. The caveat drops for that form and",
    "stays up for the rest, so this can be done a few forms at a time.",
    "",
    "Highest consequence first is a reasonable order: 3C, 10B, 10E, 11B, 11E, 6C,",
    "12C attachment, 5A, 2. Those are the clocks where a wrong reading changes whether a",
    "person is lawfully detained, restrained or secluded.",
    "",
    `Official register: <${officialFormsRegisterUrl}>`,
    "",
    "---",
    "",
  ];

  for (const form of details) {
    const review = reviewByCode.get(form.form.trim().toLowerCase());
    const status = form.contentReviewStatus === "reviewed" ? "REVIEWED" : "awaiting clinical review";
    lines.push(`### Form ${form.form} — ${form.name}`, "");
    lines.push(
      `**Status** ${status}` +
        (review?.reviewedBy ? ` by ${review.reviewedBy}` : "") +
        (review?.reviewedAt ? ` on ${review.reviewedAt}` : ""),
      "",
    );
    lines.push(
      `**Availability** ${form.availability}` +
        (form.officialPdfUrl ? ` · [approved form PDF](${form.officialPdfUrl})` : " · no published PDF"),
      "",
    );
    lines.push(...sectionLine(review?.sections ?? [], "Operational sections"));
    lines.push(...sectionLine(review?.contextualSections ?? [], "Contextual sections"));
    lines.push(...field("Purpose", form.purpose));
    lines.push(...field("Made by", form.maker));
    lines.push(...field("When it applies", form.threshold));
    lines.push(...field("Clock", form.clock));
    lines.push(...field("Authorises", form.authorises));
    lines.push(...field("Does not authorise", form.doesNotAuthorise));
    lines.push(...list("Authority boundaries", form.boundaries));
    lines.push(...list("Common traps", form.traps));
    lines.push(...list("Pre-use checks", form.preUseChecks));
    lines.push(...field("Safety pearl", form.safetyPearl));
    lines.push(...field("Filing and copies", form.copies));
    lines.push(...field("Drafted from", review?.basis));
    lines.push("---", "");
  }

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

function main() {
  const sheet = buildSheet();
  const path = repoUrl(OUT);
  if (process.argv.includes("--check")) {
    const current = readFileSync(path, "utf8");
    if (current !== sheet) {
      console.error(`${OUT} is stale. Run: npm run forms:review-sheet`);
      process.exit(1);
    }
    console.log(`${OUT} is current.`);
    return;
  }
  writeFileSync(path, sheet);
  console.log(`Wrote ${OUT}.`);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) main();
