import { readFileSync, writeFileSync } from "node:fs";

import { compareDriftSnapshots, type AllowlistEntry, type Finding } from "./check-drift";

/**
 * check:chain-mirror-parity — does the migration chain actually BUILD what
 * supabase/schema.sql describes?
 *
 * CI already proves two adjacent things and neither of them is this one:
 *   `supabase migration up --local`   the chain APPLIES without erroring;
 *   committed vs generated sha256     the drift manifest is not stale.
 * Nothing compares the RESULT of replaying the chain against the mirror. A
 * migration whose function body, policy predicate or index shape diverges from
 * schema.sql therefore passes every pre-merge gate — which is not theoretical:
 * on 2026-09-01 `public.correct_clinical_query_terms(text,real)` diverged that
 * way (migration 20260831100000, PR #2477) and only the post-merge live-drift
 * alarm caught it, red on main.
 *
 * This compares two `public.schema_drift_snapshot()` payloads captured from two
 * databases built the two different ways, and reports the difference.
 *
 *   --chain <file>            snapshot from the database the migration chain built
 *   --mirror <file>           snapshot from a database supabase/schema.sql built
 *   --mirror-manifest <file>  supabase/drift-manifest.json, whose `snapshot` IS
 *                             that mirror side (generated by `npm run drift:manifest`)
 *   --allowlist <file>        default supabase/chain-mirror-allowlist.json
 *   --summary <file>          append a Markdown report (GITHUB_STEP_SUMMARY)
 *   --strict                  exit 1 on any divergence that is not allowlisted
 *   --self-test               offline verification of the comparison wiring
 *
 * KNOWN ASYMMETRY, and the reason this starts report-only rather than blocking.
 * The chain side is the Supabase local emulator's database; the mirror side is
 * `drift:manifest`'s replay into the pinned bare `supabase/postgres` image plus
 * scripts/sql/drift-replay-scaffold.sql. Two different images, so some reported
 * difference will be platform provenance (the storage schema, role ACL arrays)
 * rather than a real chain-vs-mirror divergence. Extensions are deliberately NOT
 * on that list: the live gate waves an extra "live" extension through as
 * platform-provisioned, but here the "live" side is the migration chain, and
 * doing so hid a real one (see SUPPRESSED_EXTENSION_INFO). An image-provisioned
 * extension goes in the allowlist as a reviewed entry instead. Building both
 * sides identically would be better, but a mirror database created inside the
 * emulator does not inherit the `auth` schema that supabase/schema.sql needs for
 * its `references auth.users(id)` columns, and reproducing the emulator's chain
 * inside the bare image means driving 224 migrations by hand rather than through
 * `supabase migration up`. Reusing the manifest replay keeps the mirror side on
 * tooling that is already proven in this job; the asymmetry it costs is what the
 * allowlist is for, and the first real CI run is what measures it.
 *
 * WITHOUT `--strict` this is REPORT-ONLY: it prints every divergence and exits
 * 0. That is deliberate for its first landing — the existing divergences cannot
 * be enumerated offline (see docs/database-drift-detection.md backlog item 10,
 * which already records ~13 chain-vs-mirror keys plus storage buckets that only
 * schema.sql creates), so the honest sequence is: land report-only, read the
 * first real CI run, commit the allowlist that run prints, then add `--strict`.
 *
 * The comparison itself is `compareDriftSnapshots` from check-drift.ts — the
 * same function the live gate uses. Two comparators would eventually disagree
 * about what "different" means, and then one of them would be wrong.
 *
 * `migration_history` is stripped from both sides by construction, not by
 * allowlist: a schema.sql replay has no `supabase_migrations` schema at all, so
 * that category can only ever produce noise here. It stays the live gate's
 * business.
 *
 * This never contacts a database. Both snapshots are captured by the caller.
 */

export type ParityAllowlistEntry = {
  category: string;
  kind: Finding["kind"];
  key: string;
  reason: string;
};

const PARITY_KINDS = new Set(["missing_live", "unexpected_live", "mismatch"]);

/** Categories `schema_drift_snapshot()` reports and this gate compares. */
export const PARITY_CATEGORIES = [
  "extensions",
  "tables",
  "views",
  "functions",
  "indexes",
  "policies",
  "constraints",
  "triggers",
  "storage_buckets",
] as const;

/**
 * Structural validation of one allowlist entry. A malformed entry never matches
 * a finding, so it can never silence one: the divergence stays reported and the
 * entry is called out as stale. Same fail-closed shape as the live gate's
 * `historyEntryProblems`.
 */
export function parityEntryProblems(entry: ParityAllowlistEntry): string[] {
  const problems: string[] = [];
  if (!PARITY_CATEGORIES.includes(entry.category as (typeof PARITY_CATEGORIES)[number])) {
    problems.push(`category must be one of ${PARITY_CATEGORIES.join("|")}`);
  }
  if (!PARITY_KINDS.has(entry.kind)) problems.push(`kind must be one of ${[...PARITY_KINDS].join("|")}`);
  if (typeof entry.key !== "string" || entry.key.trim() === "") problems.push("key is required");
  if (typeof entry.reason !== "string" || entry.reason.trim().length <= 20) {
    problems.push("reason must be a real explanation (> 20 chars)");
  }
  return problems;
}

/**
 * Reduce a snapshot to the parts worth comparing between two builds.
 *
 * `migration_history` / `migration_history_probe` are live-only by design:
 * removing them from both sides keeps `compareDriftSnapshots` from reporting the
 * chain database's (entirely expected) `supabase_migrations` rows as parity
 * findings. `captured_at` goes too — it is a timestamp, it is in no compared
 * category, and the manifest side has already dropped it, so leaving it in would
 * only make the two shapes differ for no reason.
 */
export function comparableSnapshot(snapshot: Record<string, unknown>): Record<string, unknown> {
  const copy = { ...snapshot };
  delete copy.migration_history;
  delete copy.migration_history_probe;
  delete copy.captured_at;
  return copy;
}

/**
 * `compareDriftSnapshots` emits an info line when a snapshot carries no
 * migration-history probe, telling the reader that migration
 * 20260818090000 is not deployed and that a `schema_drift_snapshot` function
 * mismatch is therefore "that pending deploy, not a body regression".
 *
 * True for the live gate. False and actively harmful here: the probe IS applied
 * in the chain database and this script stripped it deliberately, and the
 * sentence coaches the reader to dismiss exactly the class of finding this gate
 * exists to surface. Drop it.
 */
const SUPPRESSED_INFO = /migration-history probe not present in the live snapshot/i;

/**
 * The live gate demotes an extension present only on the "live" side to an info
 * line, because the hosted platform provisions pg_net, pgsodium and friends that
 * a schema.sql replay never creates. That is right there and wrong here: on THIS
 * comparison the "live" side is the migration chain, which is our own code, so
 * the same demotion quietly excuses a genuine divergence.
 *
 * It already does. `20260901033250_enable_staging_privacy_retention_schedules.sql`
 * runs `create extension if not exists pg_cron`, `supabase/schema.sql` never
 * declares it, and a probe of the reused comparator on that pair returned
 * `findings: []` — so even `--strict` would have passed it (Codex review).
 *
 * Extensions the chain builds and the mirror does not describe are therefore
 * re-promoted to `unexpected_live` findings here. The asymmetry this gate really
 * does have — the emulator image provisioning extensions neither side asked for
 * — belongs in `supabase/chain-mirror-allowlist.json`, one reviewed entry at a
 * time, not in a blanket rule that cannot tell the two cases apart.
 */
const SUPPRESSED_EXTENSION_INFO = /^extra live extension \(platform-provisioned\)/i;

function extensionsByName(snapshot: Record<string, unknown>): Set<string> {
  const rows = Array.isArray(snapshot.extensions) ? snapshot.extensions : [];
  return new Set(
    rows
      .map((row) => (row && typeof row === "object" ? String((row as Record<string, unknown>).name ?? "") : ""))
      .filter((name) => name !== ""),
  );
}

/** Extensions the migration chain creates that supabase/schema.sql never declares. */
export function chainOnlyExtensionFindings(mirror: Record<string, unknown>, chain: Record<string, unknown>): Finding[] {
  const described = extensionsByName(mirror);
  return [...extensionsByName(chain)]
    .filter((name) => !described.has(name))
    .sort()
    .map((key) => ({ category: "extensions", kind: "unexpected_live", key }) as Finding);
}

export type ParityResult = {
  findings: Finding[];
  allowed: { entry: ParityAllowlistEntry; finding: Finding }[];
  staleEntries: ParityAllowlistEntry[];
  infos: string[];
};

/**
 * Compare the two builds. `mirror` is the expectation (schema.sql is the
 * committed description of the database) and `chain` is what the migrations
 * actually produced, so a `missing_live` finding reads "schema.sql describes it;
 * the chain never builds it" and `unexpected_live` reads the other way round.
 */
export function compareChainAgainstMirror(
  mirror: Record<string, unknown>,
  chain: Record<string, unknown>,
  allowlist: ParityAllowlistEntry[],
): ParityResult {
  const valid = allowlist.filter((entry) => parityEntryProblems(entry).length === 0);
  const comparison = compareDriftSnapshots(
    comparableSnapshot(mirror),
    comparableSnapshot(chain),
    valid as unknown as AllowlistEntry[],
  );

  // Re-promoted before the allowlist is applied, so a chain-only extension can be
  // excused only by a reviewed entry naming it — never by the blanket platform rule.
  const promotedFindings: Finding[] = [];
  const promotedAllowed: { entry: ParityAllowlistEntry; finding: Finding }[] = [];
  for (const finding of chainOnlyExtensionFindings(mirror, chain)) {
    const entry = valid.find(
      (candidate) =>
        candidate.category === finding.category && candidate.kind === finding.kind && candidate.key === finding.key,
    );
    if (entry) promotedAllowed.push({ entry, finding });
    else promotedFindings.push(finding);
  }

  const allowed = [
    ...comparison.allowed.map(({ entry, finding }) => ({
      entry: entry as unknown as ParityAllowlistEntry,
      finding,
    })),
    ...promotedAllowed,
  ];
  const usedKeys = new Set(allowed.map(({ finding }) => `${finding.category}|${finding.kind}|${finding.key}`));
  return {
    findings: [...comparison.findings, ...promotedFindings],
    allowed,
    staleEntries: allowlist.filter((entry) => !usedKeys.has(`${entry.category}|${entry.kind}|${entry.key}`)),
    infos: comparison.infos.filter((info) => !SUPPRESSED_INFO.test(info) && !SUPPRESSED_EXTENSION_INFO.test(info)),
  };
}

export function formatReport(result: ParityResult, strict: boolean): string {
  const lines: string[] = ["## Migration chain vs supabase/schema.sql", ""];
  if (result.infos.length > 0) {
    for (const info of result.infos) lines.push(`- info: ${info}`);
    lines.push("");
  }
  if (result.allowed.length > 0) {
    lines.push(`### Allowlisted divergence (${result.allowed.length})`, "");
    for (const { entry, finding } of result.allowed) {
      lines.push(`- \`[${finding.category}] ${finding.kind} ${finding.key}\` — ${entry.reason}`);
    }
    lines.push("");
  }
  if (result.staleEntries.length > 0) {
    lines.push(`### Stale allowlist entries (${result.staleEntries.length}) — remove them`, "");
    for (const entry of result.staleEntries) {
      const problems = parityEntryProblems(entry);
      lines.push(
        `- \`[${entry.category}] ${entry.kind} ${entry.key}\`${problems.length ? ` — invalid: ${problems.join("; ")}` : ""}`,
      );
    }
    lines.push("");
  }
  if (result.findings.length === 0) {
    lines.push("No divergence between the migration chain and supabase/schema.sql.");
    return `${lines.join("\n")}\n`;
  }

  lines.push(`### Divergence (${result.findings.length})`, "");
  for (const finding of result.findings) {
    const direction =
      finding.kind === "missing_live"
        ? "schema.sql describes it, the migration chain never builds it"
        : finding.kind === "unexpected_live"
          ? "the migration chain builds it, schema.sql does not describe it"
          : "both build it, with different definitions";
    lines.push(`- \`[${finding.category}] ${finding.kind} ${finding.key}\` — ${direction}`);
    if (finding.detail) lines.push(`  - \`${finding.detail.slice(0, 400)}\``);
  }
  lines.push("");
  lines.push(
    strict
      ? "These must be reconciled: fix the migration, or update supabase/schema.sql and regenerate the drift manifest (`npm run drift:manifest`)."
      : "REPORT-ONLY: this gate does not fail the build yet. Copy the entries above into " +
          "`supabase/chain-mirror-allowlist.json` with a reason each, or reconcile them, then add `--strict`.",
  );
  return `${lines.join("\n")}\n`;
}

function arg(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index < 0) return undefined;
  const value = process.argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`${flag} requires a value`);
  return value;
}

function readSnapshot(path: string, label: string): Record<string, unknown> {
  const raw = readFileSync(path, "utf8").trim();
  if (raw === "") throw new Error(`${label} snapshot at ${path} is empty — the capture step produced nothing`);
  const parsed = JSON.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${label} snapshot at ${path} is not a schema_drift_snapshot() object`);
  }
  return parsed as Record<string, unknown>;
}

/**
 * The drift manifest's `snapshot` is a schema.sql replay captured by
 * `npm run drift:manifest`, so it IS the mirror side — no second replay needed.
 * Read it defensively: a manifest regenerated from a different schema.sql would
 * compare the wrong thing, and the CI job's own freshness check is what proves
 * it matches (it runs immediately before this).
 */
export function mirrorSnapshotFromManifest(path: string): Record<string, unknown> {
  const manifest = JSON.parse(readFileSync(path, "utf8")) as { snapshot?: unknown; schema_sha256?: unknown };
  const snapshot = manifest.snapshot;
  if (!snapshot || typeof snapshot !== "object" || Array.isArray(snapshot)) {
    throw new Error(`${path} has no usable \`snapshot\` — regenerate it with \`npm run drift:manifest\``);
  }
  return snapshot as Record<string, unknown>;
}

export function selfTest(): void {
  const failures: string[] = [];
  const expect = (condition: boolean, label: string) => {
    if (!condition) failures.push(label);
  };

  const base = {
    captured_at: "2026-09-02T00:00:00Z",
    functions: [{ signature: "public.f()", def_hash: "aaa", acl: [] }],
    tables: [],
    views: [],
    indexes: [],
    policies: [],
    constraints: [],
    triggers: [],
    extensions: [],
    storage_buckets: [],
  };

  // Identical builds diverge in nothing.
  expect(compareChainAgainstMirror(base, { ...base }, []).findings.length === 0, "identical snapshots must be clean");

  // The 2026-09-01 failure class: same function, different body.
  const drifted = { ...base, functions: [{ signature: "public.f()", def_hash: "bbb", acl: [] }] };
  const bodyDiff = compareChainAgainstMirror(base, drifted, []);
  expect(
    bodyDiff.findings.length === 1 && bodyDiff.findings[0].kind === "mismatch",
    "a diverging function body must be reported as a mismatch",
  );

  // schema.sql describes an object the chain never builds.
  const missing = compareChainAgainstMirror(base, { ...base, functions: [] }, []);
  expect(
    missing.findings.length === 1 && missing.findings[0].kind === "missing_live",
    "an object the chain never builds must be reported as missing",
  );

  // The chain builds something schema.sql does not describe.
  const extra = compareChainAgainstMirror({ ...base, functions: [] }, base, []);
  expect(
    extra.findings.length === 1 && extra.findings[0].kind === "unexpected_live",
    "an object only the chain builds must be reported as unexpected",
  );

  // A valid allowlist entry consumes its finding; an invalid one never can.
  const good: ParityAllowlistEntry = {
    category: "functions",
    kind: "mismatch",
    key: "public.f()",
    reason: "known and reviewed divergence with a long enough explanation",
  };
  const allowed = compareChainAgainstMirror(base, drifted, [good]);
  expect(allowed.findings.length === 0 && allowed.allowed.length === 1, "a valid entry must consume its finding");

  const bad: ParityAllowlistEntry = { ...good, reason: "too short" };
  const notAllowed = compareChainAgainstMirror(base, drifted, [bad]);
  expect(
    notAllowed.findings.length === 1 && notAllowed.staleEntries.length === 1,
    "a malformed entry must never silence a finding",
  );

  // The real pg_cron case: the chain creates an extension schema.sql never
  // declares. The reused live comparator demotes this to an info line, so before
  // the fix this pair reported nothing at all and even --strict would have passed.
  const chainOnlyExtension = compareChainAgainstMirror(
    base,
    { ...base, extensions: [{ name: "pg_cron", schema: "pg_catalog" }] },
    [],
  );
  expect(
    chainOnlyExtension.findings.length === 1 &&
      chainOnlyExtension.findings[0].category === "extensions" &&
      chainOnlyExtension.findings[0].kind === "unexpected_live" &&
      chainOnlyExtension.findings[0].key === "pg_cron",
    "an extension only the migration chain creates must be reported, not demoted to an info line",
  );
  expect(
    chainOnlyExtension.infos.every((info) => !/extra live extension/i.test(info)),
    "the demoting info line must not survive alongside the finding it was hiding",
  );

  // An extension genuinely provisioned by the emulator image goes through the
  // parity allowlist, one reviewed entry at a time.
  const allowedExtension = compareChainAgainstMirror(
    base,
    { ...base, extensions: [{ name: "pg_net", schema: "extensions" }] },
    [
      {
        category: "extensions",
        kind: "unexpected_live",
        key: "pg_net",
        reason: "provisioned by the Supabase emulator image, not by any migration in the chain",
      },
    ],
  );
  expect(
    allowedExtension.findings.length === 0 &&
      allowedExtension.allowed.length === 1 &&
      allowedExtension.staleEntries.length === 0,
    "a reviewed extension entry must consume its finding without reading as stale",
  );

  // An extension schema.sql declares and the chain never creates is the other
  // direction, and was already a finding.
  const missingExtension = compareChainAgainstMirror(
    { ...base, extensions: [{ name: "vector", schema: "extensions" }] },
    base,
    [],
  );
  expect(
    missingExtension.findings.length === 1 && missingExtension.findings[0].kind === "missing_live",
    "an extension schema.sql declares but the chain never creates must still be reported",
  );

  // migration_history is stripped rather than allowlisted: the chain database
  // has a supabase_migrations schema and the mirror never does.
  const withHistory = {
    ...base,
    migration_history: [{ version: "20260101000000", name: "x", signal: "null" }],
    migration_history_probe: "ok",
  };
  expect(
    compareChainAgainstMirror(base, withHistory, []).findings.length === 0,
    "history rows must not surface as parity findings",
  );

  if (failures.length > 0) {
    console.error("chain-mirror parity self-test FAILED:");
    for (const failure of failures) console.error(`  - ${failure}`);
    process.exit(1);
  }
  console.log("chain-mirror parity self-test passed.");
}

function main() {
  if (process.argv.includes("--self-test")) {
    selfTest();
    return;
  }

  const chainPath = arg("--chain");
  const mirrorPath = arg("--mirror");
  const mirrorManifestPath = arg("--mirror-manifest");
  if (!chainPath || (!mirrorPath && !mirrorManifestPath)) {
    throw new Error(
      "--chain <file> is required, plus one of --mirror <file> (a schema_drift_snapshot() payload) or " +
        "--mirror-manifest <file> (supabase/drift-manifest.json)",
    );
  }
  const allowlistPath = arg("--allowlist") ?? "supabase/chain-mirror-allowlist.json";
  const strict = process.argv.includes("--strict");

  const chain = readSnapshot(chainPath, "migration-chain");
  const mirror = mirrorPath
    ? readSnapshot(mirrorPath, "schema.sql mirror")
    : mirrorSnapshotFromManifest(mirrorManifestPath!);
  const allowlistFile = JSON.parse(readFileSync(allowlistPath, "utf8")) as { entries?: ParityAllowlistEntry[] };
  const result = compareChainAgainstMirror(mirror, chain, allowlistFile.entries ?? []);

  const report = formatReport(result, strict);
  console.log(report);
  const summaryPath = arg("--summary") ?? process.env.GITHUB_STEP_SUMMARY;
  if (summaryPath) writeFileSync(summaryPath, report, { flag: "a" });

  // A job summary nobody is required to open is not a signal. While the gate is
  // report-only the annotation IS the output — without it, "the gate found
  // thirteen divergences" and "the gate has been silently crashing for a month"
  // look identical from the checks list.
  if (result.findings.length > 0) {
    console.log(
      `::warning::chain/mirror parity: ${result.findings.length} divergence(s) between the migration chain and ` +
        `supabase/schema.sql — see this job's summary${strict ? "" : " (report-only, not blocking the merge)"}.`,
    );
  }

  if (result.findings.length > 0 && strict) process.exitCode = 1;
}

const invokedDirectly = process.argv[1] && /check-chain-mirror-parity\.(ts|mts|js)$/.test(process.argv[1]);
if (invokedDirectly) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
