import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { loadEnvConfig } from "@next/env";

loadEnvConfig(process.cwd());

/**
 * check:drift — compares the live database's full schema inventory against the
 * committed expectation derived from supabase/schema.sql.
 *
 * Expected side: supabase/drift-manifest.json, generated by replaying
 * supabase/schema.sql into a scratch Supabase Postgres container
 * (`npm run drift:manifest`). The manifest embeds the sha256 of the schema.sql
 * it was generated from, so a stale manifest fails fast here (and offline in
 * tests/drift-detection.test.ts) instead of producing phantom drift.
 *
 * Live side: public.schema_drift_snapshot() (v1 migration
 * 20260706200000_schema_drift_snapshot.sql, v2 20260818090000 — see
 * HISTORY_PROBE_MIGRATION below), a service-role-only RPC returning the same
 * normalized inventory the manifest holds.
 *
 * Known, documented divergence is carried in supabase/drift-allowlist.json —
 * every entry needs a reason and is reported as a warning, never silently
 * dropped. Anything not allowlisted exits 1. See docs/database-drift-detection.md.
 *
 * Migration-history probe (snapshot v2, migration 20260818090000): the live
 * snapshot also carries `migration_history` — every
 * supabase_migrations.schema_migrations version whose `statements` is NULL or
 * empty, i.e. a history repair / mark-applied row whose DDL the CLI never
 * executed. That category is never compared manifest-vs-live (the replay
 * container has no history table); each live row is a finding unless a
 * reviewed `migration_history` allowlist entry points at a real guard
 * migration (see docs/database-drift-detection.md "Guard-migration contract").
 */

type SnapshotObject = Record<string, unknown>;
type Snapshot = Record<string, unknown>;

export const HISTORY_PROBE_MIGRATION = "20260818090000_schema_drift_snapshot_history_probe.sql";
/** Versions at or after this date must use the `validation` guard class. */
export const GUARD_CONTRACT_VERSION = "20260818000000";
export const HISTORY_GUARD_CLASSES = ["validation", "superseded", "no_ddl"] as const;
export type HistoryGuardClass = (typeof HISTORY_GUARD_CLASSES)[number];

export type HistoryGuard = {
  class: HistoryGuardClass;
  migration: string;
  objects?: string[];
};

export type AllowlistEntry = {
  category: string;
  kind: "missing_live" | "unexpected_live" | "mismatch" | "alias" | "no_statements";
  key: string;
  live_key?: string;
  reason: string;
  guard?: HistoryGuard;
};

export type Finding = {
  category: string;
  kind: "missing_live" | "unexpected_live" | "mismatch" | "no_statements";
  key: string;
  detail?: string;
};

type MigrationHistoryRow = { version: string; name?: string; signal?: string };

const read = (relative: string) => readFileSync(new URL(`../${relative}`, import.meta.url), "utf8");
const migrationExists = (fileName: string) =>
  existsSync(new URL(`../supabase/migrations/${fileName}`, import.meta.url));

const MIGRATION_FILE = /^(\d{14})_.+\.sql$/;

/**
 * Structural validation of a `migration_history` allowlist entry. A malformed
 * entry never matches a finding, so it can never silence a history row: the
 * row stays an unexpected finding and the entry is reported as stale.
 * Object-level checks (does the guard file really validate the named objects)
 * live in tests/migration-history-guards.test.ts.
 */
export function historyEntryProblems(
  entry: AllowlistEntry,
  options: { migrationExists?: (fileName: string) => boolean } = {},
): string[] {
  const exists = options.migrationExists ?? migrationExists;
  const problems: string[] = [];
  if (entry.category !== "migration_history") problems.push("category must be migration_history");
  if (entry.kind !== "no_statements") problems.push("kind must be no_statements");
  if (!/^\d{14}$/.test(entry.key)) problems.push("key must be a 14-digit migration version");
  if (typeof entry.reason !== "string" || entry.reason.trim().length <= 20) {
    problems.push("reason must be a real explanation (> 20 chars)");
  }
  const guard = entry.guard;
  if (!guard || typeof guard !== "object") {
    problems.push("guard is required");
    return problems;
  }
  if (!HISTORY_GUARD_CLASSES.includes(guard.class)) {
    problems.push(`guard.class must be one of ${HISTORY_GUARD_CLASSES.join("|")}`);
  }
  const fileMatch = typeof guard.migration === "string" ? guard.migration.match(MIGRATION_FILE) : null;
  if (!fileMatch) {
    problems.push("guard.migration must be a <14-digit version>_<stem>.sql file name");
    return problems;
  }
  if (!exists(guard.migration))
    problems.push(`guard.migration ${guard.migration} does not exist under supabase/migrations/`);
  const guardVersion = fileMatch[1];
  if (guard.class === "no_ddl") {
    if (guardVersion !== entry.key) problems.push("no_ddl guard must be the version's own migration file");
  } else if (!(guardVersion > entry.key)) {
    problems.push(`${guard.class} guard must be a later migration than ${entry.key}`);
  }
  if (guard.class === "validation" && (!Array.isArray(guard.objects) || guard.objects.length === 0)) {
    problems.push("validation guard must list the objects it proves (guard.objects)");
  }
  if (guard.class !== "validation" && entry.key >= GUARD_CONTRACT_VERSION) {
    problems.push(
      `versions from ${GUARD_CONTRACT_VERSION} must use a validation guard (guard-migration contract); ${guard.class} is for pre-contract history only`,
    );
  }
  return problems;
}

export function normalizedSchemaSha256(schemaSqlText: string) {
  return createHash("sha256").update(schemaSqlText.replace(/\r\n/g, "\n")).digest("hex");
}

// category -> unique key extractor. Must stay aligned with the RPC's shape.
const categoryKeys: Record<string, (o: SnapshotObject) => string> = {
  extensions: (o) => String(o.name),
  tables: (o) => String(o.name),
  views: (o) => String(o.name),
  functions: (o) => String(o.signature),
  indexes: (o) => String(o.name),
  policies: (o) => `${o.schema}.${o.table}.${o.name}`,
  constraints: (o) => `${o.table}.${o.name}`,
  triggers: (o) => `${o.table}.${o.name}`,
  storage_buckets: (o) => String(o.id),
};

// Fields that identify content per category (compared as canonical JSON).
const comparedFields: Record<string, string[]> = {
  extensions: ["schema"],
  tables: ["rls_enabled", "rls_forced", "reloptions", "acl", "columns"],
  views: ["def_hash"],
  functions: ["def_hash", "acl"],
  indexes: ["table", "def_hash"],
  policies: ["permissive", "roles", "cmd", "qual", "with_check"],
  constraints: ["def"],
  triggers: ["def"],
  storage_buckets: ["public", "file_size_limit", "allowed_mime_types"],
};

function canonical(value: unknown): string {
  return JSON.stringify(value, (_key, v) =>
    v && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(
          Object.keys(v as Record<string, unknown>)
            .sort()
            .map((k) => [k, (v as Record<string, unknown>)[k]]),
        )
      : v,
  );
}

function indexObjects(category: string, snapshot: Snapshot): Map<string, SnapshotObject> {
  const list = snapshot[category];
  const keyOf = categoryKeys[category];
  const map = new Map<string, SnapshotObject>();
  if (!Array.isArray(list)) return map;
  for (const raw of list) {
    if (raw && typeof raw === "object") {
      const o = raw as SnapshotObject;
      map.set(keyOf(o), o);
    }
  }
  return map;
}

function contentOf(category: string, o: SnapshotObject): string {
  return canonical(Object.fromEntries(comparedFields[category].map((f) => [f, o[f] ?? null])));
}

function fieldDiff(category: string, expected: SnapshotObject, actual: SnapshotObject): string {
  const parts: string[] = [];
  for (const field of comparedFields[category]) {
    const e = canonical(expected[field] ?? null);
    const a = canonical(actual[field] ?? null);
    if (e !== a) {
      const clip = (s: string) => (s.length > 240 ? `${s.slice(0, 240)}…` : s);
      parts.push(`${field}: manifest=${clip(e)} live=${clip(a)}`);
    }
  }
  return parts.join("; ");
}

export type DriftComparison = {
  findings: Finding[];
  allowed: { entry: AllowlistEntry; finding: Finding }[];
  staleEntries: AllowlistEntry[];
  infos: string[];
};

export function compareDriftSnapshots(
  expected: Snapshot,
  live: Snapshot,
  allowlist: AllowlistEntry[],
  options: { historyEntryProblems?: (entry: AllowlistEntry) => string[] } = {},
): DriftComparison {
  const findings: Finding[] = [];
  const infos: string[] = [];

  for (const category of Object.keys(categoryKeys)) {
    const expectedMap = indexObjects(category, expected);
    const liveMap = indexObjects(category, live);

    for (const [key, expectedObject] of expectedMap) {
      const liveObject = liveMap.get(key);
      if (!liveObject) {
        findings.push({ category, kind: "missing_live", key, detail: contentOf(category, expectedObject) });
        continue;
      }
      if (contentOf(category, expectedObject) !== contentOf(category, liveObject)) {
        findings.push({ category, kind: "mismatch", key, detail: fieldDiff(category, expectedObject, liveObject) });
      }
    }

    for (const key of liveMap.keys()) {
      if (expectedMap.has(key)) continue;
      // Hosted platform provisions extensions (pg_net, pgsodium, …) that a
      // schema.sql replay never creates; extra live extensions are informational.
      if (category === "extensions") {
        infos.push(`extra live extension (platform-provisioned): ${key}`);
        continue;
      }
      findings.push({ category, kind: "unexpected_live", key });
    }
  }

  // Migration-history probe (snapshot v2). Never compared manifest-vs-live —
  // the manifest replay has no supabase_migrations schema — so every live row
  // recorded without executed statements is a finding unless a validated
  // `migration_history` allowlist entry covers it.
  const historyRows = live.migration_history;
  if (historyRows === undefined) {
    infos.push(
      `migration-history probe not present in the live snapshot — migration ${HISTORY_PROBE_MIGRATION} is not deployed; ` +
        `the schema_drift_snapshot() function mismatch is that pending deploy, not a body regression`,
    );
  } else if (live.migration_history_probe !== "ok") {
    infos.push(
      `migration-history probe reported '${String(live.migration_history_probe)}' — history rows were not inspected`,
    );
  } else if (Array.isArray(historyRows)) {
    for (const raw of historyRows) {
      if (!raw || typeof raw !== "object") continue;
      const row = raw as MigrationHistoryRow;
      findings.push({
        category: "migration_history",
        kind: "no_statements",
        key: String(row.version),
        detail:
          `${row.name ?? "(unnamed)"} (statements ${row.signal ?? "null"}) — history row recorded without executed DDL; ` +
          `needs a fail-fast guard migration + reviewed allowlist entry`,
      });
    }
  }

  // Apply the allowlist. Alias entries assert the live database carries the
  // same index under a legacy name; they consume both the missing_live finding
  // for the manifest name and the unexpected_live finding for the legacy name.
  const allowed: { entry: AllowlistEntry; finding: Finding }[] = [];
  const remaining: Finding[] = [];
  const usedEntries = new Set<AllowlistEntry>();

  const liveIndexes = indexObjects("indexes", live);
  const expectedIndexes = indexObjects("indexes", expected);

  const matchesAlias = (entry: AllowlistEntry, finding: Finding): boolean => {
    if (entry.category !== "indexes" || finding.category !== "indexes") return false;
    if (finding.kind === "missing_live" && finding.key === entry.key) {
      const manifestIdx = expectedIndexes.get(entry.key);
      const liveIdx = entry.live_key ? liveIndexes.get(entry.live_key) : undefined;
      if (!manifestIdx || !liveIdx) return false;
      const stripName = (o: SnapshotObject) =>
        String(o.def ?? "")
          .split(String(o.name))
          .join("@NAME@")
          .replace(/\s+/g, "");
      return manifestIdx.table === liveIdx.table && stripName(manifestIdx) === stripName(liveIdx);
    }
    return finding.kind === "unexpected_live" && finding.key === entry.live_key;
  };

  // A migration_history entry only counts when it is structurally valid and
  // points at a real guard migration; a malformed entry can never silence a
  // history row (the finding stays and the entry is reported as stale).
  const historyProblems = options.historyEntryProblems ?? historyEntryProblems;
  const matchesHistory = (entry: AllowlistEntry, finding: Finding): boolean =>
    finding.category === "migration_history" &&
    finding.kind === "no_statements" &&
    entry.category === "migration_history" &&
    entry.kind === "no_statements" &&
    entry.key === finding.key &&
    historyProblems(entry).length === 0;

  for (const finding of findings) {
    const entry = allowlist.find((candidate) =>
      finding.category === "migration_history"
        ? matchesHistory(candidate, finding)
        : (candidate.kind === "alias" && matchesAlias(candidate, finding)) ||
          (candidate.kind === finding.kind && candidate.category === finding.category && candidate.key === finding.key),
    );
    if (entry) {
      usedEntries.add(entry);
      allowed.push({ entry, finding });
    } else {
      remaining.push(finding);
    }
  }

  return {
    findings: remaining,
    allowed,
    staleEntries: allowlist.filter((entry) => !usedEntries.has(entry)),
    infos,
  };
}

async function main() {
  const [{ requireServerEnv }, { createAdminClient }, { checkSupabaseProjectConfig, formatSupabaseProjectCheck }] =
    await Promise.all([import("@/lib/env"), import("@/lib/supabase/admin"), import("@/lib/supabase/project")]);

  requireServerEnv();
  const projectCheck = checkSupabaseProjectConfig(
    {
      NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
      SUPABASE_PROJECT_REF: process.env.SUPABASE_PROJECT_REF,
      SUPABASE_PROJECT_NAME: process.env.SUPABASE_PROJECT_NAME,
    },
    { requireMetadata: false },
  );
  if (projectCheck.status === "missing" || projectCheck.status === "mismatch") {
    throw new Error(formatSupabaseProjectCheck(projectCheck));
  }

  const manifestFile = JSON.parse(read("supabase/drift-manifest.json")) as {
    schema_sha256: string;
    generated_at: string;
    postgres_image: string;
    snapshot: Snapshot;
  };
  const allowlistFile = JSON.parse(read("supabase/drift-allowlist.json")) as Record<string, unknown> & {
    entries: AllowlistEntry[];
  };
  const allowlist = allowlistFile.entries ?? [];

  const schemaSha = normalizedSchemaSha256(read("supabase/schema.sql"));
  if (schemaSha !== manifestFile.schema_sha256) {
    throw new Error(
      `supabase/drift-manifest.json is stale: it was generated from a different supabase/schema.sql ` +
        `(manifest ${manifestFile.schema_sha256.slice(0, 12)}…, current ${schemaSha.slice(0, 12)}…). ` +
        `Regenerate with: npm run drift:manifest`,
    );
  }

  const supabase = createAdminClient();
  const { data: liveSnapshot, error } = await supabase.rpc("schema_drift_snapshot" as never);
  if (error) {
    const message = String(error.message ?? error);
    if (/could not find the function|schema cache|PGRST202/i.test(message)) {
      throw new Error(
        `schema_drift_snapshot() is not available on the live project. Apply migration ` +
          `${HISTORY_PROBE_MIGRATION} (or at least the v1 20260706200000_schema_drift_snapshot.sql) through the normal linked migration workflow first. (${message})`,
      );
    }
    throw new Error(`schema_drift_snapshot RPC failed: ${message}`);
  }
  if (!liveSnapshot || typeof liveSnapshot !== "object") {
    throw new Error("schema_drift_snapshot returned an unexpected payload");
  }
  const live = liveSnapshot as Snapshot;
  const expected = manifestFile.snapshot;

  const { findings: remaining, allowed, staleEntries, infos } = compareDriftSnapshots(expected, live, allowlist);

  if (process.argv.includes("--prune-stale") && remaining.length === 0 && staleEntries.length > 0) {
    const staleSet = new Set(staleEntries);
    const nextAllowlist = {
      ...allowlistFile,
      entries: allowlist.filter((entry) => !staleSet.has(entry)),
    };
    writeFileSync(
      new URL("../supabase/drift-allowlist.json", import.meta.url),
      `${JSON.stringify(nextAllowlist, null, 2)}\n`,
      "utf8",
    );
    console.log(`Pruned ${staleEntries.length} stale allowlist entr${staleEntries.length === 1 ? "y" : "ies"}.`);
  }

  console.log(`Drift manifest: generated ${manifestFile.generated_at} from schema.sql ${schemaSha.slice(0, 12)}…`);
  console.log(
    `Compared ${Object.keys(categoryKeys)
      .map((category) => `${indexObjects(category, expected).size} ${category}`)
      .join(", ")} against live.`,
  );
  for (const info of infos) console.log(`  info: ${info}`);
  if (allowed.length > 0) {
    console.log(`\nAllowlisted divergence (${allowed.length}) — known and documented, not failures:`);
    for (const { entry, finding } of allowed) {
      console.log(`  ~ [${finding.category}] ${finding.kind} ${finding.key} — ${entry.reason}`);
    }
  }
  if (staleEntries.length > 0) {
    console.log(`\nStale allowlist entries (${staleEntries.length}) — no longer matching, remove them:`);
    for (const entry of staleEntries) {
      const problems = entry.category === "migration_history" ? historyEntryProblems(entry) : [];
      console.log(
        `  ? [${entry.category}] ${entry.kind} ${entry.key}${problems.length ? ` :: invalid entry — ${problems.join("; ")}` : ""}`,
      );
    }
  }
  if (remaining.length > 0) {
    console.error(`\nUNEXPECTED DRIFT (${remaining.length}):`);
    for (const finding of remaining) {
      console.error(
        `  ! [${finding.category}] ${finding.kind} ${finding.key}${finding.detail ? ` :: ${finding.detail}` : ""}`,
      );
    }
    console.error(
      `\nLive schema diverges from supabase/schema.sql. Either codify the live state ` +
        `(committed migration + schema.sql + regenerate the manifest) or fix live through ` +
        `an approved migration. Raw SQL against live is how this class of incident started; ` +
        `do not \"fix\" drift that way. See docs/database-drift-detection.md.`,
    );
    process.exitCode = 1;
    return;
  }

  console.log(`\nNo unexpected schema drift between live and supabase/schema.sql.`);
  if (staleEntries.length > 0) {
    console.log("(Clean up the stale allowlist entries above in a follow-up commit.)");
  }
}

const invokedDirectly = process.argv[1] && /check-drift\.(ts|mts|js)$/.test(process.argv[1]);
if (invokedDirectly) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
