// Generates static brand assets from the single source in src/lib/brand-mark.
// Run:
//   node scripts/run-tsx.mjs scripts/generate-brand-assets.ts          # write
//   node scripts/run-tsx.mjs scripts/generate-brand-assets.ts --check  # verify (CI)
//
// The --check mode is wired into `verify:cheap` so these assets can never drift
// from the brand-mark source (same idea as sitemap:check).
//
// Two targets, for two reasons neither of which is a build step:
//
//   src/app/icon.svg    — the themed browser-tab icon. A whole generated file.
//   public/offline.html — the PWA's offline page. A static, script-free page the
//                         service worker precaches, with no bundler and no access
//                         to the app's stylesheet, so it cannot import <BrandMark>
//                         and its mark has to be inlined. Only the region between
//                         the brand-mark sentinels is generated; the rest of the
//                         page is hand-written.
//
// The HTML target is run through Prettier before comparison. Prettier also checks
// public/offline.html in CI, so generating an unformatted copy would leave this
// gate and the formatter permanently disagreeing — and the loser would be whoever
// next tried to make both green at once.
//
// Editing public/offline.html — including by running this script — requires a new
// unique CACHE_VERSION in public/sw.js and a new recorded hash in
// tests/pwa-manifest.test.ts, or installed clients keep the old copy forever.
// That pairing guard fails loudly, which is the intended coupling.
//
// NOTE: src/app/favicon.ico is a multi-resolution binary and cannot be emitted
// here — the toolchain has no rasteriser. Regenerate it offline from icon.svg
// when the mark changes; see docs/design-system.md.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { format, resolveConfig } from "prettier";

import { BRAND_VIEWBOX, brandBareMarkInner, brandIconSvg } from "@/lib/brand-mark";

const check = process.argv.includes("--check");

const OFFLINE_MARK_START = "<!-- brand-mark:start (generated by scripts/generate-brand-assets.ts) -->";
const OFFLINE_MARK_END = "<!-- brand-mark:end -->";

/**
 * The offline page's mark: the bare glyph, inked with `currentColor` so the page
 * themes it through `.mark { color }` from its own mirrored tokens. Emitted
 * unformatted — Prettier lays the element out below.
 */
function offlineMarkMarkup(): string {
  const inner = brandBareMarkInner("currentColor");
  return (
    `<svg class="mark" viewBox="${BRAND_VIEWBOX}" xmlns="http://www.w3.org/2000/svg" ` +
    `aria-hidden="true" focusable="false">${inner}</svg>`
  );
}

type Target = {
  /** Path relative to the repository root. */
  path: string;
  /** The whole expected file, given what is on disk now. */
  expected: (actual: string) => string;
  /** Prettier parser to normalise the result with, when Prettier handles this format. */
  parser?: "html";
};

const targets: Target[] = [
  { path: "src/app/icon.svg", expected: () => brandIconSvg() },
  {
    path: "public/offline.html",
    parser: "html",
    expected: (actual) => {
      const start = actual.indexOf(OFFLINE_MARK_START);
      const end = actual.indexOf(OFFLINE_MARK_END);
      if (start === -1 || end === -1 || end < start) {
        throw new Error(
          "public/offline.html has lost its brand-mark sentinels. Restore both of these, on their own lines, " +
            `around the mark: ${OFFLINE_MARK_START} … ${OFFLINE_MARK_END}`,
        );
      }
      const before = actual.slice(0, start + OFFLINE_MARK_START.length);
      const after = actual.slice(end);
      return `${before}\n${offlineMarkMarkup()}\n${after}`;
    },
  },
];

async function main() {
  let failed = false;

  for (const target of targets) {
    const path = resolve(process.cwd(), target.path);
    let actual: string;
    try {
      actual = readFileSync(path, "utf8");
    } catch {
      console.error(`✗ brand: ${target.path} is missing. Run: npm run brand:update`);
      process.exit(1);
    }

    let expected: string;
    try {
      expected = target.expected(actual);
    } catch (cause) {
      console.error(`✗ brand: ${cause instanceof Error ? cause.message : cause}`);
      process.exit(1);
    }

    if (target.parser) {
      const options = await resolveConfig(path);
      expected = await format(expected, { ...options, filepath: path, parser: target.parser });
    }

    if (!check) {
      if (actual !== expected) {
        writeFileSync(path, expected);
        console.log(`✓ brand: wrote ${target.path} from the brand-mark source.`);
      } else {
        console.log(`✓ brand: ${target.path} already matches the brand-mark source.`);
      }
      continue;
    }

    if (actual !== expected) {
      console.error(`✗ brand: ${target.path} is out of sync with src/lib/brand-mark. Run: npm run brand:update`);
      failed = true;
    } else {
      console.log(`✓ brand: ${target.path} matches the brand-mark source.`);
    }
  }

  if (failed) {
    // Deliberately named here: regenerating offline.html without the pairing bump
    // leaves installed clients on the old page forever.
    console.error("✗ brand: if public/offline.html changed, also bump CACHE_VERSION in public/sw.js");
    console.error("  and record the new offline.html hash in tests/pwa-manifest.test.ts.");
    process.exit(1);
  }
}

main().catch((cause) => {
  console.error(cause);
  process.exit(1);
});
