#!/usr/bin/env bash

set -Eeuo pipefail

fail() {
  printf '[codex-cloud:shims] ERROR: %s\n' "$*" >&2
  exit 1
}

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || fail "Run this script from the Database repository."
cd "$repo_root"

expected_node_major="$(tr -cd '0-9' < .node-version)"
[[ -n "$expected_node_major" ]] || fail "Could not read the Node major from .node-version."

runtime_profile="$HOME/.clinical-kb-codex-cloud.sh"
[[ -f "$runtime_profile" ]] || fail "The generated Cloud runtime profile is unavailable; run setup first."

# shellcheck source=/dev/null
source "$runtime_profile"
command -v nvm >/dev/null 2>&1 || fail "nvm is unavailable after loading the Cloud runtime profile."

node_bin="$(dirname "$(nvm which "$expected_node_major")")"
mkdir -p "$HOME/.local/bin"
for command_name in node npm npx; do
  [[ -x "$node_bin/$command_name" ]] || fail "${command_name} is unavailable in Node ${expected_node_major}."
  cat > "$HOME/.local/bin/$command_name" <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
# Generated by scripts/install-codex-cloud-command-shims.sh. Re-running setup
# or maintenance replaces this wrapper through the same idempotent command.
. "$runtime_profile"
exec "$node_bin/$command_name" "\$@"
EOF
  chmod 0755 "$HOME/.local/bin/$command_name"
done

printf '[codex-cloud:shims] PASS: node, npm, and npx load the generated Cloud profile.\n'
