#!/usr/bin/env bash

set -Eeuo pipefail

log() {
  printf '[codex-cloud:setup] %s\n' "$*"
}

fail() {
  printf '[codex-cloud:setup] ERROR: %s\n' "$*" >&2
  exit 1
}

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || fail "Run this script from the Database repository."
cd "$repo_root"

expected_node_major="$(tr -cd '0-9' < .node-version)"
expected_npm_version="$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"npm@\([^"]*\)".*/\1/p' package.json | head -n 1)"

[[ -n "$expected_node_major" ]] || fail "Could not read the Node major from .node-version."
[[ -n "$expected_npm_version" ]] || fail "Could not read the npm version from package.json."

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
current_node_major="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || true)"

if [[ "$current_node_major" != "$expected_node_major" ]]; then
  [[ -s "$NVM_DIR/nvm.sh" ]] || fail "Node ${expected_node_major}.x is required. Select it under Set package versions in the Codex Cloud environment."
  # shellcheck source=/dev/null
  source "$NVM_DIR/nvm.sh"
  log "Installing and selecting Node ${expected_node_major}.x with nvm."
  nvm install "$expected_node_major"
  nvm alias default "$expected_node_major"
  nvm use "$expected_node_major"
fi

current_npm_version="$(npm --version)"
if [[ "$current_npm_version" != "$expected_npm_version" ]]; then
  log "Installing repository npm version ${expected_npm_version}."
  npm install --global "npm@${expected_npm_version}"
  hash -r
fi

runtime_profile="$HOME/.clinical-kb-codex-cloud.sh"
cat > "$runtime_profile" <<EOF
# Generated by scripts/setup-codex-cloud.sh. Re-running setup replaces this file.
export NVM_DIR="\${NVM_DIR:-\$HOME/.nvm}"
if [ -s "\$NVM_DIR/nvm.sh" ]; then
  . "\$NVM_DIR/nvm.sh"
  nvm use --silent ${expected_node_major} >/dev/null 2>&1 || true
fi
export PATH="\$HOME/.local/bin:\$HOME/.deno/bin:\$HOME/.cache/clinical-kb-codex/ocr-venv/bin:\$PATH"
export CODEX_CLOUD=1
export RAG_PROVIDER_MODE=offline
export NEXT_PUBLIC_DEMO_MODE=true
export PLAYWRIGHT_OFFLINE_MODE=true
unset OPENAI_API_KEY OPENAI_ORG_ID OPENAI_PROJECT_ID
unset SUPABASE_ACCESS_TOKEN SUPABASE_SERVICE_ROLE_KEY SUPABASE_DB_URL
unset RAILWAY_API_TOKEN RAILWAY_TOKEN
unset GH_TOKEN GITHUB_TOKEN
EOF

bashrc="$HOME/.bashrc"
touch "$bashrc"
profile_source='[ -f "$HOME/.clinical-kb-codex-cloud.sh" ] && . "$HOME/.clinical-kb-codex-cloud.sh"'
if ! grep -Fq '.clinical-kb-codex-cloud.sh' "$bashrc"; then
  printf '\n# Clinical KB Codex Cloud runtime\n%s\n' "$profile_source" >> "$bashrc"
fi

# Apply the provider-free profile to this setup shell too.
# shellcheck source=/dev/null
source "$runtime_profile"

log "Installing locked Node dependencies."
npm ci --include=dev

if ! command -v deno >/dev/null 2>&1 || [[ "$(deno --version 2>/dev/null | sed -n '1s/^deno \([0-9]*\).*/\1/p')" != "2" ]]; then
  log "Installing the latest Deno 2.x release through npm."
  npm install --global 'deno@2'
  hash -r
fi

if ! command -v tesseract >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    log "Installing the OCR system package."
    if [[ "$(id -u)" -eq 0 ]]; then
      apt-get update
      apt-get install -y --no-install-recommends tesseract-ocr python3-venv
    elif command -v sudo >/dev/null 2>&1; then
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends tesseract-ocr python3-venv
    else
      log "WARNING: no root or sudo access; Tesseract OCR remains unavailable."
    fi
  else
    log "WARNING: apt-get is unavailable; Tesseract OCR remains unavailable."
  fi
fi

python_bin="$(command -v python3 || command -v python || true)"
if [[ -n "$python_bin" ]]; then
  ocr_venv="$HOME/.cache/clinical-kb-codex/ocr-venv"
  if [[ ! -x "$ocr_venv/bin/python" ]]; then
    log "Creating the cached Python OCR environment."
    "$python_bin" -m venv "$ocr_venv"
  fi
  log "Installing locked-compatible Python worker dependencies."
  "$ocr_venv/bin/python" -m pip install --disable-pip-version-check -r worker/python/requirements.txt
else
  log "WARNING: Python is unavailable; worker OCR checks remain unavailable."
fi

if [[ "${CODEX_CLOUD_SKIP_BROWSER_INSTALL:-0}" != "1" ]]; then
  log "Installing the Playwright browser matrix and Linux system dependencies."
  npx playwright install --with-deps chromium firefox webkit
else
  log "Skipping Playwright browser installation because CODEX_CLOUD_SKIP_BROWSER_INSTALL=1."
fi

npm run check:runtime
npm run check:installed-lock-parity
npm run check:codex-cloud -- --runtime

log "Setup complete. Codex agent shells will default to demo/offline mode with provider credentials unset."
