-- Codify the distinct operational indexes already proven in production so
-- scratch replay and drift detection match the live schema.
create index if not exists audit_logs_owner_id_idx on public.audit_logs (owner_id);
create index if not exists clinical_registry_record_sources_owner_id_idx on public.clinical_registry_record_sources (owner_id);
create unique index if not exists differential_records_owner_slug_kind_uidx on public.differential_records (owner_id, slug, kind);
create index if not exists document_chunks_document_id_idx on public.document_chunks (document_id);
create index if not exists document_chunks_meta_rag_indexing_version_idx on public.document_chunks ((metadata ->> 'rag_indexing_version'));
create index if not exists document_embedding_fields_document_generation_idx on public.document_embedding_fields (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_embedding_fields_document_id_idx on public.document_embedding_fields (document_id);
create index if not exists document_images_created_at_idx on public.document_images (created_at);
create index if not exists document_images_document_generation_idx on public.document_images (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_images_document_id_idx on public.document_images (document_id);
create index if not exists document_images_duplicate_group_idx on public.document_images (document_id, visual_duplicate_group);
create index if not exists document_images_priority_idx on public.document_images (document_id, clinical_priority_score desc, page_number);
create index if not exists document_images_searchable_idx1 on public.document_images (searchable);
create index if not exists document_index_quality_document_id_idx on public.document_index_quality (document_id);
create index if not exists document_index_quality_owner_id_idx on public.document_index_quality (owner_id);
create index if not exists document_index_units_document_generation_idx on public.document_index_units (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_index_units_document_id_idx on public.document_index_units (document_id);
create index if not exists document_index_units_owner_document_created_idx on public.document_index_units (owner_id, document_id, created_at desc);
create index if not exists document_index_units_owner_id_idx on public.document_index_units (owner_id);
create index if not exists document_index_units_source_chunk_id_idx on public.document_index_units (source_chunk_id);
create index if not exists document_index_units_source_image_id_idx on public.document_index_units (source_image_id);
create index if not exists document_labels_owner_id_idx on public.document_labels (owner_id);
create index if not exists document_memory_cards_document_generation_idx on public.document_memory_cards (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_memory_cards_document_id_idx on public.document_memory_cards (document_id);
create index if not exists document_memory_cards_owner_document_created_idx on public.document_memory_cards (owner_id, document_id, created_at desc);
create index if not exists document_sections_document_generation_idx on public.document_sections (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_sections_document_id_idx on public.document_sections (document_id);
create index if not exists document_summaries_owner_id_idx on public.document_summaries (owner_id);
create index if not exists document_table_facts_document_generation_idx on public.document_table_facts (document_id, index_generation_id) where index_generation_id is not null;
create index if not exists document_table_facts_document_id_idx on public.document_table_facts (document_id);
create index if not exists document_table_facts_owner_idx on public.document_table_facts (owner_id, page_number);
create index if not exists document_table_facts_title_row_param_trgm_idx on public.document_table_facts using gin (lower(coalesce(table_title, '') || ' ' || coalesce(row_label, '') || ' ' || coalesce(clinical_parameter, '')) extensions.gin_trgm_ops);
create index if not exists documents_indexed_updated_at_idx on public.documents (updated_at, id) where status = 'indexed';
create index if not exists image_caption_cache_owner_id_idx on public.image_caption_cache (owner_id);
create index if not exists import_batches_owner_id_idx on public.import_batches (owner_id);
create index if not exists ingestion_job_stages_job_idx on public.ingestion_job_stages (job_id, started_at desc);
create index if not exists ingestion_jobs_status_idx on public.ingestion_jobs (status);
create index if not exists ingestion_jobs_updated_at_idx on public.ingestion_jobs (updated_at);
create index if not exists rag_queries_owner_id_idx on public.rag_queries (owner_id);
create index if not exists rag_query_misses_expected_chunk_id_idx on public.rag_query_misses (expected_chunk_id);
create index if not exists rag_query_misses_expected_document_id_idx on public.rag_query_misses (expected_document_id);
create index if not exists rag_query_misses_owner_id_idx on public.rag_query_misses (owner_id);
create index if not exists rag_response_cache_owner_id_idx on public.rag_response_cache (owner_id);
create index if not exists rag_retrieval_logs_owner_id_idx on public.rag_retrieval_logs (owner_id);
