-- Migration: Maximize RAG retrieval accuracy + speed
-- 1. Tune HNSW indexes (m=24, ef_construction=128)
-- 2. Add rag_retrieval_logs table for diagnostics
-- 3. Add content_hash dedup on document_embedding_fields
-- 4. Drop duplicate/redundant indexes
-- 5. Enhance hybrid scoring with quality + recency weighting
-- 6. Add analyze_rag_tables() utility function

set search_path = public, extensions;

-- ============================================================
-- 1. HNSW INDEX TUNING
-- Rebuild with m=24 (graph connectivity) and ef_construction=128
-- (build-time recall). Default was m=16, ef_construction=64.
-- ============================================================

drop index if exists document_chunks_embedding_hnsw_idx;
create index document_chunks_embedding_hnsw_idx
  on public.document_chunks using hnsw (embedding vector_cosine_ops)
  with (m = 24, ef_construction = 128);

drop index if exists document_memory_cards_embedding_hnsw_idx;
create index document_memory_cards_embedding_hnsw_idx
  on public.document_memory_cards using hnsw (embedding vector_cosine_ops)
  with (m = 24, ef_construction = 128);

drop index if exists document_index_units_embedding_hnsw_idx;
create index document_index_units_embedding_hnsw_idx
  on public.document_index_units using hnsw (embedding vector_cosine_ops)
  with (m = 24, ef_construction = 128);

drop index if exists document_embedding_fields_embedding_hnsw_idx;
create index document_embedding_fields_embedding_hnsw_idx
  on public.document_embedding_fields using hnsw (embedding vector_cosine_ops)
  with (m = 24, ef_construction = 128);

-- ============================================================
-- 2. RAG RETRIEVAL LOGS TABLE
-- Per-query diagnostics: candidate scores, latency breakdown,
-- miss detection.
-- ============================================================

create table if not exists public.rag_retrieval_logs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  query text not null,
  normalized_query text,
  query_class text,
  retrieval_strategy text,

  -- Candidate scores
  candidate_count integer not null default 0,
  top_similarity double precision,
  top_text_rank double precision,
  top_hybrid_score double precision,
  top_rrf_score double precision,
  mean_hybrid_score double precision,

  -- Selected citations
  selected_chunk_ids uuid[] not null default '{}',
  selected_document_ids uuid[] not null default '{}',
  selected_count integer not null default 0,

  -- Latency breakdown
  embedding_latency_ms integer,
  rpc_latency_ms integer,
  rerank_latency_ms integer,
  total_latency_ms integer,

  -- Source counts
  vector_candidate_count integer,
  text_candidate_count integer,
  memory_card_count integer,
  index_unit_count integer,
  embedding_field_count integer,

  -- Miss detection
  is_miss boolean not null default false,
  miss_reason text,

  -- Metadata
  embedding_cache_hit boolean,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists rag_retrieval_logs_owner_created_idx
  on public.rag_retrieval_logs(owner_id, created_at desc);
create index if not exists rag_retrieval_logs_miss_idx
  on public.rag_retrieval_logs(is_miss, created_at desc)
  where is_miss = true;
create index if not exists rag_retrieval_logs_strategy_idx
  on public.rag_retrieval_logs(retrieval_strategy, created_at desc);

alter table public.rag_retrieval_logs enable row level security;
grant select, insert, update, delete on table public.rag_retrieval_logs to service_role;
grant select on table public.rag_retrieval_logs to authenticated;

create policy "rag retrieval logs owner read" on public.rag_retrieval_logs
  for select to authenticated using (owner_id = (select auth.uid()));

-- ============================================================
-- 3. CONTENT_HASH DEDUP ON DOCUMENT_EMBEDDING_FIELDS
-- Replace the problematic unique(document_id, source_chunk_id,
-- field_type, content) constraint that indexes full text.
-- ============================================================

alter table public.document_embedding_fields
  add column if not exists content_hash text;

-- Populate for existing rows (md5 is fast and sufficient for dedup)
update public.document_embedding_fields
  set content_hash = md5(content)
  where content_hash is null;

-- Drop the old constraint. The constraint name is auto-generated by Postgres
-- from the unique(...) declaration. Try both possible names.
alter table public.document_embedding_fields
  drop constraint if exists document_embedding_fields_document_id_source_chunk_id_field_key;
alter table public.document_embedding_fields
  drop constraint if exists document_embedding_fields_document_id_source_chunk_id_fiel_key;

-- Create hash-based unique index
create unique index if not exists document_embedding_fields_dedup_idx
  on public.document_embedding_fields(document_id, source_chunk_id, field_type, content_hash);

-- ============================================================
-- 4. DROP DUPLICATE/REDUNDANT INDEXES
-- These single-column indexes are covered by composite indexes
-- with the same leading column.
-- ============================================================

-- document_chunks_document_id_idx(document_id)
--   superseded by document_chunks_document_idx(document_id, chunk_index)
drop index if exists document_chunks_document_id_idx;

-- document_sections_document_id_idx(document_id)
--   superseded by document_sections_document_idx(document_id, section_index)
drop index if exists document_sections_document_id_idx;

-- document_memory_cards_document_id_idx(document_id)
--   superseded by document_memory_cards_document_idx(document_id, card_type, confidence)
drop index if exists document_memory_cards_document_id_idx;

-- document_images_document_id_idx(document_id)
--   superseded by document_images_document_idx(document_id, page_number)
drop index if exists document_images_document_id_idx;

-- document_labels_document_id_idx(document_id)
--   exact duplicate of document_labels_document_idx(document_id)
drop index if exists document_labels_document_id_idx;

-- document_embedding_fields_document_id_idx(document_id)
--   superseded by document_embedding_fields_document_idx(document_id, field_type)
drop index if exists document_embedding_fields_document_id_idx;

-- document_table_facts_document_id_idx(document_id)
--   superseded by document_table_facts_document_idx(document_id, page_number)
drop index if exists document_table_facts_document_id_idx;

-- document_index_quality_document_id_idx(document_id)
--   PK on document_index_quality(document_id) already serves as the index
drop index if exists document_index_quality_document_id_idx;

-- ============================================================
-- 5. ENHANCED HYBRID SCORING
-- Add quality_score, confidence, and recency factors to the
-- ranking formulas.
-- ============================================================

-- 5a. match_document_chunks_hybrid: add quality and recency weighting
create or replace function public.match_document_chunks_hybrid(
  query_embedding extensions.vector(1536),
  query_text text,
  match_count integer default 12,
  min_similarity double precision default 0.12,
  document_filters uuid[] default null,
  owner_filter uuid default null
)
returns table (
  id uuid,
  document_id uuid,
  title text,
  file_name text,
  page_number integer,
  chunk_index integer,
  section_heading text,
  content text,
  retrieval_synopsis text,
  image_ids uuid[],
  source_metadata jsonb,
  similarity double precision,
  text_rank double precision,
  hybrid_score double precision,
  rrf_score double precision,
  images jsonb
)
language sql
stable
set search_path = public, extensions, pg_temp
as $$
  with query as (
    select websearch_to_tsquery('english', coalesce(query_text, '')) as tsq
  ),
  vector_ranked as (
    select
      c.id,
      c.document_id,
      c.page_number,
      c.chunk_index,
      c.section_heading,
      c.content,
      c.retrieval_synopsis,
      c.image_ids,
      1 - (c.embedding <=> query_embedding) as similarity,
      (
        ts_rank_cd(c.search_tsv, query.tsq) +
        (ts_rank_cd(d.title_search_tsv, query.tsq) * 3.0)
      )::double precision as text_rank,
      row_number() over (order by c.embedding <=> query_embedding) as vector_rank,
      null::bigint as text_match_rank,
      coalesce((d.metadata->'rag_indexing_version') is not null, false) as has_deep_index,
      d.updated_at as doc_updated_at,
      coalesce(
        (select q.quality_score from public.document_index_quality q where q.document_id = c.document_id),
        0.7
      ) as quality_score
    from public.document_chunks c
    join public.documents d on d.id = c.document_id
    cross join query
    where (document_filters is null or c.document_id = any(document_filters))
      and (owner_filter is null or d.owner_id = owner_filter)
      and d.status = 'indexed'
      and 1 - (c.embedding <=> query_embedding) >= min_similarity
    order by c.embedding <=> query_embedding
    limit greatest(match_count * 6, 48)
  ),
  text_ranked as (
    select
      c.id,
      c.document_id,
      c.page_number,
      c.chunk_index,
      c.section_heading,
      c.content,
      c.retrieval_synopsis,
      c.image_ids,
      1 - (c.embedding <=> query_embedding) as similarity,
      (
        ts_rank_cd(c.search_tsv, query.tsq) +
        (ts_rank_cd(d.title_search_tsv, query.tsq) * 3.0)
      )::double precision as text_rank,
      null::bigint as vector_rank,
      row_number() over (
        order by
          (
            ts_rank_cd(c.search_tsv, query.tsq) +
            (ts_rank_cd(d.title_search_tsv, query.tsq) * 3.0)
          ) desc,
          c.embedding <=> query_embedding
      ) as text_match_rank,
      coalesce((d.metadata->'rag_indexing_version') is not null, false) as has_deep_index,
      d.updated_at as doc_updated_at,
      coalesce(
        (select q.quality_score from public.document_index_quality q where q.document_id = c.document_id),
        0.7
      ) as quality_score
    from public.document_chunks c
    join public.documents d on d.id = c.document_id
    cross join query
    where (document_filters is null or c.document_id = any(document_filters))
      and (owner_filter is null or d.owner_id = owner_filter)
      and d.status = 'indexed'
      and (c.search_tsv @@ query.tsq or d.title_search_tsv @@ query.tsq)
    order by (
      ts_rank_cd(c.search_tsv, query.tsq) +
      (ts_rank_cd(d.title_search_tsv, query.tsq) * 3.0)
    ) desc
    limit greatest(match_count * 6, 48)
  ),
  combined as (
    select * from vector_ranked
    union all
    select * from text_ranked
  ),
  scored as (
    select
      id,
      document_id,
      page_number,
      chunk_index,
      section_heading,
      content,
      retrieval_synopsis,
      image_ids,
      max(similarity)::double precision as similarity,
      max(text_rank)::double precision as text_rank,
      min(vector_rank) as vector_rank,
      min(text_match_rank) as text_match_rank,
      max(quality_score)::double precision as quality_score,
      bool_or(has_deep_index) as has_deep_index,
      max(doc_updated_at) as doc_updated_at
    from combined
    group by id, document_id, page_number, chunk_index, section_heading, content, retrieval_synopsis, image_ids
  ),
  scored_metrics as (
    select
      scored.*,
      (
        (scored.similarity * 0.62)
        + (least(scored.text_rank, 1) * 0.22)
        + (scored.quality_score * 0.10)
        + (case when scored.doc_updated_at > now() - interval '90 days' then 0.06 else 0 end)
      )::double precision as hybrid_score,
      (
        coalesce(1.0 / (60 + scored.vector_rank), 0) +
        coalesce(1.0 / (60 + scored.text_match_rank), 0)
      )::double precision as rrf_score
    from scored
  ),
  hybrid_candidates as (
    select id
    from scored_metrics
    order by hybrid_score desc, similarity desc, text_rank desc
    limit match_count
  ),
  vector_candidates as (
    select id
    from scored_metrics
    order by similarity desc, hybrid_score desc
    limit match_count
  ),
  text_candidates as (
    select id
    from scored_metrics
    order by text_rank desc, hybrid_score desc
    limit match_count
  ),
  rrf_candidates as (
    select id
    from scored_metrics
    order by rrf_score desc, hybrid_score desc
    limit match_count
  ),
  candidate_ids as (
    select id from hybrid_candidates
    union
    select id from vector_candidates
    union
    select id from text_candidates
    union
    select id from rrf_candidates
  )
  select
    c.id,
    c.document_id,
    d.title,
    d.file_name,
    c.page_number,
    c.chunk_index,
    c.section_heading,
    c.content,
    c.retrieval_synopsis,
    c.image_ids,
    d.metadata as source_metadata,
    c.similarity,
    c.text_rank,
    c.hybrid_score,
    c.rrf_score,
    public.chunk_image_metadata(c.image_ids) as images
  from scored_metrics c
  join candidate_ids candidates on candidates.id = c.id
  join public.documents d on d.id = c.document_id
  order by c.hybrid_score desc, c.rrf_score desc, c.similarity desc, c.text_rank desc
  limit match_count;
$$;

-- 5b. match_document_index_units_hybrid: add extraction_mode boost
create or replace function public.match_document_index_units_hybrid(
  query_embedding extensions.vector(1536),
  query_text text,
  match_count integer default 24,
  min_similarity double precision default 0.1,
  document_filters uuid[] default null,
  owner_filter uuid default null
)
returns table (
  id uuid,
  document_id uuid,
  source_chunk_id uuid,
  source_image_id uuid,
  unit_type text,
  title text,
  content text,
  page_start integer,
  page_end integer,
  heading_path text[],
  normalized_terms text[],
  source_span jsonb,
  quality_score real,
  extraction_mode text,
  similarity double precision,
  text_rank double precision,
  hybrid_score double precision,
  metadata jsonb
)
language sql
stable
set search_path = public, extensions, pg_temp
as $$
  with query as (
    select websearch_to_tsquery('english', coalesce(query_text, '')) as tsq,
      regexp_split_to_array(lower(coalesce(query_text, '')), '\s+') as terms
  ),
  ranked as (
    select u.id, u.document_id, u.source_chunk_id, u.source_image_id, u.unit_type, u.title, u.content, u.page_start,
      u.page_end, u.heading_path, u.normalized_terms, u.source_span, u.quality_score, u.extraction_mode,
      (1 - (u.embedding <=> query_embedding))::double precision as similarity,
      (ts_rank_cd(u.search_tsv, query.tsq)
        + case when u.normalized_terms && query.terms then 0.25 else 0 end
        + case when u.unit_type in ('askable_question', 'table_fact', 'clinical_fact') then 0.06
               when u.unit_type = 'section_summary' then 0.03
               else 0 end
      )::double precision as text_rank,
      u.metadata
    from public.document_index_units u
    join public.documents d on d.id = u.document_id
    cross join query
    where d.status = 'indexed'
      and (document_filters is null or u.document_id = any(document_filters))
      and (owner_filter is null or d.owner_id = owner_filter)
      and u.source_chunk_id is not null
      and (u.search_tsv @@ query.tsq or u.normalized_terms && query.terms)
    order by text_rank desc, similarity desc
    limit greatest(match_count * 3, 48)
  )
  select id, document_id, source_chunk_id, source_image_id, unit_type, title, content, page_start, page_end, heading_path,
    normalized_terms, source_span, quality_score, extraction_mode, similarity, text_rank,
    (
      (similarity * 0.52)
      + (least(text_rank, 1) * 0.28)
      + (quality_score * 0.12)
      + (case when extraction_mode in ('model_heavy', 'hybrid') then 0.04 else 0 end)
      + (case when unit_type = 'askable_question' then 0.04 else 0 end)
    )::double precision as hybrid_score,
    metadata
  from ranked
  order by hybrid_score desc, similarity desc, text_rank desc
  limit match_count;
$$;

-- ============================================================
-- 6. ANALYZE UTILITY FUNCTION
-- Call after large ingestion batches to update query planner
-- statistics on key tables.
-- ============================================================

create or replace function public.analyze_rag_tables()
returns void
language plpgsql
set search_path = public, extensions, pg_temp
as $$
begin
  analyze public.document_chunks;
  analyze public.document_memory_cards;
  analyze public.document_index_units;
  analyze public.document_embedding_fields;
  analyze public.document_table_facts;
  analyze public.documents;
end;
$$;

revoke execute on function public.analyze_rag_tables() from public, anon, authenticated;
grant execute on function public.analyze_rag_tables() to service_role;

-- ============================================================
-- 7. UPDATE reset_document_index TO HANDLE NEW TABLE
-- ============================================================

create or replace function public.reset_document_index(p_document_id uuid)
returns void
language plpgsql
set search_path = public, extensions, pg_temp
as $$
begin
  perform set_config('statement_timeout', '180000', true);
  delete from public.document_index_units where document_id = p_document_id;
  delete from public.document_memory_cards where document_id = p_document_id;
  delete from public.document_sections where document_id = p_document_id;
  delete from public.document_table_facts where document_id = p_document_id;
  delete from public.document_embedding_fields where document_id = p_document_id;
  delete from public.document_index_quality where document_id = p_document_id;
  delete from public.document_chunks where document_id = p_document_id;
  delete from public.document_images where document_id = p_document_id;
  delete from public.document_pages where document_id = p_document_id;
end;
$$;

-- ============================================================
-- 8. UPDATE search_schema_health TO CHECK NEW TABLE
-- ============================================================

create or replace function public.search_schema_health()
returns jsonb
language plpgsql
stable
set search_path = public, extensions, pg_catalog, pg_temp
as $$
declare
  missing text[] := array[]::text[];
  vector_type_oid oid;
  vector_schema text;
  index_name text;
begin
  select t.oid, n.nspname
  into vector_type_oid, vector_schema
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace
  where t.typname = 'vector'
    and n.nspname = 'extensions'
  limit 1;

  if vector_type_oid is null then
    missing := array_append(missing, 'extensions.vector_type');
  end if;

  if vector_type_oid is not null and not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'match_document_chunks'
      and p.proargtypes[0] = vector_type_oid
  ) then
    missing := array_append(missing, 'match_document_chunks.extensions_vector_signature');
  end if;

  if vector_type_oid is not null and not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'match_document_chunks_hybrid'
      and p.proargtypes[0] = vector_type_oid
  ) then
    missing := array_append(missing, 'match_document_chunks_hybrid.extensions_vector_signature');
  end if;

  if vector_type_oid is not null and not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'match_document_memory_cards_hybrid'
      and p.proargtypes[0] = vector_type_oid
  ) then
    missing := array_append(missing, 'match_document_memory_cards_hybrid.extensions_vector_signature');
  end if;

  if vector_type_oid is not null and not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'match_document_index_units_hybrid'
      and p.proargtypes[0] = vector_type_oid
  ) then
    missing := array_append(missing, 'match_document_index_units_hybrid.extensions_vector_signature');
  end if;

  if to_regclass('public.document_index_units') is null then
    missing := array_append(missing, 'document_index_units.table');
  end if;
  if to_regclass('public.rag_retrieval_logs') is null then
    missing := array_append(missing, 'rag_retrieval_logs.table');
  end if;
  if not exists (select 1 from pg_class where relname = 'documents_title_trgm_idx') then
    missing := array_append(missing, 'documents_title_trgm_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_chunks_content_trgm_idx') then
    missing := array_append(missing, 'document_chunks_content_trgm_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_labels_label_trgm_idx') then
    missing := array_append(missing, 'document_labels_label_trgm_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_summaries_summary_trgm_idx') then
    missing := array_append(missing, 'document_summaries_summary_trgm_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_index_units_embedding_hnsw_idx') then
    missing := array_append(missing, 'document_index_units_embedding_hnsw_idx');
  end if;
  if not exists (select 1 from pg_class where relname in ('document_embedding_fields_owner_idx', 'document_embedding_fields_owner_id_idx')) then
    missing := array_append(missing, 'document_embedding_fields_owner_idx');
  end if;
  if not exists (select 1 from pg_class where relname in ('document_table_facts_owner_idx', 'document_table_facts_owner_id_idx')) then
    missing := array_append(missing, 'document_table_facts_owner_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_table_facts_source_image_idx') then
    missing := array_append(missing, 'document_table_facts_source_image_idx');
  end if;
  if not exists (select 1 from pg_class where relname = 'document_embedding_fields_dedup_idx') then
    missing := array_append(missing, 'document_embedding_fields_dedup_idx');
  end if;
  foreach index_name in array array[
    'document_pages_document_idx',
    'document_images_document_idx',
    'document_sections_document_idx',
    'document_memory_cards_document_idx',
    'document_chunks_document_idx',
    'document_table_facts_document_idx',
    'document_embedding_fields_document_idx',
    'document_index_units_document_idx',
    'ingestion_jobs_status_next_run_idx',
    'ingestion_jobs_document_status_idx',
    'documents_owner_status_idx',
    'import_batches_status_created_idx',
    'storage_cleanup_jobs_status_created_idx'
  ] loop
    if not exists (select 1 from pg_class where relname = index_name) then
      missing := array_append(missing, index_name);
    end if;
  end loop;

  return jsonb_build_object(
    'ok', cardinality(missing) = 0,
    'missing', missing,
    'vector_extension_schema', vector_schema,
    'checked_at', now()
  );
end;
$$;

revoke execute on function public.search_schema_health() from public, anon, authenticated;
grant execute on function public.search_schema_health() to service_role;
