-- SUPERSEDED / INTENTIONAL NO-OP (neutralized 2026-07-03).
--
-- This migration originally rewrote public.match_document_chunks_text to batch
-- the N+1 label/summary lookups AND changed its RETURNS TABLE shape (it added a
-- `lexical_score` output column). It must NOT be applied, for two reasons:
--
--   1. It would ERROR. Adding an output column to a set-returning function via
--      CREATE OR REPLACE is illegal ("cannot change return type of existing
--      function") without a DROP FUNCTION first — so this file cannot apply on
--      any database whose match_document_chunks_text already exists.
--
--   2. It would REGRESS the live function. The deployed match_document_chunks_text
--      already carries the N+1 batching AND a superior title-boost dual-path
--      implementation (chunk_seed / title_docs / title_matches) that this file
--      does not contain. Applying it would replace the better function with this
--      older single-path one.
--
-- The canonical retrieval-RPC definitions live in supabase/schema.sql. Fully
-- reconciling the live retrieval RPCs into migrations/schema.sql is tracked as a
-- separate, golden-eval-gated backlog item (the known hybrid-RPC drift). This
-- file is kept as a documented no-op purely to preserve migration ordering.
select 1;
