-- NEUTRALIZED 2026-07-08 — DO NOT RESTORE THE ORIGINAL BODIES.
--
-- This migration originally rewrote retrieval_owner_matches() plus ~10 retrieval
-- RPCs. It was never applied to the live project. The 2026-07-08 pre-apply
-- investigation (docs/database-drift-detection.md) found that:
--
--   1. Its actual purpose — the public-owner sentinel in retrieval_owner_matches
--      (owner_filter = '000…000' -> row_owner_id IS NULL) — is ALREADY live and
--      identical, so the owner-scoping change was a no-op relative to live.
--   2. Live has DIVERGED FORWARD from these bodies via later raw-SQL work that
--      was never captured in a migration: match_document_chunks carries an
--      hnsw.ef_search=100 plpgsql wrapper (higher vector recall);
--      match_document_chunks_text and match_document_table_facts_text carry
--      richer multi-strategy implementations; match_document_chunks_hybrid uses
--      a left-join for quality_score.
--
-- Applying the original migration would therefore REGRESS live retrieval
-- quality. It is neutralized to a no-op so a future `supabase db push` can never
-- overwrite the newer live bodies. The correct resolution is the opposite
-- direction — forward-codify the live bodies into supabase/schema.sql and a new
-- migration (tracked in the drift-detection reconciliation backlog). Until that
-- lands, check:drift allowlists these functions with the accurate reason.

select 1 where false;
