// Generated by scripts/build-therapies-index.mjs. Do not edit.
export const THERAPY_CATALOGUE_ASSETS = {
  full: "therapies.25a7332ca7e408f5.json",
  index: "therapies-index.aae0c8650870f0a2.json",
} as const;

// The generation this one replaced. Retained on disk across one content-
// changing regeneration so a client whose bundle still names the previous
// content-addressed URL does not 404 mid-session; older generations are
// pruned. `useTherapyData` also falls back to the unversioned alias for
// bundles that include that fallback (pre-fallback clients are best-effort).
export const THERAPY_CATALOGUE_ASSETS_PREVIOUS = {
  full: "therapies.0fbdb42a8ac91b14.json",
  index: "therapies-index.efb2b0703a124d70.json",
} as const;

// First-paint metadata for the Therapy home. The landing page renders only
// the catalogue count and trusted default artifact destinations, so it must
// not download and parse a record projection before its LCP can paint.
export const THERAPY_CATALOGUE_SUMMARY = {
  totalCount: 205,
  needsReviewCount: 98,
  defaultBriefSlug: "applied-relaxation-relaxation-based-therapy",
  defaultSheetSlug: "acceptance-and-commitment-therapy-act",
} as const;
